label act1_day13:
    scene bg black
    "Sunday"
    scene bg black
    m "Hey [player]! Thanks for having me over."
    m "It's nice having just the two of us here...alone..."
    m "This IS what you wanted, right? To be alone with me?"
    n "Or was it me?"
    s "Or me?"
    y "Or me?"
    "The next thing I know, I'm being held down to my chair by each of the girls."
    mc "Wha- what are you doing?"
    "Monika/Sayori: Exactly what you wanted..."
    "Natsuki/Yuri: Keeping you away..."
    qu "From me..."
    "A familiar silhouette approaches."
    qu "It's exactly what I thought. You just cling to any girl who gives you attention. "
    qu "Showing no thought of your own. What were you before me?"
    "I try to answer, but no words come out. "
    "I scream, but only silence is the result of my hoarse throat. "
    "As I look up, the silhouette disperses and Elsea is standing above me, towering over me looking down as if I was a bug."
    "Elsea: That's correct! without me...you're nothing!"
    scene bg bedroom
    "My eyes shoot open as I wake up."
    mc "Agh...Dammit..."
    "There I go thinking I was over her. Who am I kidding? "
    "It's been two weeks and I've done nothing but sulk or find distractions. "
    "And everything I've done so far has been because of them."
    "And I can't stop thinking about what Sayori and Natsuki said yesterday about Monika and I going together."
    " While it's easy to write off Natsuki as just teasing for shits and giggles, Sayori has been tiptoeing around the same thing for the past week. "
    "I mean, it's not a bad thought. And I'd be lying if I didn't admit I haven't wondered if we had gotten together beforehand, but our worlds are just too far apart now. "
    "And I don't want her to grow to hate me. Not until I-"
    "*GGRRWLLLL*" #[Stomach Growling Sound]"
    mc "Oh yeah. Food."
    scene bg living_room_morning
    "After washing up and heading downstairs to make a quick breakfast, I realize that it's only 6:54."
    "Man, yesterday threw my sleep schedule off. "
    "At least it's a positive shift this time. "
    "I've got a few hours so..."
    "I find the remote and open up a streaming site. "
    "As soon as I'm on my profile and begin flipping through the recommendations..."
    mc "Wow. I really didn't have a personality without her."
    "Nothing but rom coms and chick flicks. "
    "At this point, I might as well delete my profile and start all over. "
    "As I hover over the delete option, I hesitate."
    mc "Eh. I barely watch anything anyway."
    "I walk over to pick up a controller and turn a game on, but as I'm flipping through them..."
    mc "Nothing but multiplayer or co-op. *Sigh*"
    "I pick something that I feel I can eat some time, but after about 15 minutes, I'm already getting bored of it. "
    "I set the controller down thinking about what I can even do to pass the time. "
    "As I sit back and think, my mind goes back to my dream. All the girls have helped keep my mind off Elsea. "
    "From the club, to the poems and the books-"
    mc "That's it!"
    "I run over to the closet and take out my book bag and retrieve the copy of Portrait of Markov Yuri lent to me. "
    "I walk over to the couch and sit down as I begin to read."
    scene bg living_room_morning
    with dissolve
    "When I noticed I'm about half way done with the book, I stop to check the time. "
    "10:22."
    mc "She did say 10am, right?"
    "I check my messages and sure enough, yup. 10am. Huh. I wonder what's taking he-"
    mc "I DIDN'T SEND HER MY ADDRESS DID I?"
    "Crap crap crap! I call Monika, hoping to catch her in time to apologize."
    "*riing* *riing*"
    m "Hello?"
    mc "Monika! Hey, [player]. Sorry, I just realized, I never gave you my address. "
    mc "Figured you may have been waiting for that looking at the time. I can send it know if that oka-"
    m "Oh, no worries. I know where you live."
    "..."
    mc "...What."
    m "Hee hee. sorry, I just realized how creepy that sounded. I've been to Sayori's house before, so I know my way."
    mc "Oh. Yeah. That...makes sense."
    m "I was about to be on time until I realized I forgot my laptop charger, so I had to double back to get it. I'm about 5 minutes out. Sorry to make you worry."
    mc "Oh, it's no biggie. Yeah. See you soon."
    m "See you soon~"
    "As I hang up, I expect to be calming down, but the anxiety keeps building. "
    "It's not like I haven't had girls over. It's just...none like THE Monika. "
    "The class star. "
    "The object of every guy's eye...which is exactly why Sayori and Natsuki are crazy thinking she has any feeling more than friendship with me."
    "Right. Just friends. Just..."
    "*DING DONG*" #[Doorbell Sound]"
    "That's her! "
    "Okay. Calm down. You got this. "
    "You got this."
    scene bg front_door_morning
    "I open the door to see Monika looking at the address and her phone."
    m "Oh, good. I thought I went to the wrong side of Sayori for a second."
    "I stand there and slightly gawk at Monika's outfit. "
    "If this is her casual, then her formal attire must be top notch."
    mc "Ah...yeah! Hi! Umm...come in."
    "I hold my hand out to guide her way like I'm some sort of butler as she walks in giggling."
    m "Well, I see you're quite the host."
    mc "Oh, uh. Thanks."
    scene bg living_room_morning
    "Monika walks into the living room to sit, looking around taking everything in."
    mc "Uh, Do you need a drink? I can get you aaaaaaa..."
    "Crap! What do I have? "
    "Let's see...lukewarm bottle water and sparkling water in the pantry. What's in the fridge?"
    "..."
    "..."
    "DAMMIT! I can't remember since I had to move stuff for the cupcakes! Maybe I can-"
    m "I've never had it, but I can try it since you're so persistent about it."
    mc "... Wha?"
    m "The 'Aaaaaa'. I can try that if you don't mind."
    "I stare at Monika in confusion until she starts giggling. "
    "Then it hits me that I stalled on the word 'a' while stuck in thought."
    "Gah!!! I'm such a fricking goober!"
    mc "Eh heh. Good one. I kinda had a brain fart trying to remember what I actually had. "
    mc "All that's in my memory is the cupcakes."
    m "Oh yeah! Natsuki told me you two made good work with those. "
    m "She even had a compliment or two about your part."
    mc "Really? Huh. I'm surprised she said something good about me."
    m "Well, she did frame it as a compliment to herself. She basically compared it to training a dog."
    mc "That's...not surprising."
    m "Do you mind if I take a look at the cupcakes?"
    mc "Depends. Are you sure you're not working for Sayori?"
    m "Hee hee. I promise there will be no heist of baked goods."
    mc "In that case, by all means."
    "Monika gets up and opens the fridge."
    m "You two did a wonderful job! These look delicious. Hmm..."
    "I lean over and see Monika trying to open one of the containers."
    mc "Uh, what are you doing?"
    m "Just getting a closer look."
    mc "I mean, they all look the same. I just don't want any to get ruined."
    m "I'll be as careful as possible. But if my finger just so happens to accidentally get frosting on it while inspecting..."
    "Monika winks at me in her coy way that always gets me blushing. "
    "I start rubbing the back of my neck, unable to think of a response."
    m "Hee hee, I was just teasing, [player]. I know Natsuki takes pride in her work and I wouldn't want to ruin anything for her."
    mc "Yeah. Of course. I-I knew that. Welp! We should probably get started."
    "I have no idea what's going on. How is she so calm in this situation? "
    "My nerves are all over the place, but she's just so natural..."
    "Right. Because it's just like I thought. To her, it's like a visit with any other friend. "
    "Like Natsuki, Sayori, and Yuri. No different."
    m "So, do you have the printer down here somewhere or-"
    mc "Oh. It's upstairs. I can bring it down here real quick. It's not that heavy."
    m "Hmm. I'm surprised. Most other guys would jump at the chance of inviting me upstairs."
    "I freeze. Calm down. She's just teasing. "
    "Just like she said. Just pretend like it's Natsuki or Sayori."
    mc "I mean, If you wanna go upstairs, we can. Whatever makes you comfortable."
    "That catches Monika off guard as she begins to blush."
    m "Umm. Down here is fine. Yup. Enough room here to work."
    "I flash a sly smile to her."
    mc "I was just teasing Monika. You really fluster easily."
    "Monika begins to pout and then softly smiles."
    m "I'll admit, you got me. Fine. Let's call a truce on the teasing, okay?"
    mc "Deal."
    m "Besides, I don't want to give you any ideas since we're all alone."
    mc "What the- I thought you said-"
    m "Starting now!"
    "I open my mouth and just close it as Monika hums to herself looking around like she's completely innocent."
    "I head upstairs to go grab the printer while trying to keep my composure."
    #"[Office room]"
    "I...was not expecting to be in a flirt off with her, but it's done."
    "I hope. "
    "The odds are definitely stacked against me if she starts back up again. "
    "I should probably try to focus on the job at hand and get it done to avoid any other awkward situations."
    scene bg living_room_morning
    "I arrive back in the living room to see Monika has already made a workspace and has her laptop out and ready." 
    "She moved the coffee table closer to the couch for easy reach."
    mc "I see you made yourself comfortable."
    m "Oh, sorry. I figured I could at least get the area set up. "
    m "Wow! That's the printer you had? That's larger than I thought."
    mc "That's what sh-"
    "Nope!"
    mc "I mean, that's what aaa..."
    "Monika starts giggling."
    m "It's okay. Those jokes don't phase me. I kinda set you up for that one."
    mc "Heh heh...sorry."
    m "Hey, you're at home. No need to feel uneasy. Relax."
    mc "Sure, but, that's easier said than done when it's my club president here with me."
    "Monika frowns and looks down at her computer."
    m "Club president. Right."
    "As I move to set up the printer, I look up at Monika and can tell she's acting a bit different now."
    mc "Uh, okay. I got everything set up. Mind if I get it connected to your computer."
    m "Yeah. Here you go."
    "She hands me her laptop and I go through and install the printer."
    "When the test page comes out, I hand her back the laptop and she starts pulling up the pamphlets."
    "I lean over to take a peak as she's getting everything ready and she glances over at me."
    m "You know, it's a kind of insubordination to shoulder surf your president."
    mc "Huh?"
    "Where did this come from? Her response was so cold and direct that I'm taken back."
    mc "Sorry, I was just...sorry."
    "I scoot away to the far end of the couch."
    m "If you were my friend, I wouldn't have minded. But as you said, I am just your class president."
    mc "Wait...no Monika, I didn't mean it like-"
    m "But you're acting like that. I can tell you're uncomfortable." 
    m "I thought a few jokes here and there would help lighten the mood, but..."
    mc "I'm sorry. I do see you as a friend. A good friend."
    mc "It's just, a bit of a weird thing for me to still wrap my head around other people here with me who aren't my folks or Els-"
    "I freeze."
    "Monika chuckles."
    m "Of course that's it. I'm...sorry. I was a bit selfish there and..I understand."
    m "But I don't want you forcing anything with me. "
    m "If me being here makes you uncomfortable then-"
    mc "No! It's not that. I do enjoy your company. It's just..."
    m "It's...fine. Really. Let's just focus on the task at hand, okay?"
    mc "Yeah. Okay."
    "She continues to move around on her laptop as I sit then and watch her. She glances over at me and smiles."
    m "I wouldn't mind a second pair of eyes on this before we print."
    "She scoots towards me while turning the laptop in my direction. I scoot closer to take a look and go over what she has."
    mc "Wow. This is amazing! When did you find time to do this?"
    m "It wasn't easy, but was definitely worth it. "
    m "Any issues? Anything you notice that could be different or better?"
    mc "I've got nothing. You nailed it."
    m "Glad you think so! And here...are the reading suggestions!"
    "I look at it and just like the others, the layout looks masterful."
    mc "Great as well! I might need a copy of this for myself."
    m "Before I print this one, did you have any suggestions? "
    m "As you can see, we've also added some manga titles, so feel free to suggest some."
    mc "Oh, no. Thanks though. I don't think I have anything that matches what you guys already had."
    "Monika begins to frown again."
    m "*Sigh* I was afraid you'd say something like that. "
    m "You know, just because we were in the club longer, doesn't make you worse than us. Your opinions matter too."
    scene bg black
    "Elsea: ... Showing no thought of your own. What were you before me?"
    scene bg living_room
    mc "I...I'm okay with...what you already have. I haven't read anything lately, so I don't really have any suggestions to begin with."
    "Monika frowns at me as she takes the laptop back."
    m "Okay...let's just see how these come out."
    "She prints a copy of each one and then folds them."
    m "Huh. These should work just fine."
    mc "Yeah. They look great."
    m "Okay, let's get started then."
    "She begins printing the batches as I get up and prepare to grab the stack when it grows to a decent size."
    "As I sit down with a batch, I begin to fold them the way Monika did, taking my time to make sure the crease is in the right place. "
    "Monika sets her laptop down and begins to grab some to begin working on it. "
    "As she does, she begins humming to the beat of the printer."
    mc "Is that the same song as before?"
    m "Hmm? Oh. Yeah. "
    m "It's just weird how this printer is the sound I was looking for. "
    m "Well, the rhythm at least."
    m "I don't see myself making THAT kind of techno music."
    mc "Heh. That's cool. Even in the mundane you find something worthy."
    "Monika begins to scowl at me."
    mc "Th-that wasn't about myself, promise!"
    m "Okay..."
    mc "So, how has the song come along? Any progress?"
    m "Heh. Sadly this is the most progress I was able to get this week. "
    m "With the festival and all, it fell to the wayside."
    mc "Shame. From what I heard, I'll admit I liked it. Let me know when you finish it. I would love to listen to it."
    "Monika starts to blush a bit."
    m "Sucking up to your president I see..."
    mc "No, just wanting to support a friend."
    "That makes Monika pause and slowly smile."
    m "Well, I don't share my music with anyone. It is quite personal, you know."
    "I look over to her and our eyes meet."
    m "Good thing you make the cut."
    "She winks at me. I smile back at her. "
    "As I start thinking about the song and what lyrics would go with it, I pause as the words from her lyric sheet I found come to mind. "
    "Now that I think of it, the cadence of the words kinda fit her humming. But the lyrics were so-"
    mc "Hey, Monika..."
    m "Yes?"
    mc "About your song...were the lyrics for them the ones I found."
    m "Y-yeah. I'd say I'm surprised you pieced that together, but I've learned you're full of surprises at this point."
    mc "So were those thoughts...genuine? I'm kinda worried about you if they are."
    m "Well, hmmm. How do I put this?"
    "She stops folding and sits back to think for a while."
    m "Let's just say, I'll manage. "
    m "While it was exaggerated for the sake of emotional potency, I'd be lying if I didn't say there was a kernel of truth."
    mc "How big is the kernel?"
    "I turn to her and can see she's getting into a deep headspace. I can't stand to see her like this."
    mc "Sorry. That's personal. I'll take your word that you'll manage."
    m "It's...okay. I just don't want you worrying too much. You have enough to worry about as is."
    "We both sit in an awkward silence. I really do want to open up to her, but with all that's going on, I'd hate to be a distraction."
    m "Listen, [player]. About Friday. I want to-"
    mc "I know, and I'm sorry. I should've spoken up more to the rumors. I'm sure me rejecting them will get it to stop."
    m "That's not what-"
    "*BEEP BEEP*" # [Beeping Sound]"
    "Monica: Huh? What happened?"
    "I walk over to the printer to check the display." 
    "Cyan out."
    mc "It's okay. It just needs new ink. Just a moment."
    "I head upstairs to grab replacement cartridges for all of them just in case."
    "As I come back down, I see Monika on her phone texting."
    m "Well, Sayori and Yuri are done with the decorations."
    mc "Really? With them too, I'm surprised they came to a stopping point. "
    mc "I know how much of a runaway train Sayori can be when she sets her mind to it."
    m "Yeah. She's really persistent like that..."
    mc "Hey, can I ask you something?"
    m "Sure. Go ahead."
    mc "I've been kinda...worried about Sayori. "
    mc "There are days where she seems a bit out of it. "
    mc "I'm no expert, but I'm not convinced that it is a normal 'womanly problem'"
    "Monika begins to look away and twiddle with her phone in her hand."
    m "I'm sorry. It's not my place to say. I really hope she opens up to you on her own, it's just...the situation is delicate and pushing too much might not be the best for her."
    mc "So it IS something. I was hoping I was being paranoid."
    "What could it be that would cause Sayori to keep it a secret from me. Is it...no. It can't be..."
    mc "Does her situation have anything to do with me? Was it something I did or didn't do?"
    "Monika winces as she tries to find the words. "
    "That seals it for me. "
    "It's me. "
    "I begin to pull out my phone, but Monika grabs my hand."
    m "No! Don't! "
    m "You confronting her right now would be the worst thing for her! It took too long for her to get this comfortable talking to me about it. I..."
    "I begin to put my phone back as Monika begins to tear up."
    m "I don't want her to shut herself off due to mistrust. If she feels like she can no longer tell me things, I fear..."
    mc "Wait, is it that bad!?"
    m "All I can say is...please keep an eye on her. Okay? "
    m "I'm sure she'll open up to you soon. It's just that she's too worried about you and afraid she may put too much on you."
    mc "I-...I can see that. Fine. I'll wait for her to come to me. "
    mc "She did do the same for me, so I owe her that at least."
    m "Thank you. Don't worry. As long as we're there for her, I'm sure she'll see through this situation."
    mc "I...hope so. I'm...sorry for pressing you on it."
    m "It's fine. Really. I'd be more concerned if you didn't care as much as you do."
    mc "And thank you. For taking care of Sayori all this time. You have no idea how much that means to me."
    m "Trust me. I do."
    "We both smile at each other as we continue working on the last of the handouts."
    m "Alright! That looks like it's it. Thank you again for having me [player]. I can't imagine the headache this would have been doing at the library."
    mc "Anything I can do to help out, I'm there."
    "Monika then pulls out her phone to check the time."
    m "Okay, I should be able to have a bit of time to relax before-"
    mc "Busy schedule as always?"
    m "Heh heh, as always. With so many things I need to do, it seems I can rarely find time to do what I want to anymore."
    "I smack myself in the head as I come to a realization"
    mc "I JUST realized you could have just emailed me the handouts and I could have done this to give you a bit of free time."
    m "I thought of that too, but then I realized that I would miss out on spending time with you."
    m " And with my schedule, I need to take advantage of every opportunity to do the things I want."
    "I'm taken back a bit, but looking into her eyes, I can tell that was the truth."
    m "So this day killed two birds with one stone. Thank you!"
    "As she's getting the handouts clipped together and in her bag, I begin to think about what she said. "
    "She has made so many steps to get to know me better and spend time with me. I should try to return the favor."
    mc "So, do you mind some company on the way back home?"
    "Monika looks up at me with surprise."
    m "It's okay. I don't want you going out of your way. I'll be fine."
    mc "You'd be doing me a favor. I need an excuse to get out the house, and no better excuse than escorting a young maiden back home."
    "That gets a blushing giggle out of Monika."
    m "Well, I'm not one to impede on a young man's chivalry. Thank you."
    "We both head out as I lock the door."
    scene bg residential_day
    "As we are leaving, we see a car pull up to the side in front of Sayori's house. It's the same one from yesterday. As we pass it the windows begin to roll down."
    "Yuri's mom: Monika, is that you?"
    "Monika is thrown off a bit but regains her composure when she looks into the car."
    m "Oh, hey! How have you been?"
    "Yuri's mom: You know, same old same old. How's your mother doing?"
    "As they chat back and forth I can't help but think how awkward I am in these situations. "
    "Luckily I see an out as Yuri comes out of the door."
    y "Oh! Hello Monika. [player]. You two are finished as well?"
    mc "Yeah. I was just about to walk Monika home."
    "Yuri's mom: Oh, so is this your boyfriend Monika?"
    "Gah! Should have seen that coming."
    mc "Uhh...actually ma'am"
    y "Mother! Please! Not every male and female companionship is romantic!"
    "Yuri catches herself as she realizes the situation she stepped in."
    y "I am sorry for my outburst. It is just, there have been rumors. "
    y "But seeing that they are rumors I choose not to engage with them. That is the correct assumption, yes?"
    "Me and Monika look at each other a bit uneasy about the situation."
    "No. This is a rumor that I need to be the one to put to bed."
    m "Well, actually we're-"
    mc "Friends! We're friends. Nothing romantic."
    "I want to look at Monika to check her reaction, but I can tell that may cause even more confusion."
    m "Heh. You heard him. Yup. Just platonic friends."
    "Yuri's mom: Sweetie. You got a chance! Go for it!"
    y "MOTHER!!"
    mc "I'm sorry ma'am. I'm actually not in the headspace for a relationship right now."
    "Yuri's Mom: Okay, but don't sleep on either of these ladies too long. You just might miss your chance."
    "Yuri covers her face with her hands as it turns bright red."
    y "Oh my god, I want to die..."
    mc "Well, it was nice meeting you ma'am. Monika, you ready to go?"
    "She just stands there looking down. She then crouches through the window."
    m "I'm sorry, Ma'am, if Yuri is okay with it, can I get a ride from you?"
    "Wait, what? "
    "No. I get it. "
    "She wants to avoid us being seen together to keep those rumors at bay. "
    "She is looking at Yuri and it looks like they are mouthing to each other until Yuri starts nodding her head."
    y "Yes. It is alright with me."
    "Yuri's mom: Alright. Get in and buckle up."
    m "Sorry for the change of plans, [player]. "
    m "It just, I remembered Yuri was wanting a bit of help with some of the decoration details. "
    m "I was going to go over it through text, but this will be better."
    mc "Yeah. For sure. No problem. See you both tomorrow."
    y "Goodbye, [player]."
    "I stand there and watch as they both get in the car and drive off"
    "As I wave to Monika, she's looking back with a sad smile, but then something behind me catches her attention. I turn around to see what it was and..."
    "*SLAM*" #[Sla,mming Sound]"
    "Was that my door?"
    "...SAYORI!"
    "I run to the door and check it. It's unlocked."
    "I slowly open the-"
    mc "Wait! This is MY house!"
    scene bg kitchen
    "I burst through the front door."
    mc "Sayori!"
    s "EEPP!!!"
    "She scurries out of the kitchen and upstairs. I run to the fridge to check on the cupcakes. "
    "Looks like I made it just in time. All cupcakes accounted for."
    mc "*sigh* That girl. What am I gonna..."
    scene bg front_door_night
    "I walk over to the stairs and sit and wait. After a few minutes, she comes down and sits on the stairs behind me."
    s "...Sorry."
    mc "So...why run upstairs?"
    s "You were blocking the door! Where else was I gonna run?"
    mc "Why did you run in the first place?"
    s "It was just a reflex!!"
    mc "Yeah, reflexes of a dodo."
    "Sayori kicks me in the back of the head."
    s "Meanie..."
    mc "Hey. You're the one trespassing."
    s "Hrmmm.."
    "We sit there for a bit until she comes down a few more steps to sit next to me."
    s "So, how'd it go with Monika?"
    mc "We got the handouts done. She really went all out on them. "
    mc "Just glad I was able to help in some way."
    s "Did you guys...talk about...anything?"
    "I look towards Sayori and can see a bit of worry in her eyes. "
    "Should I tell her that I know she's going through something? "
    "No. Monika said to let her start that conversation."
    mc "Yeah. We talked about a few personal things, her music, uhh the festival, yeah. "
    mc "That's about it. Nothing much."
    s "The personal things. Were they..."
    mc "We came to an understanding about the rumors. "
    mc "I will start speaking up to clear any confusion and reiterate that we are just friends."
    "Sayori places her hand on my shoulder."
    s "So you BOTH came to that conclusion?"
    "I nod to her."
    s "And you're happy with that conclusion?"
    "I sit and think. I want to say yes because she is a wonderful friend. But I know Sayori is expecting more."
    mc "Let's just say, for now I am."
    "Sayori gets up and kneels in front of me, meeting my eyesight."
    s "Hrmmmmmm..."
    "She is staring so hard her face begins to turn a bit red."
    s "Okay. I believe you."
    "She stands up and holds her hand out to me. I grab it and stand up."
    s "So, are you ready for the festival?"
    mc "As ready as I can be. I don't think there's anything else I can think of."
    s "You got a plan for delivering the cupcakes?"
    mc "Are you asking as Vice President Sayori or snack bandit Sayori."
    s "...Yyyess?"
    mc "I can ask Natsuki if she can come early to help. That or make two trips."
    s "I mean, you do have a fully capable friend who's close by, willing and able..."
    mc "Don't you have decorations to take?"
    s "Oh, Yuri actually has them all. There was a last minute thing she wanted to do with a few things so she decided to take them."
    mc "Hmmm...let me ask Natsuki first."
    "I pull out my phone and send Natsuki a message"
    s "Oh come on! Don't you trust me!?"
    mc "Sayori. You literally JUST broke into my house to steal some."
    s "Heh heh...I thought you forgot."
    mc "You didn't kick my head THAT hard."
    "*DING*"  #[Phone Message Notification Sound]"
    mc "Good news. Natsuki said you're good to have 1 cupcake in return for a lossless delivery."
    s "Hooray!"
    "*DING*" #[Phone Notification]"
    mc "Bad news. Failure to do so will lead to...penalty of death. "
    mc "MY death."
    s "...Horray?"
    "I stare at Sayori as I hold my hand out for a handshake."
    mc "Do you promise to not sneak any?"
    s "Hrmmmmm..."
    mc "Sayoriiii!"
    s "Mmmmm fine!"
    "She grabs my hand and begins shaking."
    s "I will promise...to try and not sneak any."
    mc "Good. And just to make sure..."
    "I keep hold of her hand and walk her out of the house."
    s "Hey! What the- If you want me out just say so, you don't have to-"
    scene bg house
    mc "So you DON'T want to get a cinnamon roll?"
    "Sayori's eyes light up."
    s "Mugiho's?!"
    mc "Yup!"
    s "EEEEE! Let's get going!"
    "She turns the tables by dragging me now."
    scene bg bedroom
    "As I lay in bed winding down, I begin to think about the festival, which then leads to thinking of Monika. "
    "She really has a lot on her plate, doesn't she? From what she said, she doesn't have a lot a free time. "
    "I hope she can get some time to enjoy herself."
    #"[Flashback to Scene]"
    m "... but then I realized that I would miss out on spending time with you..."
    "That's it! I should try and spend time with her during the Festival! "
    "I can try and talk to her before everything starts to see if she has some free time. "
    "Hopefully she'll not pull triple duty with other clubs."
    "I fall asleep anticipating the morning. All the anxiety and excitement make it difficult, but I manage to start dozing off at a decent time."

