label act1_day5:
    "Friday"

    scene bg black
    s "Hey [player]! Wanna hang out?"
    mc "Sure. Anytime!"
    qu "Mind if I join?"
    mc "Uh...Yeah!"
    mc "Hey Sayori! Isn't this fun?"
    "..."
    mc "Sayori?"
    qu "You don't need her."
    mc "Yeah. You're right..."
    qu "And I don't need you."
    mc "Yeah...you're right..."
    qu "Nobody needs you..."
    mc "..."
    e "Goodbye forever."
    mc "No...you're wrong..."
    e "I'm never wrong. I'm-"
    mc "No..."
    e "always-"
    mc "NO!!"
    scene bg bedroom
    mc "AAGGHHHH!!!"
    "I breathe heavily after being jolted awake by this dream."
    "I put my hand to my chest and focus on my breathing."
    "I am drenched in sweat and as I finally begin to collect myself, I look down to my floor as I adjust myself to the side of my bed."
    "Dammit. It's been a week. How long is this gonna last?"
    "As I lay there, the events from my dream keep playing out."
    "Nobody needs you..."
    mc "No! I am needed. And I am wanted. I..."
    "I just need to keep telling myself that."
    "As I reach for my phone I realize I woke up an hour before my alarm, but I'm too wired to even try to sleep again."
    mc "Might as well get ready now."
    scene bg kitchen
    "I do my regular routine, make breakfast and even lunch."
    "After I finish eating I look at the time."
    "6:05."
    "Sayori probably won't be awake for another half hour, let alone ready."
    "I could try and get some more work done, but I'm already starting to feel a burnout."
    "As I scroll through my phone, it hits me."
    mc "OH YEAH! GAUNTLETS!"
    scene bg bedroom
    "I run upstairs and go to my desk drawer where I placed the copy of Red Gauntlets I borrowed from Natsuki."
    mc "Might as well get some reading in."
    "I set a timer for 45 minutes, giving me plenty of time."
    scene bg bedroom
    "By the time the timer goes off, I'm already half way through."
    "Man, it's been a while since I read this thing. Kinda surreal looking at the beginning knowing what I know will happen."
    "I text Sayori to see if she's up."
    s "Yup. Gettin dressed now."
    "I put the manga back and start to head out to wait for her."
    scene bg residential_day
    "As I arrive to Sayori's house, she's running out with her mouth full of food and zipping up her bag."
    s "Franks mawm! Wuv wou!"
    "Sayori's mom: Jesus, child. Finish chewing! Your gonna choke doing all that."
    "She looks at me and gives a light smile and wave."
    "I wave back uncomfortably remembering the last time we met."
    s "Hey [player]! I'm here and on time!"
    "I give Sayori a somber smile."
    mc "Yeah. I'm proud of you."
    "Sayori beams as we begin walking."
    scene bg street_1
    "While watching Sayori walk with her enthusiastic bounce, I can't help but think about the dream I had."
    "I know I need to make it up to her and I know joining the club is a start, but it still feels like..."
    "I'm not really needed."
    "Did Elsea actually need me? She seems to be doing fine without me."
    "Hell, she looked happy when I saw her."
    "As I drift into my melancholy thoughts, I catch Sayori glancing at me. I'm just now realizing how silent it's been. God, even now, I'm ignoring Sayori for Elsea."
    mc "Uh.. so.."
    s "Hmm?"
    mc "Uhh...classes going okay for you?"
    "Sayori looks at me with a worried expression, but it slowly softens as she realizes what's happening."
    s "Yeah, just struggling with math, as always."
    s "Like, why do numbers get so crazy they turn into letters? And then become imaginary? And go on forever?"
    mc "Chances are there was some guy in a robe thousands of years ago asking the same question."
    s "Right? That's why I like literature so much. It doesn't have to be a puzzle you solve, it can be just an experience you enjoy."
    mc "Yeah. You're right..."
    "As we continue our philosophical conversation, I notice Sayori avoiding bringing up things that may make me think about Elsea."
    "I just wish my own brain showed the same courtesy."
    scene bg school_hall_2
    "As I walk out with my lunch, I try to find a place to go. I look out and take note of the courtyard to spot a place to sit."
    "Looks pretty clear. As I'm heading towards the exit, I notice a group of students walking out as well. And among that group is Elsea. "
    "I freeze up and continue to walk past them down the hallway other than heading in the same direction as them."
    "I try to keep my eyes focused on the end of the hallway, but I glance over at the last second and..."
    "Our eyes meet momentarily."
    "I grow pale as I continue to walk and keep myself from turning around until I hear the door close."
    "Crap. Where do I go now? Well, I was avoiding the cafeteria because her group was always there, so hopefully I can eat there. I'll eat quickly in case they come back around."
    scene bg cafeteria
    "I was able to find an empty space, but the location is unfortunate. No surprise, right near the trash. At least it won't draw attention, so I can appreciate the slight camouflage."
    "While I begin to unpack my lunch, I hear a group of girls walk past. My awareness shoots up just in case it's Elsea's group, but to my relief, she's not there."
    "As they pass, I notice the familiar pink head of hair in the back of the group. As she's looking around, she notices me. She gives a shy wave and I wave back."
    "I look back down at my lunch a bit conflicted with what I should do. Should I invite her to sit with me? I can try to ask to sit with her, but I doubt she would want me to sit with her friends. Plus, it would be kinda awkward if I were to-"
    n "Yo. Dummy."
    mc "Huh?"
    "The next thing I know she's sitting right across from me."
    mc "Oh. Uh, hey Natsuki. I was gonna ask you to sit, but I figured you'd wanna sit with the group you came in with."
    n "Yeah, they noticed you and..."
    n "God, they can be so annoying sometimes."
    mc "What do you mean?"
    "Natsuki starts to blush a little."
    n "They keep talking about boys and stuff and it's so gross. And when they saw me wave, they started asking questions and..."
    n "Yeah. I don't wanna talk about it."
    "I look at her curiously and glance at the group of girls she was with. I see them glancing over and giggling."
    mc "Oh..."
    "I also begin to blush a little bit from the awkwardness of the situation."
    n "I already know they're gonna talk. At least this way I don't have to hear it."
    mc "Um.. can I ask you something?"
    "Natsuki raises an eyebrow at me."
    n "No, I don't want to go out with you."
    mc "I was NOT gonna ask that!"
    "Natsuki begins to giggle to herself."
    n "As long as that's off the table, go ahead."
    mc "You sound like you don't really get along with them, so why do you hang out with them?"
    n "It's not that we don't get along. I've known them since grade school and we typically click just fine. It's just, sometimes they don't take me seriously and I don't feel comfortable talking about manga or baking with them."
    n "The last time I brought up Parfait Girls, they called it a kids book. Like we weren't all reading them like a few years ago. They sometimes make me feel like a kid and..."
    n "I need a break from it, you know?"
    "I look at how disheartened Natsuki looks."
    mc "Well, they aren't real friends if they don't respect your interests. It doesn't hurt them for you to like what you like."
    n "Eh..wish it was that simple."
    mc "Tell you what. If you need someone to talk to about stuff, I'm here for you. No matter the topic."
    "Natsuki begins to look at me slyly."
    n "Anything?"
    "I stop chewing and begin the stare at her. As she grows a devilish smile."
    mc "Well, anything you can't talk to with them."
    n "Oh? What's wrong buddy? You don't wanna hear about which tampons I nee-"
    mc "Like I said, anything that they won't here! So manga, anime, baking recipes, yeah. That stuff."
    "Natsuki begins to giggle."
    "As I continue to eat, Natsuki is scrolling on her phone. Huh. Did she already eat?"
    mc "So were you not hungry or did you eat already?"
    n "Huh? Oh. I uh..I forgot my lunchbox on the way out. Plus I'm a bit short on cash for food here. Don't worry about it though. I should be good."
    "She gives a weak smile as she looks back down to her phone."
    "I look down at my lunch and I still have about half of it left."
    mc "Do you want any of mine?"
    "Natsuki looks up with wide eyes. She takes some time looking at the food and shakes her head."
    n "N-no. I should be good. Don't worry, I do this all the time."
    mc "Look, it's okay. I'm good. I was getting full anyway."
    n "You don't have to."
    mc "But I want to. Please? Consider it a thank you for the cupcakes, the manga, the second chance..."
    n "Well, when you put it that way...I guess you do owe me."
    "Natsuki excitedly takes the food and scarfs it down in no time. "
    "For the remainder of the lunch period, we chat a bit and go over some of the manga that she's been reading. I'm left with quite the wishlist once we're done with."
    scene bg class_day
    "As the school day is coming to an end, I can't help but stay haunted by the dream I had to the point where I can barely pay attention in class. Luckily, I haven't been called on so far."
    "Am I really needed? I want to believe so. I feel like I was some help to Natsuki earlier, so there's that. I just need to not be a burden on Sayori anymore."
    "I can tell she's worried about me and I know I need to open up to her, but just saying how I feel..."
    "What would I even say? I miss her? I'm angry at her? I'm confused, sad, feel discouraged, disregarded, like an utter piece of-"
    "***RIIINNNGG***" #[Bell Ringing Sound Bit Here]
    "The final bell pulls me out of my mental spiral. I really need to get it together. I don't want to bring down the girls."
    "As I get up to leave, Mr. Agawa calls for me."
    a "[player], a moment, please."
    "I sheepishly walk over to his desk, reaching in my bag for my backlog work."
    mc "Uh, I have a couple more assignments done."
    "Mr. Agawa takes them and looks over them."
    mc "I know I'm not even half way done, but I do plan to work on them over the weekend."
    a "Well, I'm looking forward to your haul on Monday."
    a "But I wanted to talk to you about your post school road map. Have you made any progress with it?"
    mc "I..sorta forgot. But that's cus I'm trying to get all this done first!"
    "Mr. Agawa stands up and rubs the bridge of his nose."
    a "Look, I know you're trying, and I can see the potential. I just want you to see that in yourself. There's so many places you can be in the future, but you need to shoot for something. "
    a "Even if you don't hit your target, you'll find out more about yourself to make your next shot better. I mean, I originally went to school for architecture."
    mc "Wait, really? Then how did you end up as a teacher?"
    a "Just taking opportunities. If I had never taken that tutor job in college just to save up for a car, I would have never found this feeling. It was the knowledge I passed, the look of accomplishment they had after working so hard, that's what I realized teaching was what I truly wanted to do."
    mc "Wow. Do you ever think about getting back into architecture? Maybe as a missed opportunity?"
    a "Of course. But I never let it hold me back. Life is like driving: you only need to glance at the rear view, but looking back too long will veer you off course."
    "I sigh and begin to lightly smile."
    mc "Yeah. I'll keep that in mind, thanks."
    scene bg corridor
    "As I speed walk my way to the clubroom, I enter to see..."
    scene bg club_day
    "Just Monika."
    "Huh."
    "She is sitting at the teacher's desk writing and...humming?"
    "As I stand there quietly, I observe her humming a tune with her eyes closed and tapping her foot in a rhythmic pattern. "
    "As I slowly walk in, it looks like she's repeating the melody like she's trying to get it right. After a bit, she goes back to writing and repeating the process."
    "I make it to the front of the desk while she's humming again with her eyes closed and take a look at what she's writing. It looks like musical notes."
    "As she opens her eyes she's slightly startled by my presence."
    m "Eep!"
    m "Oh, [player]! How long have you been standing there?"
    "She proceeds to take ear plugs out of her ears."
    mc "S-sorry. I didn't want to disturb you, but I was also a bit curious.I didn't know you wrote music."
    "Monika gives a bit of a nervous laugh."
    m "Yeah, it's not that big a deal. It's just something I've been dabbling with here and there."
    mc "So is this the hobby you were talking about the other day?"
    m "Y..yeah. I know it's silly, but it's a song I've been writing. I've been chipping away whenever I find time and inspiration. Sadly those two factors rarely cross nowadays."
    mc "Well that sucks. Are you at least close to finishing? I mean, I only heard that bit and I would love to hear more. You have a nice voice."
    "Monika begins to blush."
    m "Well, I'm more of a piano player than a singer. And even that, I'm not very good at it."
    mc "Well if you play as good as you hum, then you've got a potential audience in me. I'd love to hear you play sometime."
    "Monika's eyes begin to gleam."
    m "Well, maybe I-"
    "SLAMM!!!!" #[Door Slamming Open sound bit here]
    "The door flings open while Sayori stumbles in with her arms full of books."
    s "Got the books and got the stragglers! Objectives complete!"
    "Natsuki and Yuri walk in behind her."
    m "Oh, there you two are. We were a bit worried that you weren't already here."
    y "I apologize for the tardiness. I had an unexpected matter that needed attention."
    n "Yuri needed my help to take a dump."
    y "NATSUKI!!!"
    "Everyone looks on with a shocked look at Natsuki while Yuri hides her bright red face behind her hair."
    y "Don't talk about that in mixed company!!"
    "Yuri walks briskly past me, making sure to avoid eye contact with me."
    n "What, you mean [player]? He barely counts due to his lack of balls"
    "Monika becomes furious."
    m "That's enough Natsuki! I've-"
    "I hold out my arm towards Monika to stop her."
    mc "No, it's okay Monika. Let her get things off her chest. I mean, it's not like anything is there to begin with."
    "There is a deafening silence in the room as Sayori, Monika, and Yuri stare at me in disbelief as I eye down Natsuki."
    "They slowly turn to her and she is staring right back at me with a scowl."
    "As the corners of her lips curl into a slight smile, she replies."
    n "Heh. Guess you have some balls after all."
    mc "Well, I couldn't let you be the only one."
    "Natsuki smirks and walk to her desk as Monika and Sayori look at each other, confused on what to do in this situation."
    mc "So, what books do you have?"
    s "Huh? Oh! Uh..these are the copies for our reading activity. I can't wait for you to-"
    mc "Sayori! Watch out!"
    "Sayori trips over the leg of a chair and spills the books on the floor, banging her elbow on the edge of a desk as she falls."
    s "Ssssss....ahhhhh....ssssss...."
    m "Sayori? Are you alright?"
    s "...ahhhhh..."
    "I run over to her to help her up and look at her arm."
    mc "Geez, Sayori. You have to slow it down sometimes. This is how you're always getting hurt."
    s "Ach! It's not that bad, just hit my funny bone a bit."
    mc "Do you need any ice? Is it bruised anywhere?"
    "I hold Sayori's elbow up and slowly massage around it."
    mc "Does it hurt anywhere here?"
    "Sayori starts to get a little red as she sheepishly responds."
    s "N..no. It's fine. A..actually, this makes it feel better."
    "She begins to beam a smile."
    mc "Well, be careful. I don't want you getting hurt. I might not be around to..help next...time."
    "Her smile begins to fade as she sees the look on my face."
    "She places her hand on my hand that was on her elbow."
    s "It's good to know that you still care this much. It's just like before."
    mc "Of course I care about you. I know it's been a bit weird, but you're still my best friend."
    "Sayori, smile slowly returns."
    "Monika comes from behind me to check on Sayori."
    m "Do you need me to get an ice pack from the nurse's office?"
    "Sayori shakes her head."
    s "It's not that serious. I'm fine."
    mc "Are you sure it's okay? Can you move it well?"
    s "Yeah, it's nothing! All good!"
    mc "Okay. I'll want to check before we leave just in case a bruise starts to form."
    s "Will do."
    m "Okay, everyone!"
    "We all walk up to Monika for the announcement."
    m "Sayori has brought the copies of the book we're reading for our activity."
    "Sayori starts handing the book out to us. As she hands me the book I read the title: Deadline."
    "As we read the back of the book, it looks to be about a high school student learning that he has a year to live as he starts senior year and the things he wants to get done to feel he's lived life to the fullest."
    "Yuri; I'm quite surprised by this selection for our inaugural activity. I was not expecting such a tension driven narrative."
    m "While the tension can be quite a hook, I really resonated with the idea of living life to the fullest. I'm also hoping you all can find something out of the story as well."
    "The more I hear about the story, the more I get interested in seeing the main character's path."
    n "Hmm, doesn't seem too dull. I wouldn't mind if we end up finishing it."
    m "I was hoping that we can start with an easier read that can also be compelling and possibly self reflective. "
    m "We can start reading and see where everyone is at in about 30 minutes to gauge reading speed. After that, we can set a stopping point."
    m "And just a reminder, everyone. It's not a race. I would rather you all take your time to fully absorb the story so we can have some great conversations about it."
    "We all nod our heads in agreement and begin to split off and begin reading. "
    "Yuri goes back to her space in the front row, Natsuki sits in her spot under the window, Monika goes to the teacher's desk, and me and Sayori sit next to each other near the middle."
    "As I begin reading, I begin to take note of how the main protagonist acts upon hearing about his diagnosis of an illness that will kill him by the end of the year. "
    "He acts brave and courageous, acting on things that most people would hesitate doing in the first place. "
    "He tries out for football and makes moves on a popular girl in his school who he develops a relationship with. There are many other interesting characters across the story that help shape what kind of person the student becomes by the end of the book."
    "I look at the clock and see that about 25 minutes have passed. I wonder how everyone else is doing?"
    "I look back towards Natsuki and she seems to be casually engaged in the story with her free hand resting on her chin."
    "Sayori seems to be around the same place as I am and looks to be fully engaged, excitedly reading with every page she turns."
    "I look at Yuri and...She's about twice as far as all of us. Her demeanor while reading is still as calm and focused as always."
    "I glance at Monika to see if I could gauge how far she is and..."
    "She quickly averts her eyes as soon as I glance over to her. "
    "Was she..."
    "No. She couldn't have been sneaking glances at me. She's acting the same and has the same flustered look on her face she did when I thought she was staring yesterday."
    "And if she did, it's probably because she's making sure I'm having a good time here. I mean, I am a new member. It's understandable."
    "Now that I think about it, she acts differently than I was expecting."
    "I remember whenever Elsea mentioned Monika, she seemed to paint her as a natural perfectionist who was more focused on her own accomplishments than others and craved the attention of others."
    "But the Monika I've seen here is much more...approachable. "
    "Yeah, she seems like she has a handle on a lot of things, but there's the slight flusters, the concerns for others, the indication that she has ambitions beyond her image. "
    "Even with the Elsea elephant in the room, Monika still treated me with a sense of comradery and not her acquaintance's ex boyfriend."
    "As I get lost in my analysis, I realize that I'm basically staring at her when she looks up towards me and our eyes meet. I swiftly avert my gaze and continue to read. "
    "I glance back and notice she is back to reading, but now she has a soft smile on her face."
    "After time was up, we stopped and discussed our thoughts on the book. During the discussion, Natsuki and Sayori both displayed interest in continuing the story, while it was obvious that Yuri had made it quite a bit farther as she had stopped herself multiple times from bringing up later plot points. [I added dialogue for this scene instead of a paragraph.] "
    "After a few more moments, Monika checks the time and closes her book, getting ready for her catchphrase, which I noticed she says a lot."
    m "Okay, everyone! Looks like that's about it for now. What did you guys think so far?"
    s "I'm really enjoying it. It's been a great read so far!"
    n "Yeah, I totally wouldn't mind to keep reading this. Surprisingly it caught my attention."
    s "Yeah, same! "
    y "I definitely found enjoyment with this read. Especially at the part further in when-"
    n "SPOILERS!! Geez! Nothing past chapter 3, remember!"
    y "M..My Apologies!!"
    "I had also brought up my interests and the connections I shared with the main character's points of view." 
    mc "This totally piqued my interest."
    mc "I kind of relate with this main protagonist. Like, he totally could just do nothing, but he chose to make the most about his situation."
    "As we all agree to continue reading together, Monika calls the club meeting to a close. As I'm closing my bag, I hear a ringtone from Monika's direction."
    "As I glance towards her, she has a bit of a distressed look on her face. When she puts her phone up, she begins to gather her things in a hurried fashion."
    "As I'm watching, I'm snapped out of my zone out by Sayori."
    s "Ready to roll [player]?"
    mc "Right behind you, Sayori."
    "As we say our goodbyes, Monika flies past us while zipping up her bag. As she's pulling the zipper closed on the bigger pouch, the smaller one in front flaps open and a folder filled with papers slips out causing them to scatter in front of us."
    m "Oh, Son of a- Ghahhh..."
    "Me and Sayori help her pick up a few while Monika frantically gathers them from our hands."
    m "Thanks, guys. Sorry for the rush, but have a good weekend!"
    "She rushes out the door before anyone else can."
    y "I hope that everything is alright. This is the first time that I have seen Monika depart before everyone else."
    n "I'm sure if it's important, she'll let us know."
    "As we begin to head out, I notice a piece of paper slightly poking out from under the teacher's desk. I guess Monika dropped this as well. She's probably far gone, so I can just try to give it to her on Monday."
    scene bg living_room_afternoon
    "After getting home, I plop my bag down and sit for a while and start to plan my weekend. While normally I would spend it either gaming or tagging along with Elsea, both of those are out of the question for different reasons."
    "If I'm gonna start focusing on my future, I need to get over the past. And that means..."
    "Saturday cram session."
    "No distractions. No excuses. I need to get this backlog down to nothing so I have nothing more to look back on."
    "I set everything up for tomorrow: Set out my meals, drinks, arranged the writing utensils and laptop. I should also get to bed early so I can just smash through it in one go."
    "As I head up and begin to get into my sleep ware, I feel the paper in my pocket. Monika's paper."
    "Should I open it?"
    "No! That's invading her privacy!"
    "Who knows what she could have written!"
    "It could even be a..confession..."
    "I shake the thoughts from my head."
    "Yeah, right. Like Monika would just write a confession like this. She has her pick of any guy in school. If anything, this is some guy's confession to her."
    "Wait. What if this isn't even Monika's paper? Crap. I begin to start cringing thinking of handing her this just for her to say it's not hers."
    "I mean I should read it just to make sure who it goes to. Like finding a wallet. "
    "You're not getting their address from their id  for anything bad, just to know where to return it."
    "Yeah! That's it! I'm not doing this to be nosy, but to make sure it's returned to the right person."
    "As I open it and begin to read, it looks like a poem, but there are some musical cues written around the main writing. "
    "Just then, I remembered that this was what Monika was working on earlier. I notice how short it is, but she did say she was still working on it."

    #On Screen Paper Animation
    "Just across the leaves"

    "I stand in the wind"

    "Flying with grace"

    "This is not the end"


    "Four walls. Entombed with my sword"

    "A dark window. I mark the way forward "

    "Do I see the mask in the dark?"

    "To find the gleam in the green."



    "To start the fire in your heart"

    "You must've known it from the start."

    "It can't take it all away"

    "Can't take away the strain"

    "Yes you've known it all before"

    "While I'm kneeling on the floor..."

    "Hmmm..."
    "I can't put my finger on it, but this seems off. "
    "It doesn't seem bad, like I can even judge if a poem is bad or not. It just seems like..I don't know, but I feel concerned."
    "It is like a polar opposite of what I would expect from Monika. Or maybe, is this how she feels for real? As I reread it again, It starts to resonate with me, but why?"
    "I fold the paper away and decide that I need to step away from this for now. I've got enough on my plate already. "
    "I'll get that crap done tomorrow, and then I'll worry about Monika's song."
    "I do my nightly routine and head to bed with shaky confidence about the weekend."
    
    return