label act1_day10:
    "Thursday"

    scene bg bedroom
    "***BEEP BEEP BE-***" #[Alarm sound bit here]"
    "As I get out of bed, I can't help but realize how light I've been feeling lately. "
    "I used to snooze this alarm at least 3 times, but now, I've got the drive to get stuff done. "
    "School isn't a drag anymore, the gossip has died down, and with the Literature club, I have something to look forward to."
    scene bg kitchen
    "After my bathroom routine, I get dressed and head down to start making breakfast and packing lunch. I've got enough time to make a hot meal this time."
    "As I'm getting things prepared, I think about Sayori."
    "Man, I hope she feels better soon. "
    "I have NO idea what any of that entails? But the way it was affecting her was rough. "
    "Hmm...maybe I can make her a breakfast sandwich as well. "
    "If anything, I can try and use the smell as a gentle way to get her up."
    scene bg house
    "As I head over to Sayori's I realize it might be better to go inside other than waiting outside. "
    "Better chance of getting her awake if I can entice her with food. "
    "As I reach the front gate, I hear the door open. As she walks out and notices me, she smiles and waves."
    s "Hey [player]! Good morning!"
    mc "Oh! Hey!"
    "As she walks towards me I look at her with concern and confusion."
    mc "You feeling...better?"
    s "Yeah...sorry for being so distant yesterday."
    mc "No, I'm sorry. I guess I kinda took it too far yesterday trying to get to school. "
    mc "I guess I forget how much you've got on your plate. Monika told us about the festival plans and that it was mainly your idea. "
    mc "Plus, Monika told me it was also because of..umm...lady problems"
    s "Fffrmrmm!!! No need to talk about that! "
    s "It's over, it's gone, it's in the past. "
    s "You've nothing to worry about and nothing to apologize for."
    mc "Uhh okay. But what do I do with this apology sandwich?"
    s "Sandwich?"
    "As I pull out the sandwich still warm in the foil, Sayori snatches it out of my hand and begins to devour it."
    s "Ampowogry awcefted."
    "She finishes the sandwich with a wide grin on her face that lasts our entire walk to school."
    scene bg class_day
    "As the final bell rings, I excitedly head towards the door when I am stopped by the voice of Mr. Agawa."
    a "[player]. A moment before you head off."
    "As I walk over to his desk, I see he is shuffling something inside one of his desk drawers."
    a "So. How goes the roadmap? You at least have a destination picked out?"
    mc "Yes. I do, sir."
    "..."
    "..."
    a "Care to elaborate?"
    mc "Oh! Uh...I was actually thinking of being a writer."
    "Mr. Agawa just looks at me with a raised eyebrow."
    a "Well, if that's your choice, I'm sure you put in some practice for your profession on your roadmap assignment."
    mc "Actually, kinda. I just need to do some research."
    mc "Right now, basically college for literature. I don't really know many options at the time outside of that."
    a "Well, there are many paths with that, it can be hard to determine. Tell you what..."
    "He looks in his drawer and pulls out a few college brochures."
    a "Here's a bit of help with the college part. "
    a "These are known for their literature departments. You can also try to look up the careers of graduates from any university that catches your eye to get a better idea."
    mc "Huh. Thanks! That will actually help a lot!"
    a "No problem. And I know this may seem a bit like overkill, but it's better to have unused plans than to be unprepared."
    mc "Will do. I'll make sure to get more of this done."
    scene bg club_day
    "I enter the room with no surprises to speak of. "
    "Yuri reading to herself? Check."
    "Natsuki rummaging in the closet? Check. "
    "Monika and Sayori chatting at the teacher's desk? Check. "
    "Even though I haven't been here long, it's comforting to walk into these settings and feel like everything is normal."
    "As I walked towards a chair, and sit down, I hear footsteps behind me. "
    "I turn around to a coy looking Natsuki"
    n "Y-yo."
    mc "Uhh. Hey."
    "Natsuki sits down in the chair in front of me backwards to stare directly at me."
    mc "Did...you need something?"
    n "Just checking if you were busy."
    mc "And if I wasn't?"
    n "Then I was gonna show you this!"
    "Natsuki pulls out a manga from behind her back. "
    "It is a volume of the Parfait Girls. "
    "While I'm familiar with the title, I don't know much more than a few characters names and the gist of the story"
    n "I just found a super rare copy of volume freakin Zero!"
    mc "Woah. Sweet find!"
    n "Right?! I've heard about the background from videos and such, but never got to read it myself."
    n "And since it's a...rare experience.."
    n "...I was...uhh..."
    mc "Hmm?"
    n "I mean if you want to, anyway uh...read it with...me?"
    "I'm a little thrown off by the request. I know how much manga means to her and I can see how much this one means to her. "
    "Now that I think of it, I'm probably the only one she CAN enjoy it with."
    mc "Sure. I'd be happy to. To be honest, I don't know much about the Parfait Girls, but don't mind the experience."
    "Her eyes light up from my response as she tries to play off her obvious excitement."
    n "You're in for a treat! Pun definitely intended! "
    n "Come on. Let's sit over here so we can read it better."
    "I follow her to her favorite spot on the floor under the window."
    "As we sit down, Natsuki begins to scoot in while holding the manga for us to both see. "
    "Wow. She is..quite close."
    "I take a glance at her and from the joy on her face, I can't tell if she doesn't notice or doesn't mind."
    n "Hey. You done reading yet? I'm ready to turn the page."
    "Her remark snaps me out of my thoughts. I've been so worried about her I forgot to read."
    mc "Oh, uh..sorry. Just a moment."
    n "No probs. Let me know when you're ready."
    mc "Aaaaand all caught up."
    "As we go through the book, I can see the genuine joy she gets out of just sharing her favorite things with others. "
    "This is the same smile she had when presenting her cupcakes. I'm glad she's comfortable expressing this type of joy. Especially knowing how others have treated her."
    m "Okay, everyone! Let's all come to the front and get started."
    n "Aww man! It was just getting good."
    mc "Well, looks like we'll have to finish it another time."
    n "I hope we can soon. I really wanna finish this thing."
    mc "You know you can just take it home after club, right? It's not tied to the school."
    n "Eeehh..I kinda...hrrmmmm..."
    "As I stand up, I notice how Natsuki is getting a bit red. She looks away from me as she mutters under her breath."
    n "I wanted to read it with you the first time..."
    "I look back and see her face and can see the disappointment."
    mc "What was that?"
    n "N-nothing! I just...nevermind."
    "She gets up in a huff and begins to stomp away."
    mc "On second thought, wait for me before reading. It was kinda fun reading it for the first time with someone. Wouldn't want you to spoil it for me."
    "Natsuki perks back up and then tries to disregard my suggestion."
    n "I guess I can hold off on reading it. Just so you don't feel left behind."
    mc "Thanks. Well, let's get going."
    n "Right!"
    "As she places the manga back into her specified spot in the closet, she skips to the front with the rest of us."
    m "Now that we're all here, we can go over the performances. I know I said you didn't have to write anything for today, so-"
    s "Umm, I actually did write something."
    mc "I actually did too."
    n "Same here!"
    y "I, too, was swayed by my muse last night."
    "Monika reacts with an excited shock."
    m "You all are... just amazing! This is why I have so much confidence in you all for this performance. "
    m "So, does anyone want to present first?"
    "We all look at each other. I mean, I've got more confidence in my work, but not THAT much to volunteer first."
    "I'm saved by the excited exclamation of Sayori."
    s "OohOhh! ME! Me!Me!"
    m "*Giggle* Okay, Sayori. The floor is yours."
    "Sayori hops up with her poem in hand and skips to the front."
    s "Okay. My poem is titled 'My Meadow'."
    "As she begins to recite her poem, she stumbles a bit and giggles at her mistakes."
    s "Sorry. More nervous than I thought I'd be. Heehee..."
    m "Don't worry. It's just a dry run with friends. If you're feeling nervous, just pretend you're in a calmer place. Say, in your room or talking to yourself in the mirror."
    "Sayori nods and proceeds to close her eyes and take a deep breath. "
    "After she composes herself, she continues from the beginning of her poem."
    "As she is performing, her tone and demeanor reflect the bittersweet words on her page in such a genuine fashion, that I can't help but be in awe of her immersion. "
    "As she finishes her poem, the room is filled with applause from the four of us. "
    "Sayori takes a curtsey and hops back into her seat."
    m "Good job Sayori. You really brought those words to life."
    s "Aww shucks, Monika..."
    m "Well, who's-"
    y "I will perform now!"
    "Yuri's outburst catches all of us off guard as she rapidly walks to the front of the room."
    m "Uh, okay. Yeah! Glad to see that passion, Yuri!"
    "As Yuri reaches the front of the room, her perceived confidence falters as her nerves kick in. "
    "She begins to perform while her face is buried in her page."
    y "Th-the title of my poem is...Afterimage of..a Crimson...eye..."
    s "Oooh. I love cherry pie!"
    n "I thought she said something about a cursed light."
    mc "No, I think she said prismed eye."
    "Yuri begins to turn red from our misunderstanding as she hides her face in her hair."
    m "I'm sorry, Yuri, can you speak up a bit? I know it's a bit different, but don't worry. We're here to support you."
    "Yuri nods her head rapidly and begins again, this time, a bit louder, but still shaky."
    "As she goes along, her demeanor slowly shifts. She is getting more and more emotionally invested in her work and it is showing in her performance. "
    "The confidence in every emotion is put on full display. At this point, even Natsuki is staring in awe."
    "As she finishes, a silence fills the room as we are still soaking in what we just witnessed. "
    "The silence begins to get to Yuri's nerves as she begins to hide her face behind the page again."
    "Monika is the first to clap with a huge smile on her face. We all shortly follow suit."
    s "Oh my gosh, Yuri! That was amazing!"
    n "Didn't know you had it in you, girl!"
    m "A beautiful expression, Yuri! You really brought life into your words!"
    "As Yuri rushes back to her seat, she can hardly hide the smile curling onto her bright red face."
    m "Alright, who's next?"
    "As Monika says this, her glance lands directly at Natsuki."
    n "Why you lookin at me for? Why do I have to be next?"
    s "I mean, it kinda makes sense. You were the next person to join the club after Yuri."
    n "Don't see why that's a rule for this. Why don't we have the goober go."
    mc "I understand your hesitation. That is quite an act to follow."
    n "W-what? I ain't worried about any of that! It's just...I uhh-"
    "Crap, I didn't mean to put her in this situation. I might as well step up and fix it."
    mc "You know, I don't mind going now. I figured if I give a crappy performance, you can bail me out with your better one."
    "Monika looks at me with a sad smile as she is about to rebut, but is interrupted by Sayori."
    s "Hey! You won't be crappy! As long as you do your best, you'll do fine."
    m "My sentiments exactly. Please, [player]. The floor is yours."
    "As I get up to the front of the room, I can't help but notice Natsuki looking a bit disappointed, while the others look on in anticipation."
    "As my eyes meet with Monika's, it feels like I can see a sort of glimmer in her eyes."
    "My face begins to feel a bit hot, but I can't tell if it's from her stare or the situation. I try to calm my head so I can get through this."
    "I imagine how I felt when listening to Sayori and Yuri. The emotion of every word. "
    "I progress, I feel my voice getting less shaky and rigid. "
    "It's beginning to feel less like reading words on the page and more like describing my thoughts and emotions. "
    "Before I know it, I'm done reading. As I look up, I am greeted with the applause and smiles from them all."
    m "For all that nay saying, you put on quite the performance, [player]."
    s "Told you you'd do fine!"
    y "I agree."
    mc "Uhh, thanks guys."
    m "With practice, it will become easier. I have no doubt you'll do well at the festival."
    "I rub the back of my head as I head back to my chair."
    m "Well, Natsuki. It's your time to shine."
    s "Get on up there and show us what you got!"
    n "Welp, can't let the newbie show me up."
    "Natsuki drags herself up to the front and begins to present."
    n "The name of my poem is Jump..."
    "She begins to recite, she looks up from her page and back at us. She freezes up a bit."
    n "W-Why are you all staring at me?!"
    m "Because you are performing."
    n "Hrmm...Stop it you weirdo!"
    "She singles me out of the crowd."
    mc "W-what did I do? Everyone else is watching too."
    n "You keep looking at my eyes, ya freak. Look somewhere else!"
    mc "Maybe if there was something else to look at-"
    "**SLAP**" #[Smack sound bit]"
    "I'm thrown off by the sudden slap upside the head. As I turn, I see a stern-faced Sayori."
    n "Thank you, Sayori."
    s "Just doin' my job!"
    m "Alright, guys. Enough. We need to take this more seriously. Natsuki, please continue."
    "We all nod and return to giving our attention to Natsuki, who begins to read her poem again. "
    "While it starts with her giving a low effort read, her own words seem to work against her efforts as she begins to lean into the bouncy, upbeat rhythm to her words as it begins to reflect in her performance."
    "As she finishes, we all begin to applaud."
    s "That was so fun! I loved it!"
    y "Quite the enjoyable ride you took us on! Excellent performance, Natsuki."
    n "Yeah, that's what I do..."
    "While she tries to display confidence, her shyness is still taking center stage."
    m "Okay, everyone! That should be it for the performances. How's everyone feeling about it now that you have a bit more experience?"
    s "I'm pumped now! I'm sure if we practice, we should have this in the bag!"
    y "While this exercise did not fully quell my nerves on the situation, I must say it did ameliorate my reluctance."
    mc "Uh...yeah. What she said. I think."
    n "As long as the folks in the audience aren't jerks, we should be alright."
    m "This is great to hear. There are a few other things we will need to get everything ready, but we should be in good shape. "
    m "For tomorrow, I would really want you all to focus on your poems that you will be performing, so don't worry about writing a new one for tomorrow."
    m "I don't expect you to fully memorize them, but getting a hang of your delivery will definitely help with the performances. With that said, we are done for today."
    "Alright. I was able to perform. It wasn't as bad as I thought it would be, but that's probably because it was just them. "
    "As I look over the poem and re-read it, I realize it is quite long. She did say memorizing would work better. "
    "Maybe I should try one of my older ones. The second one seemed to have better feedback, so probably-"
    s "Hey, [player]. You good, buddy?"
    mc "Huh? Oh. Yeah. Just wondering which poem to choose."
    s "What was wrong with this one? I liked it. It was really inspiring!"
    mc "Thanks. That's good to hear, but..it's kinda long to recite. Rather not spend too much time up there."
    s "I can see that. Hmmm..."
    mc "I was kinda thinking my second one-"
    s "Oh yeah! I never got to read it! Monika told me it was good."
    mc "In a nutshell, it's kinda my emotions on joining the club. If you want you can-"
    "I stop myself and look at Sayori. She's been much happier today than yesterday. "
    "Maybe it was the excitement of our performances. It seems like the more we get into this the better she feels."
    mc "Now that I think about it, how about I let you hear it for the first time at the festival?"
    s "Huh? Why?"
    mc "This was one I was really wanting you to experience in the best way possible. I feel like the festival will be a great way to do that."
    "Sayori begins to smile sweetly."
    s "Well that's just one more thing to look forward to for Monday. I can't wait to hear your poem. If it's anything like the one today, I'm sure it'll be great."
    "After finishing packing my things, I head out with Sayori as we head home."
    return
    
    