label act1_day9:
    scene bg black
    "Wednesday"
    scene bg residential_day

    "As I look at my phone, I begin to feel a little anxious."
    "It's already 7:25 and Sayori still isn't out yet. "
    "I've had to have left her at least 3 messages and nothing and her phone keeps going to voicemail."
    "It's ringing, so it's not dead. What the hell? "
    "Time for action. I walk up to the door and give a gentle knock and wait."
    "..."
    "..."
    "Nothing. "
    "I knock a bit louder."
    "..."
    "..."
    "Still nothing."
    "Come on. "
    "Last chance. I begin banging on the door and it flings open."
    mc "Geez, finally! You ready t-"
    sm "You must have lost your mind banging on my door like that! I am trying to work! What is wrong with you!?"
    mc "Ahh..I'm..so sorry. I was just..Sayori was."
    sm "That girl isn't ready yet?! Hell...well, go up there and get her."
    mc "Uhh...you sure? She could be..."
    sm "She still wears clothes to sleep. Well, she was last week. She did have a little bit showing last time I..."
    sm "Screw it, come on."
    scene bg sayori_hallway
    "I follow Sayori's mom to her room. As her mom opens the door. I make sure to stay back a bit to grant her privacy."
    sm "Sayori! GET UP! You're running late! *smack smack smack* *grunt* [player], come give me a hand. Don't worry. No free shows today."
    scene bg sayori_bedroom
    "I walk in avoiding eye contact and slowly look up to see Sayori's mom pulling Sayori by the leg to get her out the bed."
    sm "Geez! Now I know where the food goes. "
    sm "She must show her weight in her sleep or something. You grab her other leg. I don't wanna give her brain damage, so we're gonna drop her on her ass."
    "As we both pull her legs, I can see what she's talking about. The hell? I could have sworn she wasn't this heavy Sunday. "
    "What, did she eat a cannonball?"
    sm "Stop being gentle with her or she won't wake up! "
    "As I reluctantly agree, I pull Sayori and she flies on the bed on her butt."
    s "BWAAAHH AHHH WHATS GOIN ON!!!"
    mc "You're gonna make us late?"
    s "[player]?! What are you doing?!"
    sm "Trying to watch your ass. Get up, get dressed, get to school. "
    "As Sayori's mom walks out of the room, she pats my shoulder."
    "Sayori Mom: You should probably leave for the dressed part."
    "My eyes widen as me and Sayori's eyes meet. We both turn red."
    s "G-Get out so I can change, perv!"
    "[player]; I'm going! And I'm not a perv!"
    scene bg house
    "I sit there impatiently waiting for Sayori to hurry up looking at the time on my phone. "
    "It's 7:48 when she rushes out the door"
    mc "Come on! We're gonna have to jog so as not to be late."
    s "Can't we just speed walk?"
    mc "I'm not leaving you behind, so no. Jog!"
    s "But I'm tired..."
    "I grab her hand and begin halfway dragging her."
    mc "Stop being a bum and speed it up!we don't have time to be lazy! Let's go go go!"
    scene bg class_day
    "The bell rings as soon as I sprint into the room. "
    "Mr. Agawa is already standing at the front of the class while everyone else is sitting down."
    a "Cutting rather close, [player]."
    mc "Sorry. I had a...long night."
    a "Writing that roadmap, I hope?"
    "Oh crap! With all the stuff going on with the club I completely forgot about it."
    mc "Mmmhmm..."
    "My high pitched response probably did nothing to help with this situation."
    a "Oh? Well, if you're finished with it, I can take it righ-"
    mc "Nnn-I still got a bit to go! You know, uh. Fine. Details. And such."
    a "Fine details, eh?"
    "We stare at each other for a bit. My nerves are so racked that in the first to break eye contact to look towards my desk as a slink away to it."
    mc "I've been enough of a bother so I'll just move along here. Don't wanna interrupt this great learning, am I right everyone? Eh heh..."
    "I cringe out of embarrassment in my seat as I try to live down this moment. "
    "Crap crap crap! Dammit Sayori! I thought you woke up late yesterday."
    "If her mom wasn't there, I doubt I would have been able to wake her up myself. That girl slept like a rock. That's..."
    "That's kinda worrying."
    "Is she staying up late or something? What could she be doing? "
    "Wait. It probably had to do something with worrying about Yuri and Natsuki. "
    "Not to mention she's obviously trying to hide something about the festival."
    "I mean, she was a bit dismissive earlier. Then again, me calling her a lazy bum and berating her most of the way here didn't help."
    "*Sigh* I really should apologize. "
    "With all she's done for me, she deserves more grace than that."
    scene bg school_hall_2
    "With all that went on yesterday and this morning, I completely spaced it on making lunch today. "
    "At least I have enough to get something from the cafeteria. "
    "As I head to the vending machines to get a drink, I turn the corner and see Natsuki standing in front of them counting the change in her hand."
    n "Crap. I'm just short-"
    mc "Finally figured it out, huh?"
    "Natsuki jumps from being startled, dropping some of her change."
    n "Dammit! Why the hell'd you do that!"
    mc "S-sorry."
    n "Crap! Some of them are under the machine. Dammit..."
    "As she is about to get on her knees to search for them, I stop her by placing my hand on her."
    mc "Let me get it. It was my fault."
    "Natsuki looks down at the floor while clenching her fist. She then flings my hand off her and turns around to walk away."
    n "Screw it! Wasn't enough anyway."
    mc "Natsuki, wait!"
    "She stops and looks back at me."
    n "What!?"
    mc "What were you planning to get? It's on me."
    n "I'm not some sort of charity case!"
    mc "I know you're not. You're my friend."
    n "Huh?"
    mc "Do you know how much I've spent on snacks for Sayori alone? The shop keeper once said I was putting their kids through college once."
    n "Pfft. Yeah, that girl is a black hole for snacks...well, if you insist that this is only a friend thing and ain't pity."
    "I hand her the money for her to make her choices as I begin to try and reach the change she dropped under the machine"
    "???: What's this? Little miss short change has paper money? Who'd you steal that from?"
    "As I look up, I see a tall, lanky guy approaching us."
    n "*Sigh* just leave me alone Kenji."
    "I stand up after getting the rest of the change to turn around and face him. As he notices me he begins to put on a smug grin."
    "Kenji: Oh, I see how it is. Feeling more bold now that your boyfriend is here? Didn't know you were into pathetic looking guys."
    mc "Dude. Just leave her alone. Now."
    "Kenji: Looks like we got a jealous type here. You really dating this guy?"
    "Natsuki/[player]: We are not dating!!"
    "Kenji is shocked by the synchronized outburst, but quickly returns to his smug self as he begins to approach Natsuki."
    "Kenji: We in that case why don't we-"
    "I place my hand out and stop him in his place as I take a step in front of Natsuki."
    mc "She obviously doesn't want to talk to you, so move on. If you need the machines, we were leaving anyway."
    "He slaps my hand away from his chest."
    "Kenji: If you're not tapping that, then mind your business. Besides, she's too cute for your punk ass anyway."
    "I can feel the rage radiating from Natsuki. Hearing a word that many find a compliment being used by this scumbag, no wonder she hates the word. "
    "Kenji tries to walk around me to talk to Natsuki."
    "Kenji: So how bout it cutie?"
    n "HOW BOUT-"
    "I spread my arm in front of her blocking her from approaching him."
    mc "No! I may not be her boyfriend, but I am her friend. So this IS my business."
    "Kenji begins to look me in the eyes to try and intimidate me, but I stare right back holding my ground. He then laughs to himself."
    "Kenji: You really think you can stand in my way?"
    mc "Haven't had a problem so far."
    "As we stare each other down, I can see him balling his fist in the corner of my eye. As he begins to move his body to throw a punch, I quickly shove him. "
    "As he is backing up, he runs into a teacher who was walking past."
    "Teacher: What the hell? What were you...  "
    "Kenji: Sorry, ma'am. We were just horsing around a bit and I guess we took it too far."
    "The teacher looks at me and Natsuki. I can tell from their face that they don't believe him."
    "Teacher: Is this true you two?"
    "I look towards Natsuki and then back to the teacher."
    mc "Actually-"
    n "Yes! Sorry. We were just playing around and got carried away."
    "The teacher looks at me with a questioning glare."
    mc "Y-yeah. Sorry about that. We'll be more careful."
    "The teacher looks at all of us suspiciously."
    "Teacher: O...Kay. You kids should get moving and stop playing in the halls."
    "Kenji: Yes ma'am. Thanks for understanding."
    "The teacher walks off and turns the corner. Kenji then begins to walk away in the other direction before looking back to address us once more."
    "Kenji: You better watch your back, boyfriend."
    mc "Sure. Whatever."
    "As I take a sigh of relief, I'm interrupted by a fury of small fists to my arm."
    n "What the hell was that, you doofus! Now he's gonna be gunning for you!"
    mc "Hey. If it takes the heat off you, I can handle it. "
    mc "Besides, you're my friend. And that's what friends do, right?"
    "Natsuki's frown slowly turns into a comforting smile."
    n "Right. Thanks. I guess...because of yesterday...n-never mind."
    mc "If you need to talk-"
    n "No I- uh...not now, okay?"
    mc "Completely understand. I'm here when you need it. I'm heading to the cafeteria, did you already eat?"
    n "...this will be enough."
    "I look at what she got from the machine and it's a bag of chips and a snack cake."
    mc "If you're embarrassed you forgot your lunch and are short on money, you don't have to feel embarrassed. I forgot mine today too. I can spot you."
    "Natsuki looks as if she's pondering the request before shaking her head."
    n "Nah. I was just getting a quick snack anyway. I got some homework to catch up on."
    "She then looks at her phone and notices the time."
    n "Speaking of which, I better get going. See you in club!"
    mc "Yeah, see ya!"
    "As she scurries off I get my drink and head to the cafeteria."
    scene bg club_day
    "As I walk into the clubroom I notice for the first time, I see an empty teacher's desk. "
    "I look around the room and see Natsuki and Yuri in their normal spots, while Sayori is sitting near the window staring at an eraser as she slowly rolls it on the desk."
    "As I walk up to her, she seems completely spaced out. I finally get to see how the other side of that looks."
    mc "Hey Sayori. You still with us?"
    "Sayori continues focusing on the eraser as if I don't exist."
    mc "Hey, if you're upset about this morning, I'm sorry. I didn't really mean to be so harsh on you I just..."
    "As I look, her demeanor still has no change. Is she that deep in thought? I put my hand on her shoulder and gently shake her."
    mc "Hello? Are you ignoring me on purpose?"
    "The jostle startles her out of her daze and she realizes that I'm next to her."
    s "Huh! Oh. Sorry. Didn't notice you there."
    "She tries to smile, but it's obviously forced."
    mc "Are you okay? You were more spaced out than me."
    s "Oh, don't worry about me. I'm fine. Just...tired..."
    mc "About that. Sorry again. I forgot your mom can be a little rough."
    s "No worries. I probably would have slept till noon otherwise. Didn't really sleep well last night."
    mc "Hey, if this is about yesterday-"
    "Sayori No, it's just...*sigh*...I need to be alone right now."
    "Sayori proceeds to lay her head on the table and in her arms. Poor girl must have been up all night worrying about the others. I guess I can give her a bit of space to gather her thoughts."
    "As I walk over to the front of the door for any sign of Monika, I almost run into Yuri who has just gotten out of her seat. The near collision gives her a slight panic."
    y "Oh, I'm so sorry! I-"
    mc "It's no problem. I'm not in any hurry. Hey, do you by chance know where Monika is?"
    y "Oh! Umm...She does have an eclectic extra curricular experience. Perhaps another club approached her for assistance."
    mc "Knowing Monika, she's not one to deny someone in need. Especially when they ask her."
    y "Indubitably. If you do not mind, I must...uhh..Attend a personal matter."
    "I look at her with a bit of a confused look until I realize she is going to the restroom."
    mc "Ah! My bad. Don't let me stop you."
    "As Yuri bows to me in gratitude, she swiftly walks out the door."
    "I walk past her desk and notice that she's still reading the same book. "
    "Huh. With her speed, I would have thought she finished it last week and would be on another one. I pick it up and reread the synopsis."
    "Yup. Still surprised that she likes this type of stuff. Maybe my outlook on it is wrong. It may be like her poem and be a metaphor for something."
    "As I pick up the book and read where she left off, I hear footsteps approaching me. I look up and Yuri looks at me curiously."
    mc "Oh! Sorry. I didn't mean to be nosy. I was just a bit interested."
    y "No need to apologize. I am happy that you are finding an interest in my taste in literature. "
    y "I take it that Monika was able to relay my recommendations to you?"
    mc "Yeah. It was quite a haul you had there."
    y "I hope the extent of my recommendations did not overwhelm you."
    mc "I mean, a little, but it was mainly knowing that you've read THAT much.  Unless you have a long list of everything you read."
    y "Nnno...those were the works that I was able to compile at the moment."
    "All that off the top of her head!?"
    mc "And here I thought you couldn't get more impressive!"
    "Yuri begins to blush."
    y "T-thank you for your praise. Glad to be of assistance."
    mc "Just wondering, this is the same book you were reading last week right?"
    y "It is. I was not aware that you would notice. If you are interested, I can let you borrow it."
    mc "I...don't think I would do too good with it. I mean, if it's taking you this long to get through it, it must be a tough read."
    "Yuri looks at me inquisitively and then it clicks for her."
    y "I understand now. On the contrary. The book is quite an easy read. I have just been re-reading it as I find this book mentally appealing when reading."
    mc "Kinda like a rerun of your favorite anime."
    y "Exactly!"
    mc "So what makes this book so appealing to you?"
    "Yuri stops for a bit and closes her eyes. She has been at it for a minute."
    mc "It's okay if you can't put your finger on the reason."
    y "No. It is not that. I am trying to compile my explanation so as to not present an overwhelming amount of detail."
    mc "I mean, if you want I can find a copy and read it myself. That way you can talk about it with no filter."
    y "Y-you would want to discuss Portrait with me?"
    mc "Why not? This is literature club after all."
    "Yuri's eyes brighten up and she begins grinning larger than I have ever seen on her face so far."
    y "That is an extremely welcomed offer! As a matter of fact, you can borrow my copy. This will expedite your exposure!"
    "As she holds out the book to me with great delight, I cautiously take it from her hands."
    mc "Are you sure? I mean, you were just reading it."
    y "Never you worry! I can indulge in other novels as well. While it is my favorite, it is not the only book I have on hand."
    mc "Oh. Well, thanks! I did just recently finish the manga Natsuki lent me. So this takes care of my next read."
    y "If you do not mind, I would like to discuss the book during your reading periodically, if that is okay with you. "
    y "It is not because I feel that you will not be able to understand it, it is just that since this is your inaugural exposure to this story, I would like to provide a bit of context here and there and also get your feedback."
    mc "Uh...yeah. Sure, we can talk during club some time. I'm just gonna put this up for now and get my poem ready."
    y "Certainly!"
    "As I walk over to place the book in my bag and grab my poem, I think about Yuri's reaction. "
    "This IS a literature club after all. She acts like...well, now that I think about it, I doubt Sayori or Natsuki would like this type of story. Monika might, but seeing how busy she always is-"
    "As I think of Monika, almost like a psychic manifestation she bolts through the door with great speed."
    "Monkia: I am sooo sorry you guys. I got held up by the student council."
    n "What happened, they asked you to be president or somthin?"
    m "No..*but at this point they probably should* I was just wrangled in helping some of the first year members with clerical stuff. "
    m "Since the festival is next week, many of the senior members are caught up in that. You know, their last one before graduation."
    m "Anyway, we should probably get started on sharing poems. I hope everyone is ready!~"
    "As I look around the room, I see Yuri still quite excited approaching Monika. Sayori hasn't moved yet. "
    "Is she really okay?"
    "Eh...I should probably give her some space. She's quite an open book when it comes to me, so I shouldn't think too hard about it. "
    "Natsuki it is. "
    "As I approach her, she has a bit of a chipper attitude."
    n "So, are you looking to get some notes before embarrassing yourself with the others?"
    mc "Nah, They say save the best for last."
    "Natsuki's grin turns into a piercing scowl."
    mc "Guess I'm just a contrarian."
    "That remark lands a smirk on Natsuki's face."
    n "Nice save there. Your shins should thank you."
    mc "Gotta keep you on your toes or you won't measure up."
    "*KICK*"#[Kick sound bit or something like that here]"
    "I grab my shin in pain as I silently scream to myself."
    n "Should have quit while you were ahead."
    mc "What did I even sa-"
    n "The friggin short jokes!"
    mc "What short jo- ...Ohhhh!"
    n "Can't believe the only thing smart about you is your damn mouth."
    mc "Yeah yeah. So, how have you been holding up? I know a couple of things are on your mind probably."
    "Natsuki side eyes me before warming up a bit."
    n "Y...yeah. Its still kinda."
    mc "Awkward with you and Yuri."
    "She nods her head slowly."
    n "I mean, we said hi to each other, but...I don't know. I mean sure, we didn't talk much before, but it just felt like we didn't need to say something. "
    n "Now it feels like we're avoiding each other."
    mc "Yeah. I can see that. It can feel a bit forced if there's no reason. But, there is now."
    "I point to Natsuki's poem in her hand and my poem in mine."
    mc "Maybe try to make amends while sharing."
    n "Hmmm..I know I should...fine. I'll admit I was a bit mean yesterday. I guess it's on me to be the bigger person."
    "*KICK*"#[Kick sound again here]"
    mc "AHH! *Clasp*"
    "I turn around and see Yuri and Monika looking towards me to investigate the commotion."
    "I just wave at them and they both reluctantly wave back."
    mc "What was that for!?"
    n "Preemptive strike."
    "[player]; Huh? Whatever...fine. Can we just trade poems before I'm left needing a wheelchair?"
    "Natsuki hands me her poem with a devilish grin while I rub my poor shin."
    "As I read her poem, it carries her signature bouncy cadence. "
    "From the message, I can tell that she took what happened yesterday to heart and reflected it into this poem."
    "As I hand it back to her, I smile at her."
    mc "I really liked it. Good message, fun read, and I'm certain Yuri will love it."
    "Natsuki becomes red and flustered."
    n "I-I didn't write it for Yuri! I just...wrote what I was thinkin is all."
    mc "Sure you were...."
    "Natsuki glares as she winds her leg back as if she's playing kickball. I jump back a bit."
    mc "I got it, I got it! Sheesh!"
    "I hand her back her poem while keeping a good distance from her."
    mc "You gonna holster that thing and read mine now?"
    "Natsuki sets her foot back down as I walk closer to hand her my poem. "
    "As she reads it, her face slowly grows concerned, similar to yesterday."
    n "Well, it's an improvement from yesterday. At least it's less clunky and the ending isn't as much of a downer."
    mc "Uh..thank you?"
    "She hands me back my poem as she stares at the floor."
    n "You..uh..okay?"
    mc "I think you might have left a bruise."
    n "I meant your poems! They're kinda, depressing. I don't mean to pry but-"
    mc "It's okay. You're not wrong. "
    mc "Last week, I was in a dark place. I guess this was a way to kinda work through those feelings."
    n "Did something happen?"
    mc "Sigh...i broke up with my girlfriend two weeks ago"
    n "O-oh...."
    "..."
    "..."
    "Wow, this is awkward."
    n "So...I take it she was important."
    mc "I mean, she was kinda the only social connection or guidance I had. Heh, I was quite the loser, huh."
    n "I WANT to say yes, but it...doesn't feel right to."
    mc "Thanks. But, I was. No direction, no initiative. Honestly, if it wasn't for Sayori, I'd probably be a drop out right now."
    n "Well, I'm glad you had her. From what I've seen, you're completely different."
    mc "I'm glad that I can no longer be seen as scum in your eyes."
    n "I never saw you as scum. Just a selfish wuss."
    mc "Don't know if that bett-"
    n "Take the compliment, dummy. Besides, without you, who else can I talk about manga with?"
    mc "I mean, maybe Sayori..."
    n "But you take it seriously as a form of literature.  I don't have to feel like you're looking down on me for reading it."
    "I just back out of her leg range. She stands there with a confused look and then squints her eyes at me."
    mc "P-preemptive evasion?"
    "It soon feels like she is looking past me. As I turn around, I see Natsuki is looking over in Yuri's direction with a sad look on her face."
    mc "Tell you what, I can read with Yuri next if you want. I can give you a sign for how she's feeling about yesterday if you're worried about it."
    n "You don't have to be so nosey about it. I can handle it myself."
    mc "Okay, I gues-"
    n "But!"
    mc "Huh?"
    n "I mean, if you're that set on having her read your poem, I won't get in your way. I can check on Sayori while we share, seeing you probably pissed her off."
    "I open my mouth to rebut, but realize this may be the better route."
    mc "Yeah. Thanks."
    n "No problem! It's what friends are for."
    "As Natsuki approaches Sayori, I turn to Monika and Yuri, who seem to be separating at the moment as Monika's phone seems to be going off. "
    "As she looks at it, she begins to face palm and looks up at me looking both annoyed and disappointed."
    m "Looks like I have to sit out this round. Excuse me."
    "As she walks out the door, I stand next to Yuri."
    y "Well, [player], I am quite intrigued to see what you composed. Were you able to find any inspiration from the references Monika relayed?"
    mc "Actually, yeah. That caged bird sings one kinda spoke to me. I liked their style and tried my best to mirror it with my own outlook."
    y "That is fantastic! You have chosen a great work for inspiration. I would love to see if I can interpret that reference from your work."
    "As I hand Yuri my poem, she does nearly the same thing as last time. I can see her eyes going back and forth, top to bottom. Her demeanor begins to show her worry."
    y "[player], if you do not mind I-"
    mc "-know what youre gonna ask. I am okay and these were my reflections from last week."
    mc "I had a break-up with my girlfriend."
    y "I am sorry to hear of your loss. It does bring a lot of revelation to your poems. I take it from this poem that you have found a new outlet that alleviates the pain."
    "Yuri steps closer to me and begins to whisper to me."
    y "Might I ask if Sayori is your sunshine?"
    mc "Well, yeah! Actually, it's kind of all of you here and the club as a whole."
    
    y "I am glad that we were able to provide you with some levity in your trying times. "
    y "You seem to be quite adaptable as your work has improved since yesterday. I can see the slight influence of Maya Angelou, even though it is a slightly superficial adoption."
    mc "Uh thanks, I think? To be honest, I have no clue on what I'm doing. "
    y "Well then you have excellent instincts. You seemed to have taken everyone's criticisms to heart from this attempt. "
    mc "I'll take your word for it. You're the expert."
    "Yuri begins to get a bit flustered."
    y "Uh- I wouldn't call myself an expert, more...experienced in the subject. "
    y "But do not worry. We all have that sense of imposter syndrome from time to time. Especially blossoming poets. It just takes experience to provide a more fluid production. "
    mc "That's what she said!"
    y "Hmm? who?"
    mc "Oh..uh. Nevermind. Thanks for the feedback, Yuri. I get a bit more confidence each day with you guys."
    y "Oh! Uh...g-glad to be of assistance."
    mc "Anyways, mind if I read your poem now?"
    y "Of course!"
    "Huh. It still has the metaphors that Yuri has shown yesterday, but this one reads easier. While it has a story, I can't seem to figure out the meaning. Maybe feeding into some sort of habit?"
    "I look up to Yuri and she seems to be focused more on Sayori and Natsuki at the moment. I look over as well and it looks like Sayori is still down."
    "Natsuki seems to be going quite easy on her, but concern can be seen on her face."
    y "Hmm..."
    mc "Yuri?"
    
    y "Huh? Oh. My apologies. My attention was a bit preoccupied."
    mc "She can be quite understanding and gentle at times, can't she? Especially when it comes to her friends."
    "Yuri looks back at me and then down again."
    y "So you believe that she will forgive me for the insults? "
    mc "I don't believe she will. I KNOW she will. If anything, she is probably hoping you can forgive her. I honestly think this poem may help as well. "
    mc "I noticed the use of an animal for the metaphor."
    mc "Did Natsuki's poem play any part in that?"
    y "A...bit. The prospect of incorporating an animal for the personification of my interpretation was birthed for reconsidering the meaning of her poem. "
    mc "Well, be sure to let her know that. I'm sure she will be glad to hear she influenced you. "
    mc "And I think you two may be able to find some relatability with your poems today. "
    "Yuri slowly exhales in relief and begins to smile again."
    y "Thank you for your vote of confidence. I believe I will approach her next so the tension is finally dispelled. Thank you for your support in the matter."
    mc "Hey. Just returning the favor."
    "Yuri turns around to Natsuki with a bit of a pep in her step, but slows down a bit as she gets closer. "
    "Natsuki is patting Sayori's back before she turns around jumping a bit at the sight of Yuri. "
    "I can barely hear what they are saying, but they begin to talk as they walk away after Sayori says something to them and it looks like everything should be working out between those two."
    "I guess now would be the time for me to talk to Sayori to fix our-"
    m "Okay! I'm back. Is everyone okay?"
    "As Monika looks around the room, she notices Sayori sitting by herself still, with the same defeated demeanor as before."

    mc "I was actually gonna try and share with Sayori next since she's free."

    "Monika then places her hand on my shoulder to keep me from proceeding."
    m "Actually, you can sit this round out. I'll go share with her now. Besides, it wouldn't be fair since I already sat one out."
    mc "Yeah, I guess so. It's just...have you noticed anything off about Sayori lately."
    "Monika takes a look and begins to look a bit somber."
    mc "She's been kinda like this all day. I think it's my fault for kinda forcing her awake this morning, but I can't tell if she's just tired or actually upset with me."
    m "It's sweet to know you care so much for her like this."
    mc "Well, yeah. She's been there for me so much, I would be a crappy human not to return the favor."
    m "Tell you what. I can check with her to make sure everything's okay. It may just be a girl thing and that can be...kinda awkward to talk to with you."
    mc "...Ahh. That,..does make more sense."
    m "Besides, she's my friend too. I would hate to see her suffer if I can help it. I'll let you know what I find out."
    mc "Thanks, Monika! You're the best!"
    "Monika begins to blush a little."
    m "Oh.. well, well I'm just doing my duty as club president. I have to make sure all my members are safe and happy!"
    "She pats my shoulder before turning around to Sayori."
    
    "-Monika POV-"
    "As I turn around to face Sayori, the only thing running through my head is the hope that my suspicions are wrong. "
    "Unfortunately, they rarely are."
    "As I approach the desk, I can see the glassy eyed stare Sayori is giving to the window. "
    "Oh, boy. This seems like a bad one. I try to crouch down to her and talk to her with the most gentle tone I can muster. "
    m "Hey, Sayori. Is everything okay? Me and [player] noticed you were looking down today and were a bit concerned."
    "Sayori slowly turns her head to acknowledge me, but then turns face down and places her head on the table, struggling to keep her composure."
    s "Don't worry. I'm just tired. I'm...fine."
    "I reach for her hand and clasp it in mine. It looks like it's hitting her hard today. "
    m "Is it the rain clouds again?"
    "Sayori slowly nods while trying to hold back the tears from rolling. She tries to respond further while trying to keep everything in and as quiet as she can."
    s "Please..don't...tell...him."
    "I scoot closer to her and place my arm around her shoulders."
    m "I would never betray your trust like that, but I think he should know. He seems very worried."
    s "That's why he can't know. He's already dealing with enough. He doesn't need my stupid feelings to bog him down."
    m "It looks like he's gonna worry regardless. He's not as inattentive as before. He doesn't have a distraction like-"
    "No. Stop. Bringing her up will only make this worse."
    m "I understand. You want to make sure you're ready. But, please. Open up to him. Not just for yourself, but for him as well. "
    m "Will you at least think about it?"
    "Sayori shrugs before turning her head to face me with her red, puffy eyes."
    s "I'm sorry I ruined the mood today.  I can't believe I made myself even more useless. "
    s "I'm a horrible vice president."
    m "You are NOT a horrible vice president. I have never regretted that decision. "
    
    s "I didn't help yesterday, I made everyone worry today, what else am I to think?"
    m "You're just having a few off days. I don't blame you for yesterday or today. "
    m "Heck, something just might be in the air because Natsuki and Yuri look like they made up already. "
    m "Besides, all the work you've been doing over the last couple weeks for the festival surprise? That was a big help."
    s "I...just...hrmmm..."
    m "Look, we're already halfway through the meeting. You should head home to get some rest."
    s "But what if-"
    m "I will just tell him it was your time of the month. Yuri and Natsuki wouldn't have any problem either vouching or making [player] uncomfortable enough not to even ask further."
    s "Are you sure?"
    m "Only if you promise to text me when you get home so I know you're safe. And if you need to talk or text further, I'm happy to be there for you."
    "Sayori sadly smiles at me."
    s "Thank you, Monika. I...will...text you later."
    "As Sayori packs up, I think deeply on Sayori's depression, wishing I can do more to help, but I'm not a professional at this. "
    "The only thing I can do is be there for her."
    "If only Sayori took my advice in looking for a doctor for her condition. "
    "I understand the apprehension and the fear of medications, but it's always a trial and error process. "
    "As I return to my desk, I look in [player]'s direction. Would he be able to do anything better than I can for Sayori? "
    "He seems sweet and kind enough and is obviously just as worried. He may have his own battles, but he seems to understand those feelings she may be going through better."
    "Plus, he's much closer to her than I am."
    
    "Wait, why do I keep thinking about him so much? "
    "He's...not there. He's not looking for someone. "
    "He's healing. "
    "Plus, I can't. With their breakup being this soon, I can't imagine what those gossip harpies are gonna fling around. "
    "Knowing them, they'll probably blame their breakup on me. "
    "Wait. Was it me? I know Elsea was very standoffish when it came to me because of him. "
    "Yeah, she was like that with everyone, but it felt she was a bit more targeted towards me. Maybe somehow she knew I-"
    mc "Earth to Monika!"
    m "Huh?"
    mc "Welcome back, fellow space cadet! I saw Sayori heading out. Is she okay? Should I go and walk her home?"
    "Oh my God. Why is he so sweet? How can I not want to-"
    "Not! "
    "Appropriate! "
    "Monika!"
    m "Oh. Uh..yeah. About that. She's having a rough...time of the month."
    "I can see the gears turning in his head as he finally understands."
    mc "So it was THAT. I wish there was something I could do for her."
    m "Yeah. She's got some medicine to help ease the pain, but it's at home. I just told her to head home and feel better."
    m "In that state, your presence alone may make it worse, unfortunately. But it is sweet that you're willing to help."
    mc "Well, as long as you're sure she'll be okay."
    m "Positive."
    
    "Positivity lying out my ass."
    m "Well, let's get back on track, I think Yuri and Natsuki are finishing up and we haven't even started."
    mc "Oh! Right. Uh..here."
    "As I reach to grab his poem, I can't help but focus on the brief moment our hands touch."
    "Just ignore it, Monika. "
    mc "Disclaimer: that was about last week. I'm better now."
    "I softly as I read through it."
    "His style has greatly improved. It's good to see that he's coming out of his shell. "
    "But I can't help but feel concerned. He was dealing with this all last week? But the ending."
    "The sunshine, is it..."
    "It has to be...Sayori."
    "As I look up to him, he seems a bit distracted looking out the window. "
    "As I turn to check his line of sight, I can see her walking home."
    "Was this poem a sort of...confession? "
    "I can't just out right ask, but... hmmm..."
    m "Wow, [player]! Talk about an improvement!"
    mc "Huh? Oh. Uh. Thanks. I was much happier about this poem than the others. A bit bummed Sayori didn't get a chance to read it, though."
    "Okay, Monika, let's start prying."
    m "I take it you found something or...someone to be an outlet?"
    mc "Now that I think about it, this club has helped me come to terms with my emotions."
    "The club, huh? Maybe I'm overthinking things and he doesn't have THOSE feelings for Sayori? "
    "But I wouldn't be surprised if this poem sparked something..."
    
    mc "So, any other notes? Any improvements?"
    m "Well, poetry is subjective, so I can't really say anything outside of staying true to yourself and keeping your muse close. "
    m "From what you have here, you must have quite the muse."
    mc "I think it was the poems Yuri shared with me."
    "What? Yuri?"
    m "Well, glad to see you're getting inspiration from all of us."
    mc "Yeah. I guess your work earlier kinda inspired me too because I remember your poem about being in a similar position of not showing weakness and stuff."
    "Me as well, huh. Sayori, Yuri, not to mention how close he's gotten to Natsuki...it's all just friendship."
    "I sigh internally."
    "This is good. We are all proving to be his friends here. "
    "Nothing more."
    "Friends."
    m "Yeah, It's still a subject I tend to avoid due to the discomfort, but I'm glad to see that you're comfortable enough to share such deep feelings with us. "
    m "It reinforces my idea that the trust I put in my friends will help me through any hardships. And I must admit, I'm starting to consider you as a friend, [player]."
    "As I reach out to hand him his poem, I try to position my hands to graze his again. "
    "My efforts were in vain as he effortlessly avoided my hands."
    "Sigh...maybe next time"
    
    "--mc pov--"
    
    "As I grab my poem back from Monika, I can't help but feel a sense of relief."
    
    mc "I feel the same way. You've done a good job of making not only me, but the others feel welcome. Even those two have lightened up and got more comfortable."
    "We both look at Natsuki and Yuri as they are in deep discussion over each other's poem with a smile on each of their faces."
    mc "Well, I don't want to take up all the time. Do you mind if I read your poem now?"
    m "Oh, of course! Here you go."
    "As I read I can't help but notice the obvious: the spacing. "
    "It's very much on purpose and I can tell it's for some sort of effect. Huh. I never thought of that as a possibility."
    "But the meaning is kinda confusing. It sounds like some sort of computer program or something, but...think. Metaphors. Hmmm...."
    m "So? What are your thoughts?"
    mc "To be honest, you're shooting sky high over me with this one. I think I may know but..."
    m "It's okay. There's no wrong answers."
    mc "Okay. Uhh...I'm getting the idea of being stuck doing things you don't quite understand and sort of running on autopilot in the confusion. "
    mc "The last line and the title make me think of a computer file, so probably...a file others are writing to without the file's say so."
    "Monika looks at me with her jaw slightly dropped and a surprised demeanor."
    mc "Umm...that or its about some kind of A.I. gaining sentience, but...yeah."
    m "That..was actually quite close for what I was going for."
    mc "Really? I didn't take you much for the science fiction type."
    m "*giggle* No, silly. The first explanation. I'm just shocked you got so close to the mark so fast."
    mc "Well, you all have taught me to look a bit deeper. Guess you all are starting to rub off on me."
    "Monika's face turns red in surprise as she begins to fluster. What did I say that would cause her to..."
    "My face begins to get red quickly."

    mc "I MEAN I'M LEARNING A LOT FROM YOU ALL IS ALL...Sorry if I uh..."
    m "Ha ha ha! [player], it's okay. It just caught me, off guard is all. We're glad Natsuki wasn't in earshot for that one."
    mc "Yeah, my shins can't take any more abuse."
    m "To get back on track, yes. That was the general premise of my story. "
    m "I actually got the idea while working on a project last night thinking about how a file can be created to do a specific thing and that thing only. "
    m "If it doesn't behave correctly, it's usually deleted. Makes me think, what if the file was just trying something new. Why is that so bad?"
    "I nod in agreement as the depth of this conversation is beginning to give me a headache. "
    "Luckily, my brain is saved by Monika's phone going off in her pocket."
    m "Oh, looks like Sayori is home safe. Good. She also reminded me of the announcement I have to make now."
    m "Okay, everyone! I have a quick announcement to make before we leave."
    "Yuri and Natsuki walk over to us to join the group. The fact that I don't see a frown and didn't hear any yelling tells me they must have made up. Good."
    m "So, with the festival being in a few days, we did get the go ahead that we will be able to hold an event for our club since it is now official."
    n "What would be the point of that?"
    m "Well, the festival is a good opportunity to advertise our club to others in hopes of getting new members."
    n "Why do we need new members? We can barely keep this chucklemutts in line and he was just a warm body to make us official."
    mc "I love you too, Natsuki."
    "Natsuki just rolls her eyes at me while Monika attempts to ignore my retort."
    m "Well, gaining more members is important for the club's longevity. "
    m "If we can get a few underclassmen, then the club can keep going after we graduate. It can be seen as a legacy we leave this school."
    
    n "I doubt it will work. I don't think anyone actually cares about literature. "
    n "We'll probably end up with a bunch of slackers or jerks trying to pad out their resumes."
    y "I concur with Natsuki's hesitancy. Improper members can negatively affect the dynamic of the atmosphere we have."
    n "Plus I don't wanna show out for people who won't even take me seriously. I'm not gonna make a fool of myself just so one person can read a flyer once."
    m "I understand you guys. I know not many people share this interest."
    m "But shouldn't that be why we put ourselves out there? "
    m "So we can find the few that do? Natsuki, wouldn't you want to find someone else just as passionate about manga as you?"
    n "K..kinda"
    m "And Yuri, wouldn't you want to see if there is anyone with novel recommendations from writers you've never heard of?"
    y "There are only so many hours in a day to research on adequate material..."
    m "And [player], don't you want to no longer be the new one?"
    "All the girls giggle at my expense."
    mc "I mean, a low bar is still a bar."
    m "And I want to find people who need a safe space to enjoy their hobbies. No better way than to let them know at the festival so they can get a sneak peek."
    n "When you put it that way...fine. So what are our options? Got any ideas already or are we brainstorming?"
    m "Well, me and Sayori have been discussing the subject for a bit, and seeing how good your poems have been the last 2 days, we decided the best way to represent the club is to do a poetry performance."
    
    "..."
    "..."
    "Natsuki's and Yuri's faces are filled with dread."
    n "Pass. What's the other ideas?"
    m "Huh? Well, we don't really have any others at the moment. To be fair, there's not much we can do to promote literature as individuals."
    y "While I am not opposed to providing my poetry for others to read over, performing them in public seems too..."
    n "I ain't puttin myself out there like that!"
    y "Y-yes. That sentiment exactly."
    m "Come on, guys. Give it a chance. "
    m "Look how much we've grown as writers after just two days. This can be a great growth opportunity not only for the club, but ourselves as individuals."
    "Natsuki and Yuri look at each other and then at me."
    n "Maybe...how long till we have to decide?"
    m "Well the deadline to submit was this morning, so..the end of the meeting."
    "Yuri/Natsuki: WHAT???"
    y "How can you make that decision without-"
    n "We don't get any sort of heads up?"
    m "Look, it was an executive decision. Me and Sayori have been going over this even before [player] joined. "
    m "While it was just back and forth talks for a while, we kept falling on poetry as the best event for our club."
    n "I thought this was a group club where we all take a vote. Not Monika's puppet army!"
    y "This...is really unbecoming of someone who regards themselves as a fair leader."
    "Monika is taken aback by their remarks."
    m "I just...we need to move forward or else we stay stagnant and..."
    "I can't take this anymore."
    
    mc "Come on you guys. Let's just give it a shot. I don't think Monika is being controlling. I feel like she's just helping us out of our bubble so we can all grow."
    "All the girls look at me with surprise."
    mc "I mean, come on. If a dummy like me can go from struggling to even think about writing to being interested in different novels and poetry, just think of what we can bring out in others. "
    mc "None of this would have been possible without Monika sharing her poetry with us. If we can inspire just one more person, even if they don't even join, wouldn't that be worth it? "
    mc "Isn't that the point of the club itself?"
    "Monika looks at me softly smiling with a sign of relief on her face. "
    "Natsuki stands with her arms crossed with a sign of defeat and Yuri looks down and away as if she's processing the situation."
    n "Hrmm..."
    y "When you put it that way..."
    m "While I won't force you all to perform, I think it will go along much better if you do."
    m "If we can all focus on the goal, I have no doubt we will all do great. "
    m "And we won't just go out there without practice. For the rest of the week, we can focus on the festival. Tomorrow, we can begin practicing our performance."
    "Natsuki and Yuri's abrasive demeanor says it all."
    n "Wait, perform? In front of you all?"
    m "Well, yeah. A bit of primer before performing in front of a larger group"
    n "Bleh. Rather do it in front of strangers. It's less weird."
    mc "Wait, how is that LESS weird? "
    n "Strangers can't piece things together. Can't read deeper if they don't know you for real."
    "Yuri: Our opinions actually differ in that regard. I would feel more comfortable reciting amongst friends who are less likely to judge me harshly. "
    y "I notice that those more aware of my personality tend to avoid...improper interpretations of my work."
    
    mc "You two should do fine. I'm the weak link here."
    m "[player], you are in no way weak. Your work is getting better and with the right mindset, your performance can make it shine brighter."
    "I'm left speechless with a stupid grin creeping on my face. I'm still not used to anyone other than Sayori giving me praise like that."
    n "I'm still not sure...can't we just not? Or at least do something else?"
    m "We're already on the flyers the student council will be printing out. Doing nothing will make our club seem incompetent. "
    m "As for something else, if anyone has any other ideas, I'm glad to hear you out."
    "The room is filled with silence as Natsuki and Yuri struggle to think of any alternative."
    m "Then it's official. Tomorrow, we can practice in front of each other so we can get some practice in. We can leave Friday as a free day for now and we can go over the prep needed for Monday."
    "We all nod our heads to the announcement."
    m "Glad we're all on the same page. Well, that will be all for today. You're all free to go and I hope you all come prepared tomorrow."
    "As we all pack our things up, I check my phone. "
    "Huh. No word from Sayori. "
    "Monika said she got a message that she was home. Maybe she's got another update. "
    "I wave to the others as they leave and walk up to Monika."
    mc "Hey, did you hear anything else from Sayori?"
    m "Sorry, nothing since she said she was home. "
    m "Sometimes, we can go through things that need some time to process. While your intentions are good, it may not be the best for her right now."
    "I think about what she says and, yeah. It took me a while to open up and Sayori trusted me enough to let me open up to her. I should trust her the same way."
    mc "Thank you, Monika. For everything you've done for her."
    "Monika waves me off."
    m "No thanks needed. She's my friend as well, so I care about her wellbeing just as much as you do."
    mc "Well, I'm glad you're in her life. At least she had someone for the time where I was..."
    "Before the silence can last enough for it to get awkward, Monika breaks it."
    m "You're showing yourself to be a great friend as well. Not only to Sayori, but the entire club. "
    m "I honestly can't thank you enough for helping me get those two to agree to the performance. I know Sayori really had her heart set on it since it was initially her idea."
    mc "No need to thank me. I just said what was on my mind is all."
    m "And that can be more help than playing it safe and being quiet. You have more influence than you think."
    "Monika then gives me a sweet smile that I'm beginning to recognize as I spend more time with her. "
    "It's not a forced smile. It's quite natural, genuine and...dare I say...cute. That cute smile turn a bit awkward."
    m "Hey, [player]? Are you okay? You're kinda..staring a bit. Wait! Is there something on my-"
    "Monika pulls out her phone and begins to look at herself."
    mc "Oh, no. Sorry. I kinda got lost in thought thinking about your smile."
    "..."
    "Ahhh! WHY DID I SAY THAT OUT LOUD!!!"
    "Monika notices my frozen awkwardness and begins to chuckle."
    mc "I-I didn't mean it like- I mean it's not wrong, but..uhh"
    m "It's fine, [player]. I know I have a nice smile. It's okay to stare sometimes."
    "As she winks at me I can feel my temperature rise from the blood rush due to embarrassment. "
    "Sure am glad Natsuki has already left."
    m "Sorry, couldn't help but tease. But don't worry. I get lost in thought myself, so I understand. And thank you for the compliment."
    mc "Uh...no problem. Welp, best to head off now. See ya Monika."
    m "Have a good one, [player]. Try to keep your compliments to the clubroom. Don't want to give someone the wrong idea, right?"
    mc "Y-yeah. Right."
    "I walk out completely embarrassed as Monika giggles to herself."
    scene bg house
    "As I pass Sayori's house, I debate on if I should go and check on her. I mean, I can at least ask her mom-"
    "Wait! That's it!"
    "As I'm typing a message to her mom, I stop midway as Monika's words come to mind."
    "I remember how it felt when my parents were informed while I was feeling like this."
    "People meddling just made it worse. It didn't get better...until I went to Sayori on my own."
    "I just have to treat her like an equal and be here when she needs me. "
    "I erase the message and head home."
    scene bg bedroom
    "After eating and getting my homework done, I begin mulling over my performance. "
    "Should I try to perform one of my current poems or should I try to write something new? "
    "The thought of writing becomes a bit exciting."
    mc "Eh. Even if I don't use it, it will be good practice. Maybe I can turn my poems into a sort of trilogy..."
    
    # "Emotional Growth"
    # "As the storm shakes the tree"
    # "The seed dangles, holding tightly to the branches, fighting the wind and rain"
    # "The wind flings the branches to and fro while the rain's impact and moisture weakens the grip"
    # "As the grip is lost, the seed braces for impact, eying the concrete below"
    # "But the fall is manipulated by the surrounding elements"
    # "The wind, which pushed the seed, is now gently guiding the seed to fertile soil"
    # "The rain's powerful downpour has softened the soil, causing the seed to sink into the ground"
    # "As the seed sits in the darkness it begins to look for anything to grab on to"
    # "As it reaches in all directions, it feels a warmth that begins to spread within."
    # "As it embraces the the warmth, the view brightens until it breaks through the surface"
    # "As the sprout emerges, it looks back on its path thanking the elements"
    # "The turmoil afflicted lead to its emergence as a plant in prime conditions to thrive"
    # "******"
    
    mc "That's good for now. Even if I don't use it, it was a fun exercise."
    "As I put my notebook back into my bag, I see the roadmap sheet that I still need to fill out."
    mc "Man, what should I do for a career?"
    "As I look at the notebook in my hand, I start to think that being a writer wouldn't be that bad. "
    "Hmmm..."
    "I pull out the sheet and start filling out some of the basic information. I can work on the fine details later."
    return