label act1_day7:
    "Monday"
    scene bg club_day
    "Today has gone quite well. I was able to put a smile on Mr. Agawa's face by handing in the stack of work with maybe 2-3 assignments left. "
    "Sayori has been in high spirits since yesterday, and we are just finishing up the book. "
    "It looks like I wasn't the only one who wanted to get a jump on it either this weekend as it seems we all finished it about halfway through."
    m "Well, since it looks like everyone has finished, what were your thoughts on the story as a whole? Has anyone gained any insight for it?"
    y "While the accomplishments of the protagonist seemed cathartic in nature, their inevitable demise left a somber, bittersweet ending. A stark reminder to embrace the pleasures of mortality to the fullest as they can easily be cut short."
    n "Well I was hoping he would pull through. Yeah, they said terminal, but, bleh. I just hate sad endings like that."
    s "That's what makes it bittersweet. While yeah, it ended sad, they at least left some good memories behind for their loved ones to look back on and pass on to others."
    m "And your thoughts [player]? You've been awfully quiet."
    "I sit and think it over a bit."
    mc "To borrow words for Yuri and Sayori I'd say cathartic and I apt the good memories left."
    n "Geez, you can't think of an opinion for yourself?"
    mc "Great minds think alike.."
    y "-but fools seldom differ."
    mc "Huh?"
    y "Hmm?"
    mc "Sorry, I didn't hear what you said."
    n "She called you a fool, ya dummy!"
    y "Wha?! N.no! I was just..the full quote is-"
    mc "Don't worry Yuri. Took me a second to register what you said there." 
    mc "Natsuki just thought it went over my head, since she's so used to that feeling."
    "Natsuki begins to scowl and crosses her arms."
    n "Are you calling me stupid or are you calling me short?"
    "I look at her straight in the eyes"
    mc "Yes."
    n "Grrr!!"
    s "[player], don't be mean."
    mc "Fine. Natsuki, you are not stupid."
    n "... Wait a minute!"
    mc "Sayori said not to be mean, she didn't say not to be honest."
    "Natsuki begins giving me a death glare as I smile smugly at her."
    m "Alright you two. That's enough. "
    m "Well, there's a bit of time left, so we can have a bit of free time before dismissal. We can go over if we want to try another book or activity."
    "As Monika goes back to the teacher's desk, Sayori collects our books to return them to the library. "
    "Natsuki heads back to the closet as Yuri pulls out a notebook and begins to write. Sayori reaches me to get my copy of the book."
    mc "I forgot to ask, but what did Monika say about the poem thing?"
    s "She said she's a bit on the fence. She doesn't want to come off too pushy."
    mc "Okay. I can try to talk to her about it."
    s "You sure?"
    mc "Yeah. It may just take the word of the newest member to spark the activity. I mean, she has encouraged me to speak up about what I would want to do."
    s "That and you can use your boyish charms. Tee hee~"
    mc "Boyish? What happened to not being mean?"
    s "Not being mean, just being honest ~"
    "Sayori scurries out of the room to return the books."
    "Well, now's as good a time as any. I grab Monika's paper out of my bag and approach her."
    "As she sees me approaching, she gives me a sweet, genuine smile."
    m "Hey, [player]. Hope we haven't bored you too much here."
    mc "Not at all! It's quite enjoyable and the reading has helped me gain a bit of attention span back."
    "Monika giggles."
    m "Well that's a plus. Glad to see we're making a positive influence on you."
    mc "More than you know. Well, what I was wanting to do is to give you this."
    "I pull out the folded paper and hand it to Monika."
    m "Oh, is this a confess-"
    "Monika stops herself as she realizes what she was about to say to me."
    m "S..sorry. Force of habit."
    mc "Hey, it's okay. You've been around Natsuki, so I'm sure she affected you at some point."
    "As she opens it her face goes a little red."
    m "Oh. That's where this was."
    mc "Yeah. You dropped it on Friday and I didn't see it until you were long gone."
    m "You know, you could have texted me that you found it and I could have picked it up over the weekend."
    "I stand there blank faced"
    mc "I am just now realizing that was a possibility because I have your number."
    m "Most guys don't forget that."
    "I begin to blush and get flustered"
    mc "W..well I mean, I..uh-"
    "Monika starts laughing, causing me to become even more embarrassed."
    m "I'm just teasing, [player]."
    mc "Heh heh I knew that..."
    "I stand there in silence as she puts the paper back in her bag."
    mc "So..are you..okay?"
    "Monika pauses as she looks up at me curiously and then back to her note as she puts on a faltering smile."
    m "I take it you read it, huh."
    mc "I'm sorry, I didn't mean to invade your privacy, it's just I was seeing who it actually belonged to cause if I gave you someone else's thing it would have been-"
    m "It's fine. I'm not upset. To be honest, I'm a little relieved I was able to share it with someone, at least accidentally."
    mc "Again. Sorry"
    "Monika shakes her head."
    m "No need to apologize. I'm just glad it was you and not someone else."
    "We both stand in awkward silence for a bit."
    m "So, what did you think of it?"
    "I'm taken a bit back by the question that broke the silence."
    mc "Uh..."
    m "That bad, huh?"
    mc "N-no! I-"
    "I stop myself as I realize how loud I am. I turn around to see if we caught the others' attention. Yuri is still in her book and Natsuki is still in the closet moving things around."
    mc "It seemed well written, for what it's worth. While I don't find it bad, it kinda put me in a somber mood."
    "Monika slowly nods her head to me."
    mc "So, out of context, I would say it was good? I'm sorry. I don't really know how to judge poetry. But perhaps someone else might have a better opinion."
    "I turn to the others as Sayori comes back into the room with Yuri still in the same place and Natsuki sitting under the window."
    mc "I mean, seeing that made me more interested in trying to write poetry. Maybe that's what they need as well."
    "Monika thinks to herself for a moment while looking at the others. She then smiles at me."
    m "You know, I think that might work. I know they're both quite reserved, but maybe it just takes someone else to let them know it's okay to be vulnerable."
    mc "I wouldn't say I know them as much as you, but from my short experience I can see that."
    m "Looks like being nosey paid off for you."
    "Monika reaches into her bag and pulls out a small notebook."
    mc "Heh..I'll try not to make a habit of it."
    "As Monika gets up to address the club, she places her hand on my shoulder."
    m "Thank you for your suggestion. I really appreciate it."
    "I begin to feel my face getting hot."
    mc "No problem. Just doing my duty as a member."
    "Monika smiles at me and proceeds to the others."
    m "Okay, everyone! It's almost time to dismiss us for the day. But before we do, I want to discuss the next activity."
    n "Ooh Ohh! I got the perfect manga for us to read this go around! It's real dialogue heavy too."
    m "While I appreciate your enthusiasm, I was wanting to revisit the poetry activity. I know you and Yuri are a bit apprehensive, but [player] has voiced some interest in trying."
    n "So we just follow what the guy says now?"
    m "Now Natsuki, half of us were wanting to do this in the first place and [player] was basically on the fence. We shouldn't blame him for gaining a new interest. That's what this club is for."
    s "Plus he doesn't have nearly as much experience with writing as the rest of us. So it's understandable that he's reluctant off the bat."
    mc "I mean, yeah, but you didn't have to call me out like that, Sayori."
    m "Also, I know the main fear is the vulnerability of it all. So as an example of leadership, I am offering to perform one of my own proms to you all right now. Will you two hear me out?"
    "Natsuki and Yuri look at each other and then back to Monika."
    n "Sure, I guess."
    y "We will be willing to listen."
    m "Okay. Here it goes..."
    "Monika takes a deep breath and begins her performance with such grace and confidence that she's known for. "
    "As it goes on, I notice that her poem is not as sad as the lyrics she wrote, but a bit more abstract. "
    "Monika grabs the attention of everyone with her passionate voice and detailed delivery. "
    "I begin to lose myself in her every word as each phase bounces through my mind trying to articulate just how I should feel in this moment. "
    "The next thing I know, everyone else is applauding while Monika gives a casual bow. I try to follow suit with the others and begin to clap as well. "
    "Monika seems to notice my delay as she turns to me as I start clapping, giving a sweet smile to me."
    s "Wow, Monika! You really got a knack for poetry reciting. Are you moonlighting at open mic nights or something?"
    m "Ha ha...thanks, but that's a little too out of my wheelhouse. I'm still working on my presentation and felt like one of my older poems I've committed to memory would be a good presentation."
    y "Both your performance and your work are immaculate. I must say, I very much enjoyed the amalgamation of the abstract and simplicity presented in your writing. "
    y "It provides quite the breathing room for the imagination to wander. Not to mention the confidence in your presentation. It was awe inspiring."
    n "So are all your poems like that Monika? I'm pretty sure you fried [player]'s brain with it."
    mc "Huh? What are you-"
    n "Either that or he's crushing hard for you. Guy couldn't stop gawking enough to realize you finished."
    mcs "He/I was not gawking!!"
    "Everyone freezes and looks between me and Sayori as we look at each other in slight confusion."
    n "Pfft...okay. Just to save you from more embarrassment, let's just agree you were too slow for her poem."
    "I open my mouth to retort, but stop myself realizing the trouble with taking the other route."
    mc "*sigh* I will admit, some of the meaning is lost on me."
    "I look up slyly at Natsuki."
    mc "Why don't you enlighten me about the meaning of the poem? I mean, we have the author right here to confirm, don't we?"
    "Natsuki gets a bit of a shocked look on her face."
    n "Th-that's not how it works!"
    y "I will have to agree with Natsuki on this topic. While an author's intentions can be present in a work, more abstract pieces such as this leads to encouraging the reader's interpretation to provide their own viewpoint on the output."
    n "Yeah! That! It was way too abstract to mean just one thing.  "
    s "To be fair, it kinda flew over my head a bit as well."
    m "Well, poetry is a medium that can present new meaning depending on how you consume it. My writing style does get easier to understand when reading it and can lead to new meanings the more you reread it."
    "Monika looks at me and begins to wink."
    m "Isn't that right [player]?"
    "I look on as all the other girls start giving me a curious look."
    mc "Uh, yeah. Reading is a bit easier cause I can go back and catch things I didn't the first time."
    n "Well, in that case, I'm sure I can get you something that even you can understand. If you want a lesson in straight forward meaning, I'm already a pro at that."
    m "So does that mean you're interested in sharing poetry?"
    n "Well, maybe nothing too personal."
    "Yuri speaks up as well."
    y "I must admit, I was not immune to the persuasiveness of your performance. While I may not be comfortable with presenting verbally, I believe my nerves are solid enough to share my written work for you to read."
    s "Alright! Sounds like everyone's on board!"
    "Monika begins to beam, hearing that everyone is agreeing to the activity."
    m "Thank you all for giving this a chance. We can start tomorrow, so make sure to bring a poem to share with everyone. We can trade off with each other one on one to give each other some feedback."
    "Natsuki looks at me with a condescending look on her face."
    n "You sure we shouldn't give until next week? SOME of us might need the extra time."
    mc "I've got no problem with it, so I think little miss pro needs more time to think about what to write."
    n "Please. I can write 10 poems in the next hour that can blow anything you'll ever write out of the water, you amateur."
    s "It's not a competition, guys."
    m "Alright, you two. That's enough. Geez, you two make me feel more like a mother than a president."
    "Yuri and Sayori giggle as Natsuki sticks her tongue out at me as I roll my eyes."
    "As I pack my bag up after Monika dismisses us for the day, I feel a tap on my shoulder."
    m "Before you go..."
    "I turn around to see Monika staring at me with a comforting look on her face."
    m "I want to thank you again for your encouragement. I don't think I would have been able to perform that on my own."
    mc "I doubt I did much. I mean, you seemed so natural up there. It was quite..."
    m "...mesmerizing?"
    "Monika finishes my sentence with a cheeky smile."
    mc "I...guess you noticed. Sorry if I made you feel uncomfortable."
    m "Don't worry. I'm quite used to boys staring at me like that."
    "She giggles to herself while I begin to turn beet red."
    mc "I-it was more of the performance and the words and stuff. Kinda made me realize how unskilled I am at writing. I just hope I don't embarrass myself tomorrow."
    m "Hey, don't sell yourself short. We all start somewhere. And no one here will make fun of you for your efforts."
    n "No promises."
    "She briskly walks out the room looking back at me with her cheeky smile."
    m "Well, no one ELSE will make fun of you. We all have our opinions and biases. But the worst you'll get is constructive criticism, even with our resident sour patch kid."
    "I reflect on her words and I'm filled with confidence."
    mc "Alright. I'll do my best."
    "Sayori comes up to us and Monika glances towards her and me."
    m "That's all. You two have a good night. Looking forward to tomorrow."
    s "Same here!"
    "Me and Sayori walk out as Monika goes back to the teacher's desk."
    scene bg residential_day
    "On the way home, Sayori expresses her excitement at the idea of the club sharing poems."
    s "This is gonna be sooo fun! I can't wait to read everyone's poems."
    mc "Don't forget. You have to write one too."
    s "Of course I will. I'm not gonna let everyone down after you helped convince Monika to perform."
    mc "I wouldn't say I convinced her. More like I- wait. What made you think it was me in the first place?"
    s "Then what were you two talking about before she did?"
    mc "Oh. That. I was returning something to her."
    "Sayori looks away for a bit."
    s "Hey, [player]. Do you think Monika is a great person?"
    "Well that came out of nowhere. I turn to Sayori with a raised eyebrow."
    mc "Where did that come from?"
    "Sayori begins to point her fingers together."
    s "Well, she's pretty, talented, confident, and caring."
    mc "Sounds to me like you've answered your own question."
    s "With that said, I have noticed...things."
    "I slow down in my stride."
    mc "What kind of 'things?' Do you think she's doing drugs or something."
    s "N-No! Nothing like that! Not at all!"
    s "It's just...every so often, I look over at her and she's..kinda staring."
    s "At...you."
    "My eyes open wide realizing how perceptive Sayori can be."
    mc "I...also noticed it. Whenever I glance at her she looks away."
    "Sayori then starts looking at me with a teasing smile."
    s "Do you think she likes you?"
    mc "I mean, yeah. She doesn't seem to dislike any of us."
    "Sayori then jabs me with her elbow"
    s "You know what I mean. Does she LIKE like you."
    mc "HA! Yeah right. Her liking me like that? Not a chance. She probably has guys asking her out every class period. Besides, dating isn't something I'm looking towards at the moment."
    "Sayori's smile disappeared."
    s "Oh. Right. Sorry for even bringing it up"
    "She begins walking with her head down, staring at the ground."
    "I bump my shoulder into hers."
    mc "Hey. Don't worry about it. You've been a massive help with that whole thing already. "
    mc "Besides, even if I was ready to date again, I doubt Monika would give me the time of day in that regard."
    s "Stop selling yourself short. You're a great guy and any girl would be happy to be with you."
    mc "You say that like a mom. But for real, chances are she doesn't have time for a relationship. Probably why she turns down all the guys who approached her."
    s "But what if she said she was interested?"
    mc "Did she?"
    s "Huh?"
    mc "Tell you. Did she say she was interested?"
    s "Well, she hasn't said anything to me about it. But the way she looks at you, what else could it be?"
    mc "Well, I've thought of that and I have 3 reasons. 1. She is keeping an eye on the demeanor of the newest member, who helps make the club official."
    s "I can see that."
    mc "2. I'm the only guy there amongst pretty girls, so she's making sure I don't fulfill Natsuki's prophecies."
    s "I mean, you're not that much of a pervert."
    "I stop and stare at Sayori. She realizes and looks back at me as I look at her with a stone face."
    s "What?"
    mc "Slander aside, the last reason, and probably most likely, is the elephant in the room. Elsea."
    s "Ah. That one does make sense. I think they still have a class or two together as well this semester."
    mc "Yeah, it could be that she's heard some things. But...I don't know."
    s "Well, whatever the reason, I'm sure she had your best interest in mind. We both do."
    "She places her hand on my shoulder and sweetly smiles."
    mc "Thanks, Sayori. I greatly appreciate everything you do for me. And to answer your question. Yes. I think Monika is a great person. Almost as great as you"
    "Sayori starts to blush a little."
    s "Well, I'm nowhere near her level, but thanks."
    "I place my hand on her head and lightly pat it."
    mc "Anytime."
    scene bg bedroom
    "As I wave goodbye to Sayori, I head home and go straight to my room."
    mc "You've gotta write something that won't make an embarrassment of yourself."
    "I start jotting down a few things, but they all seem too cheesy."
    mc "What should I even write about..."
    "I look outside for some inspiration."
    mc "The white clouds reflect the sun's bright orange...."
    "I look around my room some more."
    mc "Uhh...open up dusk like the sky's door hinge? What does that even mean???"
    mc "Man, this is tougher than I thought. I can't show these to the girls. Without it some sort of inspiration..."
    "I then remembered Monika's poems and lyrics. They seemed so personal. Maybe..that's what I need to do."
    mc "*Exhale* Okay, [player]. I guess we're going there..."
    "I begin to write my thoughts out and after a few hours, I edit it down to something somewhat coherent before turning in for the night."
    # "***Reflections"
    # " While holding up the mirror in a need to inspect"
    # "A formless shadow is all that reflects."
    # "From the silhouette's center the glass starts to shatter"
    # "In the end, does it really matter?"
    # "I try to fix it myself, but get cuts from the glass"
    # "Without anyone's help, I don't think it will last"
    # "I was told what I looked like. Informed of my image"
    # "But with that outlook gone, it leaves my view diminished"
    # "So I stare out the window, embracing the rain"
    # "Since it's more of the same, viewing glass pane***"
return