label act1_day12:
    scene bg black
    "Saturday:"

    scene bg living_room_morning
    "My nerves seem to have gotten to me since I've been awake since 6am cleaning my house. "
    "It started with just a quick sweep and vacuuming, but the potential ridicule of Natsuki kept bouncing around in my head."
    n "Geez. You live like this? Have you even heard of a vacuum?"
    scene bg kitchen
    n "How am I gonna bake in this dirty ass oven? I ain't making trash cakes."
    n "Yuck! Your fridge smells like crap! I guess you are what you eat."
    n "So you just live around garbage? Birds of a feather..."
    #bathroom
    n "I wouldn't even wash my hands in that dank, disgusting bathroom."
    "How the hell is she badgering me without even being here?"
    scene bg living_room_morning
    "As I sit down in the living room with the sound of her voice out of my head, my door bell rings."
    mc "Wait, what time is it?"
    "I look at my phone and see it's 10:23. "
    "I have been cleaning for 4 hours. "
    "FffffffUuuuuu-"
    "*KNOCK KNOCK KNOCK*"
    mc "Alright! I'm coming."

    scene bg front_door_morning
    "As soon as I open the door, I see Natsuki standing there looking like a pack mule. "
    "If she was bringing this much, we probably should have done this at her place."
    mc "Didn't have room for the oven, eh?"
    n "Oh ha ha. If you can make jokes you can make yourself useful and carry some of this in."
    "I grab a bag and-"
    mc "The hell?"
    n "Pfft. Do you even lift, bro?"
    mc "It's not that it's heavy. Just heavier than I thought it was gonna be."
    n "Sure whatever you say."

    scene bg kitchen
    "As we set everything in the kitchen, Natsuki begins to go through the fridge."
    mc "Uh, it's customary to ask before going through other people's stuff."
    n "I'm just making sure you got everything we need to-"
    mc "Milk, cream, eggs, and vanilla extract. Got more than enough."
    n "Alright, but if we don't have enough of something, you'll be on fetch duty. And I ain't starting til we have everything."
    mc "So you just expect me to leave you here alone and unsupervised?"
    n "Why would I need supervi-"
    "Natsuki's face gets flushed as she comes to a realization."
    n "W-wait. Your parents aren't here?"
    mc "Nnnoo."
    n "You mean just for now, right? Like they'll be back later?"
    mc "Later this month, yeah."
    "Natsuki begins to slowly inch away from me."
    n "So you mean it's just you and me...no one else lives here or will be coming, right?"
    mc "That is correct."
    n "...How close is Sayori again?"
    mc "Close enough to hear your screams."
    n "Pfft! L-like I would be afraid of you. You can barely lift my bags. It's just..."
    mc "Just...what?"
    n "I've...never been by myself with...a...boy."
    "I look over at Natsuki and can see that while she's trying to put up a front, she is clearly uncomfortable."
    mc "So I'm just a boy now? I thought I was a weak dummy that you can easily outsmart and over power."
    n "I mean, you are. It's just..."
    mc "If it helps, don't think of me as a boy, think of me as a friend."
    "Natsuki begins to smile coyly."
    n "You mean like a boy frie-"
    mc "Nope! None of that! Shame on you!"
    "Natsuki giggles at the response and begins to relax her stance."
    mc "Alright fellow club member, do we have everything needed?"
    n "Yeah, looks good. Let's get started."
    mc "So, where do I begin?"
    "Natsuki looks over everything as she begins placing bowls, pans and ingredients in certain places."
    n "Imma get everything set up. Go preheat the oven to 325 and get the stuff out the fridge and place them...here."
    mc "On it."
    "As I get the oven ready and grab the stuff out of the fridge, Natsuki is steadily organizing the utensils, measuring cups, and measuring spoons."
    mc "Wow. You really have a system, don't you?"
    n "Wouldn't be a pro without one. Here, place these cooling racks on the stovetop."
    mc "Uhh...why a cooling rack near a hot thing?"
    n "The cakes will need to cool off slowly so they don't collapse. We let them sit for a while in the pans before moving them to the racks, which are still in a warm enough area."
    mc "Huh. Didn't know that. How did you learn all of this?"
    n "Oh! Uhh...internet."
    "That hesitation brings out my skepticism as I stare her down."
    mc "Really? Just the internet?"
    n "Mmm-okay, fine! I learned a lot reading parfait girls."
    "I begin to crack a smile, which seems to trigger her rage."
    n "See! This is why I-"
    mc "That's cool! So they actually go into actual baking in that?"
    n "Huh? Oh, yeah. Kinda. "
    n "The cooling is actually how they stopped the Cakenstien monster from reaching full strength when he was done being baked. "
    n "Shot em with cool whip and froyo and he collapsed in on himself."
    mc "Man, I love when you can learn things like that from manga."
    n "Yeah!"
    "As Natsuki begins to portion things out, she sets 2 work areas for us."
    n "Alright. I'll start you off on something easy. We're gonna have you make the frosting. We've got 4 colors here, so you'll be making 4 batches."
    "As she walks me through the steps, it doesn't seem too difficult. I begin to start as Natsuki pulls out her phone and starts playing music."
    mc "So...this is the type of music you like?"
    n "What? You don't like K-pop?"
    mc "Got nothing against it, just not my cup of tea."
    n "Well this is a new album. My friends introduced them to me and I can't bake without this album."
    mc "So I should be thanking the music for making your cupcakes taste so good?"
    n "They're delicious no matter what. But, I will admit, it can help with timing in the kitchen."
    "As I'm working on my side, I see she was not kidding. After about 2 songs, she has a large batch of batter done."
    n "How's the frosting coming?"
    n "What the hell? It's still lumpy and runny? Show me how you were mixing."
    mc "Uhh...good I guess? Is it supposed to look like this?"
    "As I begin mixing, she face palms."
    n "Bruh. The hell is that? It needs to be faster. Like-hold on."
    "Natsuki goes to her phone and scrolls through until she finds what she's looking for. She then plays a very energetic song with what sounds like a sped up guitar solo looping."
    n "Alright. Now whip it to the beat. Like this."
    "She begins making the movement with an empty bowl and a spatula. As I follow suit and try to keep up, I notice the frosting getting smoother and fluffier."
    n "See? There ya go! If you need, can set this on repeat for ya. It's a banger!"
    mc "Hell, might as well."
    "By the time I get the first batch done, Natsuki has already panned up 4 trays of cupcakes and is putting them in the oven."
    n "Alright. Put all the frosting in the fridge to keep it cool. We'll wait for the cakes to all cool before we start decorating them."
    mc "Got it."
    "Natsuki turns off her music and sets a timer on her phone after putting the pan in the oven. "
    "She heads over to another bag and begins ruffling through it."
    mc "Something else we need to do?"
    n "Yeah. Finish this!"
    "She pulls out her first edition copy of Parfait girls 0."
    n "We should have enough time for the first batch to finish and cool off to read the rest."
    mc "Sure! I'm down."

    scene bg living_room_morning
    "As I begin to move towards the living room, I hear chairs moving. I turn around to see Natsuki moving the chairs in front of the bar to sit on the floor."
    mc "Uhh..what are you doing?"
    n "Making room to read."
    mc "So, you always read on the floor?"
    "Her demeanor shifts and she gets a little irritated."
    n "I-I just don't wanna sit anywhere you ever did. If you live here alone you probably sit everywhere naked. "
    "I don't wanna take the chance to sit on your taint sweat."
    "She looks away from me."
    mc "Natsuki?"
    n "FINE! FORGET IT! I don't know why I brought it in the first pla-"
    "I grab her shoulder stopping her from getting up and walking away and proceed to sit down next to her. "
    "I don't get it, but I have a feeling it's something sensitive. "
    "Knowing what I know of her, I should just let her be without explaining it."
    mc "It's alright. It's easier to read this way. Any other way would have one of us at a weird angle."
    "Natsuki looks back up at me with glossy eyes."
    n "*Sniff* Yeah. That's what I was trying to get at."
    mc "I got ya. Now. Where were we?"

    scene bg kitchen
    "As we're finishing up the manga, the timer goes off. Natsuki gets up and begins to take the cupcakes out. They look amazing."
    n "Alright. I'm about to start the second batch of batter. You take these pastry bags and start filling them up with the frosting. DON'T start trying to add it yet."
    mc "I wouldn't dare! No way am I gonna turn these things into cakenstein."
    n "Ha ha. Very topical... Dork."
    "I fill up the bags and Natsuki is still in the middle of making batter."
    n "Alright, CAREFULLY move the cupcakes from the pan to the cooling rack. I should have this batch done by then."
    "After about 10 minutes of concentrated surgical precision, I emptied the trays and emptied them with linings."
    n "Huh. So I don't have to spoon feed you instructions."
    mc "Nope. I'm just a dummy, not a moron."
    n "Well..."
    "Natsuki in no time fills up the trays and has them in the oven."
    n "Good. By the time those are done, we can start decorating. "
    n "I did have a bit more batter than I thought, so we can make one more tray after these."
    mc "In case I mess up decorating the first ones?"
    "I look at Natsuki and she begins to look down."
    mc "What is it?"
    n "It's just...you're a competent guy. You know that right?"
    "Huh? Where did this come from?"
    n "I know I shoot the shit with you and try to get your goat a lot, but I think you're...decent. I just wanna make sure you know that."
    mc "Uh, yeah. Thanks."
    n "So leave bad mouthing you to me, got it?"
    "Woah. I didn't think she would care about...but then again. "
    "She is the one to protect her friends. Even from themselves."
    mc "Got it. Sorry."
    n "No prob. Besides, you'll never get to date Monika if you keep looking down on yourself."
    mc "Gah! What the- what are you talking about?"
    n "You guys are always eyeing each other, dude. It's so freaking obvious."
    mc "I...don't know what you mean. She's just...you know..."
    n "Undressing you with her eyes?"
    "My face is turning redder by the minute."
    mc "I HIGHLY DOUBT THAT!!"
    "Natsuki begins cackling at my discomfort."
    mc "If anything, it's probably cus I'm the only guy in a club full of cu-"
    #"I glance at Natsuki as she scowls at me."
    "[player]:... Curiously diverse group of girls?"
    n "Hmpf. Could be..."
    "As Natsuki walks me through the process of decorating, the second batch finishes baking. "
    "She gets them out of the oven as I continue to decorate."
    n "Alright. Last one's in. How you doin over there?"
    mc "Bout 5 more. Geez you can really tell which one's are mine."
    "*WHACK*" #[Smack Sound bit]"
    "I'm thrown off from the punch to the arm."
    n "What did I say about bad mouthing yourse-"
    mc "I meant because yours are perfect and mine are just okay! Sheesh!"
    n "Oh. Well, stop pointing out the obvious and finish up."
    "As I finish the last of them, Natsuki has already moved the cakes to the cooling racks and placed the pans in the sink."
    mc "Oh. I can get the dishes."
    n "Really? Sweet!"
    "Her chipper demeanor soon sours as she stands there looking around."
    n "Eh...I can do it. I gotta do something."
    mc "Got any other manga to read?"
    n "*Scoff* yeah, right. It was hell trying to smuggle the one I DO have. I had to-"
    n "CRAP!"
    mc "What happened?"
    n "Did you throw away that cake mix box?"
    mc "Well, yeah cus we're done, right?"
    n "SHIT SHIT SHIT!!!!"
    "She begins freaking out and hyperventilating. She then turns to my cabinets and starts tearing through them."
    mc "Whoa! What the hell's going on?"
    n "I need a box to hide my manga!"
    "Mc: Wait, what?"
    n "If my dad ever sees this, he'll try to sell it for sure!"
    mc "Wait, sell it?"
    "Natsuki freezes as she just realized what she revealed to me."
    n "*Sigh* These books have been the only escape from my shitty life. "
    n "I'm already on thin ice with Monika with the teacher about stashing them in the closet. If I don't have that..."
    mc "...If you need a safe place to stash them...you can always leave them here."
    n "Huh?"
    mc "Yeah. We've actually have a guest room with empty drawers that's not used as much anymore. We can keep them in there."
    n "You sure it's okay? What will your parents say?"
    mc "They spend as much time on the road as they do home. I doubt they will notice. At most, they assume they're mine."
    n "Hmmm...I'll...think about it."
    mc "Just let me know when your mind's made up. I already have the copy of Red Gauntlets you lent me. I can keep that one as well."
    "Natsuki picks up the book and holds it close to her as she thinks."
    n "Not this one! I can try to...hope he doesn't..."
    "As I think about it, I get an idea."
    mc "Just a moment.."
    scene bg bedroom
    "I run upstairs into my room and go through my bookshelf. "
    "I find an older textbook that is about the same size as the manga and take the plastic cover from it. "
    scene bg kitchen
    "As I head back down, I hand it to Natsuki."
    mc "Maybe this can help?"
    "She takes it and inspects it for any dust, smudges, or stains and then places it over her manga. She holds it back and looks at it."
    n "Yeah, I think this may help. It won't be long term, but it's something."
    "Natsuki puts her book back into her bag and begins to calm down and get more chipper."
    n "Kay. Let's finish this out!"
    "As Natsuki is finishing frosting the last pan, I had the dishes all cleaned and dried."
    n "That'll do it! You sure you have enough room in your fridge for all these containers?"
    mc "Got no choice. It's either that or risk some at Sayori's house."
    "Using my slightly above average Tetris skills, I'm able to get the last container in the fridge. "
    "I turn around and Natsuki is already done packing her things back up."
    n "Alright, I need to get going. Thanks for having me. And keep the cupcakes safe from the resident snack monster."
    "As she's looking lopsided from her load already and is trying to add another bag on her shoulder, I grab it for her and put the straps on my shoulder."
    mc "I can help you carry these home, if you want."
    n "I made it here with more. If anything the load is lighter. I should be fine."
    mc "Honestly, this is for me. I need some fresh air anyway."
    n "I mean, I don't mind, but I walk pretty fast, so you better keep up."
    mc "Heh, with those little legs of yours, I'll have no problems."
    "Natsuki growls at me while I lock my door, but I can hear the slight joy in that growl."
    scene bg natsutki_house
    "The walk wasn't bad, but I still can't believe she carried all this stuff by herself. I can tell during our small talk she was happy I offered, but I doubt she would admit it."
    "As we approach her front door, it begins to open. Natsuki's face flushes as she sees who opened the door."
    n "P-Papa!?"
    "Pfft! Papa?" 
    "Wait..." 
    "PAPA!!!?"
    "Oh crap." 
    "He stands at the door glancing at the both of us."
    n "W-what are you doing home so early?"
    nd "It was slow. They set some of us home. Had too many hours so I drew the short straw. "
    nd "Who is this?"
    "Natsuki looks at me in a slight panic. She takes a breath and calms herself down before replying"
    n "Oh, he's just someone from school. He offered to help me carry my stuff back from my clubmate's house."
    "That...is technically the truth."
    nd "Head inside Natsuki."
    n "Yes, papa."
    "She scurries inside without looking at him or looking back. He closes the door behind her and then walks towards me."
    nd "I'll take the bags so you can be on your way."
    mc "S-Sure. Here you go."
    "As he grabs the bags, he just stands there and stares at me."
    mc "Uhhh-"
    nd "What is your name?"
    mc "Uhh...?"
    "He raises an eyebrow at me."
    nd "Are you not sure of own name?"
    mc "I-it's [player]"
    nd "Good. Now. Did my daughter tell the truth just now?"
    mc "Y-yes."
    nd "Are you dating my daughter?"
    mc "N-no!"
    nd "Are you trying to fuck my daughter?"
    mc "NO!"
    nd "Do you have any ill intentions towards my daughter?"
    mc "No!"
    "He continues to glare at me as I nervously look back. It's okay. You're not lying. Theres nothing to be afraid o-"
    nd "Good. Head home, [player]. Have a good night."
    "Huh?"
    mc "Y-Yeah. Same to you, sir."
    "He turns around and heads into the house. As I hear the door lock, I still stand there in confusion."
    mc "Did...did I just get interrogated?"
    scene bg residential_day
    "As I'm approaching home, I see Sayori waving by to a car driving off. I slowly approach Sayori from her blind spot."
    mc "Was that Yuri-"
    s "EEEEP!!"
    "Sayori freezes up and slowly turns around. When she sees my cheesing face she begins slapping me on the arm."
    s "THAT WAS NOT FUNNYYYY!"
    mc "Heh heh, it was from my angle. "
    mc "So, you two are all done with decorations?"
    "Sayori stops hitting me and then gets sheepish."
    s "Eh heh...we got a little carried away and have to finish tomorrow."
    mc "So you two just goofed around all day?"
    s "We didn't goof around! We got a lot done! "
    s "It's just..one idea led to another..and we got posters, a banner, a ribbon curtain with kanj-"
    mc "I get it, I get it! You two kinda went into the deep end."
    s "We couldn't help it! My ideas gave Yuri ideas, and then THOSE ideas gave me ideas, and then..."
    "As she looks at my stoned faced look, she stops."
    s "I'll call Monika to get some advice on how far we should go. So how did you and Natsuki fair?"
    mc "Pretty good. I know how to make frosting now. And we should have plenty of cupcakes for the festival."
    s "Speaking of which, I think I may have to do my duty as vice president and check on your work..."
    mc "Or I can have the president do that tomorrow while she's over. You know, seeing she's less likely to sneak one or eight."
    s "Hmpf. Meanie..."
    "We both laugh a bit as Sayori's face turns a bit wistful."
    s "Yeah, you're right. Monika's got it. She really is an amazing person. "
    s "The way she conquers everything she puts her mind to, and she's a rock of a friend. So loyal and trustworthy."
    mc "Uh...huh..."
    "Well that was out of left field. I mean, she is not wrong, but what prompted all of that?"
    s "...I mean, if you think about it, she would make a great girlfriend."
    "Huh?"
    "..."
    mc "Wait, what!?"
    s "Hmm?"
    mc "Uhh...are you...wanting to confess something?"
    s "What's that mom? Oh, yeah, coming! Gotta go, [player] ! See ya! Byeeee~"
    "She rushes back into the house in a hurry, leaving me dumbfounded."
    mc "...What the-"
    "*VVRRBBBB* *VVVRRRBB*" #[Phone Vibrations Sound]"
    "I check my phone and see a new message from Monika."
    #"[Phone Screen with Text]"
    m "Hey, [player]! Just checking to see if you can confirm that your printer works and that you have enough color ink. "
    m "I will want to make sure beforehand just in case I need to schedule a trip to the library to get these printouts done tomorrow."
    "Crap! I forgot to double check! I run right into my house and head to the office room."
    #"[Home Interior Office Room]"
    "As I go through the closet, I find the color printer and multiple teams of paper. "
    "Lucky dad stocked up before he found out he had to switch to PowerPoint and email his presentations. "
    "I pull out the printer and hook it up to my laptop."
    mc "Okay, what should I try and print?"
    "I scroll through pictures I have on my laptop and stop at the ones I had of Elsea. "
    "These were before we were even going out."
    "As I look through them and reminisce, I can't help but feel bittersweet about these moments. "
    "As I continue, I then get to the ones of me and Sayori."
    mc "Heh...she hasn't changed a bit."
    "I choose one of me and Sayori and print it off. I check for any lines or spotting."
    mc "Huh. This came out great!"
    "I take a picture of it as well as the ink cartridges and paper and send them to Monika."
    #"[Phone Screen with Text]"
    mc "Looks like we're stocked. No worries here!"
    m "Great! And aww, you two are so cute :)"
    mc "Yeah, Sayori's barely changed, hasn't she?"
    m "I can say the same about you lol."
    "...Did...she just call me...cute?"
    m "Alright. I can be over around 10am. That okay with you?"
    mc "Yeah. That'll work. See ya tomorrow."
    "I head back to my room and sit on my bed. As soon as I sit, I just realize...I've been up and busy since 6am. "
    "My body can definitely feel it as I lay back and slip right into sleep."
    return
