label act1_day6:
    scene bg black
    "Sunday"
    scene bg bedroom
    "As I wake up, I reach for my phone to check the time."
    "11:38"
    "Geez. Basically slept through the entire morning. "
    "No surprise, I spent all day yesterday staring at books and pages. But at least I got it all done. "
    "As I reflect on this, I start to feel like a weight is off my shoulders." 
    scene bg kitchen
    "As I go down to get something to eat, I open the fridge to..."
    "Absolutely nothing."
    "Oh yeah. I needed to get groceries."
    "I dig through the cabinets and find a couple of granola bars that I snack on as a type of list on my phone. As I'm typing, I get a message from Sayori"
    s "Hey [player]! Get any progress yesterday? [Add phone screen here with the text]"
    "I remember on our walk home that I told her my plan of barreling through the rest of my homework. I figured at the time it was the easiest thing to open up to her about."
    mc "Yeah. I got basically all of it done. Just got my post school roadmap to do."
    s "Cool Beans! : )"
    s "So Whatcha got planned today? "
    mc "I gotta get groceries. Ran out of food."
    "As I sit there and go back to thinking of food to add, it hits me: Sayori most likely wants to hang out today. "
    "Sure, we spend time in the club and on walks, but we haven't really done anything outside of school together in a while."
    mc "Hey, would you want to head out with me to the store? We can take a few detours on the way there. I was planning on heading out soon anyway."
    "..."
    "..."
    s "Yeah! I'll be ready in a bit! You can come over whenever!!"
    mc "Great! See you in a few."
    s "See ya!! : D"
    "I chuckle to myself as I grab my reusable bags and head out."
    scene bg house
    "As I approach Sayori's house, I reach for the door knob to let myself in, but stop myself."
    "What am I doing? I should be knocking first. "
    "As I go to knock, I stop myself again."
    "Wait. You never used to knock. We would always go in and out of each other's houses like we were family. I reach back for the doorknob. "
    "I Stop myself again. "
    "But that was before. Things are different now. We aren't that close anymore. Are we?"
    "As I stand there frozen, the door opens, snapping me out of my trance. It opens to Sayori's mom standing in front of me."
    "Sayori's mom: Why, hello [player]. This is a pleasant surprise!"
    "I grow pale from the confrontation. I'm still embarrassed from Tuesday."
    mc "Uh, yeah. Hi. I uhh, came to take Sayori out."
    "Sayori's mom lifts her eyebrow and grows a sly smirk on her face."
    sm "Oh my. Did you finally come to your senses about my sweet girl or are you treating her like a rebound?"
    "W...What?"
    mc "N..NO! Not like that! It's-"
    sm "Oh, my little girl isn't good enough for you?"
    mc "NO! I MEAN..YES!? I mean..uh-"
    "Sayori's mom bursts out laughing as I stand there completely in panic"
    sm "Heh heh.hoo..I'm sorry. I couldn't resist. Come on in, [player]."
    "I walk in cautiously as she continues to chuckle to herself."
    scene bg sayori_livingroom
    sm "SAYORI! [player] IS HERE!"
    s "I'LL BE DOWN IN A FEW!!!"
    "Sayori's mom: She'll be down in a few."
    mc "R..right..."
    "We both sit in the living room waiting for Sayori. "
    "Sayori's mom begins to pull out her phone and start scrolling, watching video clips on her feed at full volume."
    "Geez, this is almost as awkward as Tuesday. But, she seems so relaxed with the situation. Almost like she forgot what happened. Or...she just moved on."
    "I clear my throat and she looks up at me."
    mc "I'm, uh..sorry for the other day. I was not in my right mind, I know I was being unreasonable and you were just looking out for me."
    "She puts her phone down and walks over to me and places her hand on my head."
    sm "That's what mom's are for."
    "She smiles sweetly at me before popping me upside the head."
    "Sayori's mom: And stop letting these girls run your life like this! A crush is nothing to ruin your life over. Got it?"
    mc "Yes, ma'am. Sorry, ma'am."
    sm "Good. Now, what are you two planning to do today?"
    mc "Well, I was going to get groceries, but I figured Sayori would like to hang out for a bit first. Probably just a walk around town for a bit."
    sm "Well, it's good you two are spending time together again. She's been quite worried about you lately. She hides it well, but a mother knows."
    mc "Yeah...Again. Sorry."
    sm "Don't be sorry. Be better."
    "I sit there for a bit and reflect on that."
    "Sayori's mom: So, what food are you getting? You have a list or are you just winging it?"
    mc "No, I have a list."
    sm "Do you mind if I take a look."
    mc "Uh...sure."
    "I open my list and hand her my phone."
    "As she scrolls through the list, she begins to look more and more disappointed."
    sm "So your list is just instant food and snacks?"
    "Now that I think of it, That is all I could really think of."
    sm "Son, you need some real food. Do you have any meal ideas?"
    mc "No, not really."
    "Sayori's mom sighs as she pulls out her phone."
    sm "Okay, I've got a few recipes for you. This is a special list I've been building that I call my Sayori proof list."
    "My phone rings and it's a list of links for recipes that vary from simple soups and stews to full course meals."
    sm "Tell you what; Make sure you take your time with Sayori before going to the store. I'll go through these and type out the ingredients list for you. "
    sm "Add these to your list. The instant stuff isn't bad in a pinch but shouldn't be your only source of food."
    mc "Thanks. This means a lot!"
    sm "No problem. Heck, half way returning the favor. Can't tell you how often you and yours watched out for Sayori. Plus half of these came from your mom."
    "I hear the closing of the door and clomping down the stairs to reveal a winded looking Sayori."
    s "I'm here! I'm Ready!"
    "Sayori's mom: What did you have to find?"
    s "Eh heh..my wallet..."
    "As we head out the house, Sayori gives her mom a hug and kiss on the cheek."
    s "See ya Mom!"
    sm "See you later, sweetie."
    "Sayori's mom came to me and gave me a hug and I hug her back."
    sm "Bye, [player]. Take care of my baby."
    mc "Will do. Have a good one."
    scene bg street_2
    "As we walk, I look up at the scattered clouds."
    mc "It's a beautiful day for a walk, huh."
    s "Hmmhm. Sure is."
    "Geez this is awkward. "
    "What do I even say to her? What can I say? I know she wants me to open up to her about Elsea, but doing it now feels...off. "
    "I know she cares and she's always out to help everyone feel better, but doing that out the blue doesn't sit right. I don't want to feel like I'm only using her for that."
    "I look at Sayori and she's wearing an awkward look on her face."
    mc "So, uhh. Is there anywhere you wanna go?"
    s "I thought you said you were going grocery shopping?"
    mc "Well, yeah, eventually. But I also wanted to spend some time with my best friend."
    "I then put on a pathetic excuse for a puppy dog pout."
    mc "If that's okay with you."
    s "Pfft..you know, you don't need to beg like that. In fact, that makes me wanna be further away from you out of sheer creep vibes."
    "Sayori playful widens the gap between us."
    mc "Okay, I get it. That's your trademark."
    s "Exactly! Now you owe me for copyright infringement!"
    mc "What's the damage?"
    s "Hmmm. Oh! Cinnamon buns! From Mugiho's bakery!"
    mc "Mugiho's, huh? It's been a while. Yeah. Let's go."
    "Sayori cheers as she skips along."
    scene bg park
    "We decided to walk through the park on our way to the bakery. "
    "As we look around, it's filled with kids running though the field and on the playground. The atmosphere is so lively that it puts a smile on my face."
    s "Wow, talk about memory lane!"
    mc "Yeah. That used to be us out there."
    s "Do you remember the time we tried to walk on top of those monkey bars?"
    mc "Heheh. Yeah. Almost gave mom a heart attack."
    s "Oh! The pond where the goose chased you down!"
    mc "I was just trying to pet the baby geese."
    s "Are you still afraid of them?"
    mc "Terrified."
    "We both laugh at each other."
    mc "And look over there! Your favorite biking buddy!"
    "Sayori looks confused as she follows the direction I pointed and then looks bemused."
    s "It's not my fault! Stupid tree came outta nowhere!"
    mc "3 different times?"
    s "Maybe it's hiding a Sayori magnet!"
    mc "Uh oh. I think you're right!"
    "I begin to start gently walking her towards the tree."
    s "Heh heh, hey! Cut it out!"
    "???: WATCH OUT!!"
    "I turn around to see a frisbee flying towards us. I grab Sayori and hold her in front of me as I brace myself for impact."
    "SMACK!!"
    "The frisbee hits me in the back, but it's not hard enough to hurt. I pick it up and hand it to a child running up to get it back."
    "Kid: Sorry bout that mister."
    mc "No problem"
    "I turn to Sayori, who seems a little startled."
    s "Are you alright?"
    mc "Yeah. It was just a frisbee. Not like they attacked me with a steel chair."
    "Sayori begins to softly smile."
    s "It's good to know you're still looking out for me."
    s "Mister~"
    "She begins to giggle to herself."
    mc "Hey, if I'm a mister you're a ma'am."
    s "As if! I'm still young"
    mc "Sure you are, grandma."
    "Sayori squints her eyes at me."
    s "Oh yeah?"
    "She then runs up to a nearby tree and begins to start climbing it. "
    "As she sits on a branch, she smiles down at me with the brightest grin I've seen on her in a while."
    mc "Lookin a bit winded up there."
    s "I'm sorry, I can't hear grandpa's from up here!"
    "I shake my fist at her and then proceed to try and climb the tree as well, but all my loafing around caught up with me as my legs begin to give out."
    "SMACK"
    "I land right on my ass and I give out a pathetic groan."
    "Sayori climbs down the tree and comes over to me to help me back up"
    s "[player], are you okay?"
    "I get up and rub my back."
    mc "Dag nabbit tree done did bruised my bum!"
    "I look at Sayori and we both start laughing."
    s "Kinda ironic if you think about it. You used to be the one climbing trees and I was the one falling on my butt."
    mc "Except this time, you don't have to keep me from crying when I fall."
    "As we continue on the trail, I start thinking about opening up with her. [I feel we should exclude this line. Let it come naturally for the scene]"
    "Man, it really does feel like nothing has changed and today just solidified that I'm still comfortable being vulnerable with her about silly stuff, so I should start up with the serious as well."
    mc "Speaking of me crying when I fall, I..."
    "You can do this."
    mc "I just want to say thank you for being there for me. Even when I didn't notice. I would have been in a bad place if not for you and you've done so much to cure the loneliness I've been feeling."
    "Sayori begins to smile softly and tear up a bit."
    s "[player]..."
    mc "I feel horrible about the breakup in every way possible. I hate how I took it, I hate how I treated everyone else because of it-"
    s "It's okay, [player]! Everyone makes mistakes."
    mc "That's the thing. It didn't even feel like a mistake. It just felt like..."
    "I stop walking and begin to look down. Sayori stops and turns around towards me."
    mc "I look back on it and feel like I was just a drain on Elsea. Like a leech. "
    mc "I had no plans, no ideas, I was just a blank slate for her. Hell, chances are, she only went out with me because I was convenient. "
    mc "And I went out with her because she asked. I mean, what guy wouldn't, right? Just the right place at the right time I guess."
    "I start tearing up as Sayori begins to place her hand on my shoulder."
    mc "The more I think about it, the more I realize I was in the wrong, everything she said about me was true. I was a waste of space and the best thing I could possibly do for her now is stay out of her life."
    "Sayori embraces me tightly."
    s "Stop it! You are NOT a waste of space!"
    "I can feel her tears soaking through my shirt."
    s "You made mistakes. But you are NOT a leech! You are NOT a blank slate!"
    mc "I've been nothing but a passenger in my own life, dragging down those around me. "
    mc "I mean, look at you! You're the vice president of a club now. Before me you probably wouldn't have even tried. Just like I've stopped trying."
    "Sayori pulls back to look me in the eyes."
    s "You haven't stopped trying! Not with your work, not with Natsuki, and..."
    "She buries her face into my shoulder."
    s "And you haven't stopped trying with me. I know you're sorry and feel horrible for your mistakes, but you're taking responsibility. You're not ignoring it. You're...being better."
    "Her words seem to melt my heart as the tears flow and I fully embrace Sayori as well."
    "We stand there for a while until I notice how many people are watching. Way to have an emotional breakdown in public."
    "I pull away from Sayori and look her in the eyes."
    mc "Thank you. For listening, for being here, for understanding, for being...you."
    "Sayori smiles through her tears."
    s "What are best friends for? It's my job to make sure you're happy."
    mc "Heh, yeah. I guess I've been slacking on my end haven't I? I should try more to make you happy as well."
    "Sayori gives a sad smile for a moment as we both wipe our eyes dry."
    s "Don't try to change the subject. We're focusing on your happiness today. You don't need to worry about me, silly."
    mc "So we can just skip Mugiho's and head straight to the store?"
    "Sayori perks up."
    s "Well...maybe we can focus on my tummy's happiness. Plus, you buying me treats is your favorite pastime!"
    mc "I wouldn't say favorite, but as long as I can put that smile back on your face, it's worth every cent."
    s "Yay! Let's go! Mu-gi-ho's! Cinn-a-mon Rolls! Mu-gi-ho's! Cinn-a-mon Rolls!"
    "She continued the chant until we made it out of the park."
    scene bg cafe
    "As we walk into the bakery, we are hit face first in nostalgia. "
    "The sweet smells of baked goods, the same tables that they would eat at as kids, even the same menus, with the only difference of them being slightly more faded then memory."
    "Sayori is entranced by the sight of all the fresh baked desserts. She is nearly pressing her face to the glass drooling."
    "A cashier comes to the front, staring at Sayori in confusion."
    mc "Sorry about her."
    c "It's no problem. Just make sure she cleans any drool."
    "Sayori overhears and nervously wipes her mouth with her sleeve as she pulls out her phone to start taking pictures."
    mc "Uh, can we get 2 cinnamon buns and an Apple fritter?"
    "I pay for the food and grab the tray. As I'm walking to a table, I get Sayori's attention to sit down."
    "As she comes to the table, she looks at the tray in a bit of a confused state as I place both of the cinnamon buns on her side"
    s "Wait, two?"
    mc "I remember you would always ask for a second as a kid, so I figured I'd nip the trying to steal mine in the bud by giving you two off the bat."
    "Sayori begins to pout, but then begins to laugh."
    s "I couldn't help it. They were always so good and you were so slow when eating."
    mc "I didn't realize chewing was a handicap. Guess I need to train my jaw to unhinge or develop some mouth acid."
    s "Hey, whatever it takes to get more buns in your tums, hun!"
    "As we're eating, I get a notification on my phone. I look and see that Sayori's mom texted me a decent sized list, organized by the meal recipes."
    mc "Are you ready to head to the store now?"
    "Sayori nods her head as she finishes chewing her last bite"
    s "*gulp* yup! Fueled up and ready to rock!"
    mc "Alrightly. Let's head out."
    scene bg store
    "As we get into the store and get a cart, we begin to go through the isles, deciding what all I can carry on my way home. While we talk, the Literature Club comes up."
    s "So, how are you feeling about the club so far?"
    mc "Are you asking as my best friend or as the vice president?"
    s "Hmm...little from column A, little from column B. Hee hee-"
    mc "Heh. Well, it hasn't even been a week, but great so far. I mean, the worst thing about it was Natsuki, but that doesn't even count since the drama was before I was even a member. "
    mc "And I'm really interested in the discussions for the reading activity. It's kinda cool to see other people's perspectives."
    s "Well in that case, I can't wait to try the poetry activity. "
    s "Not only do we get others' viewpoints, but their inner self as well. How they write, what they write about, it can be so revealing. "
    s "Although I guess that was the reason why the others didn't want to do it."
    "I begin to remember Monika's writing that I found. It did seem quite personal and showed a side to Monika I never expected. Sayori may be on to something about that."
    mc "I mean, I don't mind trying it, it's just my lack of experience with writing. I don't wanna bore you all with some bland writing."
    s "You shouldn't worry about that. You're with friends. At worst, you'll get constructive criticism. Well, maybe Natsuki will call you a noob, but will at least give some pointers."
    mc "Yeah, Natsuki and Yuri seemed afraid that we would be too harsh. Like both felt that they would be judged badly for it."
    s "I get that they're both afraid of opening up too much. It can be scary."
    "Sayori then places her hand on mine, catching my attention with her soft smile."
    s "But sometimes opening up is just what we need, right?"
    "I smile back at her."
    mc "Right. You know, they probably need someone else to open up first. Do you have anything you can share?"
    "Sayori thinks for a while before replying."
    s "Now that I think about it, not really. I have some short stories, but not really any poems. I could probably write one tonight as a demo."
    mc "That may work. We can also see if Monika has any other poems that she's willing to share as well."
    s "Any more?"
    "Crap! I never told Sayori about Monika's song. I don't want to ruin this by admitting I invaded Monika's privacy by taking her personal property home with me. "
    "I don't need any more creep ammo for the club."
    mc "Uh, yeah. The other day I saw her writing what looked like a poem before you all got in."
    s "Oh. Yeah, she would probably be good to ask. I'll text her about it now."
    "We finished shopping and got a decent amount of stuff for the week and with Sayori's help, walking home with the haul was a breeze."
    scene bg kitchen
    "As we return to my home, Sayori assists with putting the food up."
    s "I still can't believe my mom already had a list for you for so many different meals."
    mc "Yeah. She must have been saving them for you."
    s "Huh? Why'd ya say that?"
    mc "Well, she did call them 'Sayori proof' recipes."
    s "What!? But, I didn't..what's that supposed to-"
    mc "The ramen incident?"
    s "I was 8 and hungry!! "
    "I just start laughing at her rebuttal."
    s "I don't find that funny."
    mc "The fire fighters sure found it funny.. "
    "Sayori begins to pout at me."
    s "Well if you're gonna be mean then I should just go home."
    "Just then a loud growl is heard from her stomach." #[Add stomach growl sound bit here]
    s "Or, you can make it up to me by making me dinner."
    mc "Sure you don't wanna redeem yourself in the kitchen?"
    "Sayori squints her eyes at me."
    s "Sure. Where's your microwa-"
    mc "Never mind! You can sit this one out. I got it."
    s "Tee hee..alright! Let me know when it's done-"
    "I shake my head as I look through and pick an easy recipe to start with."
    mc "I guess your mom is a fan of leftovers."
    s "Yup! Two dinners and a lunch is usually the outcome!"
    mc "Hope you like chicken pasta, then."
    "I get the food done and it comes out pretty decent. Looks like I can at least follow a recipe."
    scene bg kitchen
    with dissolve
    s "Thanks [player]! This is delicious!"
    mc "It's the least I can do for all that you've done for me. Actually, speaking of which-"
    "I go to the cabinet and get the Tupperware Sayori's mom had left previously and fill it with some of the pasta."
    mc "Here you go! Share some with your mom as a thank you."
    "Sayori eyes light up."
    s "YEEESSSS..."
    mc "Let me text her so I make sure it reaches her."
    s "Whaaaa?" 
    
    s "You don't think I'd share this delicious meal made by my bestest friend with my own dear, sweet, mother?"
    "I stare at Sayori with a stone face of disbelief before sending the message to her mom."
    s "Meanie..."
    scene bg front_door_night
    "As she gets ready to head home, we share another hug."
    mc "Thank you for today. It's the most fun I've had in a while."
    s "I should be thanking you, silly! You're the one who invited me. Besides, I told you that I'm here when you're ready."
    mc "And you were. You've helped more than you know just by being your fun loving self. And from now on, I'll do my best to be a better friend."
    s "Pinky promise?"
    "I grab Sayori's extended pinky with my own."
    mc "Pinky promise. I won't leave you hanging again."
    "Sayori leaves the house and I lock the door behind her. "
    "I look at the clock and see it's still early. "
    "Hmm. I really don't want to waste my day of relaxing with school work, but I also feel a bit better and don't want to fall back into my lazy streak. "
    "I know, I'll read some more of the club book. I grab my copy out of my bag and read a few chapters."
    scene bg bedroom
    "I'm down to the last few chapters and can probably finish the rest in the club tomorrow. I put the book up and get ready for bed. "
    "As I lay there, I can't help thinking about how wonderful of not only a friend, but a person Sayori is. "
    "I'm so grateful to have her in my life and surprised she's still willing to stay around even after I basically ignored her. "
    "But I'm making steps to be better."
    " I fall asleep in high spirits, excited for tomorrow."

    return