label act1_day15:
    "Tuesday"
    scene bg class_day
    "As I enter the classroom, I'm immediately called on."
    a "[player]. Do you have something for me?"
    "I pat my pockets and shrug my shoulders."
    mc "Sorry, I'm a little short from the festival."
    a "I take it you spent every cent trying to win something for that young lady the other day, huh."
    mc "Heh, I'm...just joking. I got the road map right here."
    "I hand over the paper and Mr. Agawa quickly looks over it."
    a "Hmm. At first glance, I'd say good job. I have an important meeting after classes today, so I can go over it with you more tomorrow."
    mc "Sure thing."
    "As I sit down and classes begin, I start noticing how much freer I feel. "
    "I don't know if it's the relief of the projects no longer looming over me or what, but I feel relaxed. "
    "I'm quite excited for club today. "
    "While Sayori was trying her best to be tightlipped on the way to school, it was obvious that they were planning a new club activity. "
    "I mean, with the emotions this one brought out for everyone, I doubt Natsuki and Yuri would have issues with anything else. "
    "Who knows, maybe it will be something that pairs me with Monika!"
    "Huh...The thought of that seemed to excite me more than I thought. I mean, being with any of the others wouldn't be bad but...huh..."
    "While I drift off, my mind focuses on the chalkboard. Heh. That Y kinda reminds me of Monika's bow."
    "...Wait. What?"
    "Some of the ambience from outside begins to catch my attention and I hear the chirps of birds. "
    "Huh. That kinda sounds like Monika's song. It could probably fit somewhere in there. I should probably remember that and see if she can use it."
    a "Okay. We're gonna cut this lecture early due to my meeting. "
    a "You all have the next 15 minutes free. I hope you all spend this time getting a head start on your workbook."
    "As Mr. Agawa leaves the room I sit and think about what he said."
    " I've been doing good and nothing seems too bad. I can probably get a chapter of Portrait of Markov. "
    "As I pull the book out, I think about how happy Yuri would be to talk about this with me. "
    "Maybe we should get the others to read it too. "
    "Ehh...now that I think about it, Sayori and Natsuki may not be into it as much. "
    "Oh well, just the three of us should be good. "
    "Me, Yuri, and Monika. But then again, Yuri will be quite anxious not to spoil."
    "I don't know Monika's position on spoilers, so it may just be better if it was just me and Monika. Yeah. That sounds good. "
    "Just me..and Monika..."
    "Crap! I gotta get her outta my mind! I should probably avoid anything to do with the club for now to keep those thoughts at bay. "
    "I guess I should try to get some of my economics homework done. I pull out my book and begin to read..."
    "...in this example we will use the company Common,  Inc. A single month of revenue-"
    "Wait."
    "Common Inc. A..."
    "Com..mon...Inc....a..."
    "Mon...Inc...a..."
    "....."
    "Okay. Even I have to admit that was a stretch. "
    "Why can't I get her off my mind? "
    "I guess I have spent more time with her these past two days than anyone else. "
    "And those times brought up some emotions I haven't really felt in a while. "
    "If I think about it, she has been there for some of my lowest and highest ones over the past week."
    "Stop! It's not like she was the only one! "
    "Sayori has been by my side since before anything happened. "
    "With that said, it feels different. Sayori is practically family. But Monika is...she's..."
    "*RIIINGGG*" # [School Bell Ring]"
    "Well, let's just see how I can handle club now. "
    "While my excitement is still there, I'm also starting to get a bit more nervous. Haven't really felt anything like this since Elsea."
    " ..."
    "And that's it, isn't it. I think...I might actually like Monika...romantically. "
    "Great. Just when I was getting things off my plate."
    scene bg corridor
    "As I approach the clubroom, I see Natsuki and Yuri standing outside the closed door."
    mc "Hey, what's going on? Is the door locked or something?"
    n " Sayori stopped us before we got in saying they had to talk to faculty about something. There's a teacher in there with her and Monika right now."
    mc "Do you think it's something bad?"
    y "I can not perceive any reason to believe so."
    n " You don't think they'll cancel the club cus we cut out early, will they?"
    mc "I hope not."
    y "It is not like the room was empty. I was here the entire duration of the festival. Though, the lack of follow up from other students may be a factor..."
    "As we sit in silence and suspense, we can faintly hear the others in the room."
    s "Okay, I'll get them now."
    "As the doors open her bright face grows one of concern."
    s "Woah, guys. What's wrong?"
    n " Why are you asking us? You're the one with the inside knowledge."
    s "Oh! That's Right! We've got great news! Come on in!"
    scene bg club_day
    "As we walk into the club we see Monika sitting filling out some paperwork and-"
    mc "Mr. Agawa?!"
    a "Surprised huh."
    mc "Wait, what's going on? Is there something I did wrong?"
    m "Don't worry [player], this is a good thing."
    a "Well, let me introduce myself. My name is Mr. Agawa, and I will be your faculty advisor."
    n " Faculty advisor? What's this mean?"
    mc "Don't tell me you're gonna be in the club meetings as well."
    a "Oh, god no! While I can respect literature, it's honestly not my forte. "
    a "But, after speaking with Ms Monika the other day after the festival, I resonated with her reasonings for this club and figured I can at least throw my name behind it. "
    a "I'll basically be a silent partner. Only here if you need special permission for events."
    m "Thank you again, Mr. Agawa. I can't thank you enough."
    a "It's my pleasure. Well, now that that's all handled, [player]?"
    mc "Y...yeah?"
    "Mr. Agawa looks at the girls and back to me."
    a "Mmmmhmm."
    "He then walks out the door. "
    "What the hell was that about?"
    n " So it's cool we got a faculty...whatever, but was that really necessary to keep us out of the club room?"
    "Monika then begins clicking away on her computer."
    m "Actually, I wanted to save this little surprise for you all. I got a sneak peak of the school social media posts, and take a look at what's going to be up tomorrow."
    "She turns her laptop around to us and it's a ranking of the festival events based on size. At the top of the 10 numbers and under list, the Literature club is number 1."
    y "Why that is fantastic!"
    n " I guess the students here know talent when they see it."
    s "I'm so proud of us all!!!"
    m "I am too, Sayori. And none of this would have been possible without all of you."
    "Monika stares at me when saying that as Sayori begins to nudge me on my side. In this moment, I can't help but smile and sigh in relief."
    "For the rest of the club, we were left for a bit of free time to do whatever. "
    "We all kinda floated along towards each other. "
    "One moment I'm discussing manga with Natsuki, the next I'm reading a bit of Sayori's latest story. "
    "I ask Yuri about her current reads and give her my thoughts on Portrait of Markov. "
    "But throughout all those activities, I find myself constantly glancing back at Monika. "
    "And as she glances back, the usual eye shift is replaced with a warm smile."
    m "Okay, everyone! It's time to pack up. I've got a couple ideas for our next activity, but I want your suggestions first. You all can think it over and we can discuss tomorrow."
    #"[Time Skip to End of Club]"
    "As we leave, I take a detour to the front to talk to Monika."
    mc "Hey."
    m "Hey."
    mc "So, uhh...Mr. Agawa?"
    m "Yeah. I ran into him while helping the student council yesterday. "
    m "He recognized me from when I was with you. You seemed to put quite an impression on him."
    mc "I...hope it wasn't a negative one."
    m "Heehee, no. It's the same one I've always seen from you: Great potential, just a little bit caught up in your head to realize it."
    mc "Well, thanks for that. And Thank you for everything you've done for me. I was on a self-destructive path, but...you saved me. "
    mc "From my sorrow, from my aimlessness, from..."
    mc "myself."
    "I then feel a pat on my back. As I look to my side I see Natsuki standing there."
    n " You're a good guy, man. Even when you don't have your own back, we got you."
    "I then feel a hand on my shoulder. I turn to see Yuri lightly smiling."
    y "With the assistance you have provided us, it would be shameful not to return the sentiment."
    "I am then bombarded with a large weight on my back, only to find Sayori wrapping her arms around my neck."
    s "You've got friends for life here. Thick or thin, you can count on us."
    "My hands are then grabbed by Monika."
    m "Always. And forever."
    "As I think back over all that I've gone through, everything they've helped me with, I can't help but feel joy in knowing that I have friends like these. "
    "I hope we can stay like this for as long as possible."
    "END OF ACT 1"
    return