label act1_day2:
    "Day 2: Tuesday"
    show bg black
    #[Dream Sequence] [This sequence will be coded with sprites and background images. Maybe a CG]

    "Just another day with Elsea"
    show bg black
    "We're walking down the street, hand in hand as she is walking ahead of me with me staring in the back of her head"

    "As she turns a corner, I try to turn with her, but I suddenly trip and begin to fall."
    "As I'm falling, her grip loosens."
    "As I fall, I land on something soft and sticky..."
    "A...cinnamon bun?"
    "I look around for Elsea and see her hand reaching out to me."
    "As I grab it, a white ribbon begins to wrap around my arm."
    e "[player]! [player]! [player]!!!!"
    "The ribbon begins to unfurl and the cinnamon bun becomes hard and stiff."
    "I'm tossed away in a random direction and then I'm face to face with Elsea, but she's not the same."
    "Her face is contorted and her eyes are blank."
    e "YOU ARE MINE!!! NO ONE ELSE'S!! WITHOUT ME YOU ARE NOTHING!!"
    "I try to fight away and as soon as she releases me, I begin to fall in a deep pit."
    "I can still hear her as I fall..."
    e "MINE!! MINE!! MINE!!"
    play sound "mod_assets/sfx/alarm_clock.ogg" loop
    "*BEEP* *BEEP* *BEEP*"
    
    scene bg living_room_morning
    "I jolt awake and grab my phone to turn off the alarm."
    stop sound
    mc "Wow. 3 percent battery. It barely made it."
    "As I plug it up to the charger, I think about the weird dream and what it could mean..."
    "Until I see the empty jar of peanut butter on the floor."
    mc "Note to self: a stomach full of peanut butter will give some screwed up dreams."
    "I struggle to get off the couch, but pull myself together to run a quick shower and put on my spare uniform. "
    "With just enough time, I try to get some cereal, but half way through I begin to realize how unenjoyable it is."
    "Guess I grew out of the sugary stuff."
    "I drain the milk and toss the rest out as I grab my phone and head out the door."
    "48 percent. Will that be enough?"
    "I then remember the main use of my phone was either talking to Elsea or watching things that remind me of Elsea."
    mc "Maybe we just needed a break from each other. It might not be fully over..."
    "As I scroll through my messages, I realize how short the list of contacts really is."
    "And the turmoil of the last few messages I had with her."
    "I put my phone in my pocket and head out the door."
    scene bg house
    "As I step outside and lock my door, I hear my neighbor's door open and close quite quickly."
    "I glance over and see that there's no one there."
    mc "Sayori?"
    "I stand to watch for a bit to see if it opens again."
    "If it was her, what would I even say?"
    " 'Hey! Now that I don't have a girlfriend, why don't you stay around to keep me from being lonely' "
    "Pfft."
    "This is probably how she felt."
    "I'm such a moron."
    scene bg residential_day
    "As I slowly walk staring at her house, a group of students pass me, whispering to eachother"
    $ st1_name = "Student 1"
    $ st2_name = "Student 2"
    $ st3_name = "Student 3"

    st1 "What's his problem? Is he trying to perv on some other girl now?"
    st2 "Maybe he's begging that stupid airhead for attention."
    st3 "how pathetic. No wonder Elsea dropped him."
    "I stand there clenching my fists in anger."
    "They know I can hear them. They just don't care."
    "As tears start to well up, I fight them back and turn around."
    "Screw it. Everyone else gave up on me. Might as well join them"
    scene bg bedroom
    "I've just been sitting in my bed with the tv on."
    "I'm not even watching it at this point, but I can't stand the silence with my thoughts"
    "*RIING RIING RIING*"  ##[Phone ring sound bit]
    "My phone keeps going off. Elsea probably passed my number out and her friends are spamming me."
    "I don't even look at my phone as I randomly tap to answer. It's not like those morons can come up with anything clever"
    mc "What is it?"
    qu "What do you think you are doing??"
    "My heart drops"
    mc "...w..what?"
    "I look at the caller ID."
    "All the calls were from either mom or dad."
    $ mom_name = "Mom"
    mom "You heard what I said. Why are you not in school? We just got a call that you never showed up for your homeroom! And what's this about falling asleep in class?"
    mc "...."
    mom "Well? Are you gonna say something or just sit there being silent?"
    "All the frustration begins to well up and I start choking on my words."
    mc "..I, I just can't...keep..."
    mom "You are too old to be trying to pull this crap. Do you really think you and Elsea will have any sort of future if you keep acting like this? Get to school! NOW!"
    mc "You...don't know-"
    mom "Know what?"
    mc "...of course you don't. That would require you to be here."
    mom "...WHAT?? WHO DO YOU THINK YOU-"
    "I hang up the phone and shut it off as the tears roll down my eyes."
    "What the hell!??"
    "Why can't the world just leave me alone!!??"
    "After a few minutes I hear a knock on the front door."
    "I try to ignore it, but it gets louder and louder"
    scene bg front_door_morning
    "I look through the peephole and see that it's Sayori's mom with a stern look on her face."
    sm "[player]! I know you're in there. Your parents called me to get you. I don't know what you did or what you said to them, but I suggest getting to school now."
    "Really?? I can't even find peace at home?"
    "How can they ruin my life without even being in it?!"
    sm "[player]? This is your last chance. I've been nice so far, but I will come in if I need to. I'm fully aware of the key on the door frame"
    "DAMMIT!!"
    "I've got no safe haven at all do I?"
    "Any privacy or agency I even THINK I have is just a joke."
    "Screw it."
    mc "F..FINE!! Gimme 5 minutes to get dressed."
    sm "Okay."
    sm "I'll be pulling around up front to give you a ride. If you're not out there by 10:47, I will come in without warning and drag you out myself."
    "How the hell does she sound so calm while being so threatening."
    "I put my uniform back on and head out to get in the car..."
    " "
    scene bg class_day
    "This day has been utter hell."
    "The drive here with Sayori's mom couldn't have been more awkward."
    "The silence was unbearable, but the small bit of talking was like daggers."
    "It hurts that this was the most we've talked in years."
    "Even more interaction than I had with Sayor."
    "Geez. Another relationship ruined. What a streak."
    "The bell interrupts my self loathing, but my exit is cut short before I even stand up."
    $ a_name = "Mr. Agawa"
    a "[player]. Can you please stay for a moment?"
    "I stare at him dumbfounded and then look down."
    "I hear the whispers of the others as they leave."
    "As soon as the room is empty, I make my way to his desk."
    "#just a joke if you want to add it#"
    "He looks at me"
    "And I look at him"
    "And he looks at me"
    "And I look at him"
    "And he looks at me"
    "And I look at him"
    "(It's fine I just don't feel it matches the tone of what's happened so far)"
    a "I'm pretty sure you know what this is about."
    "I just look away from him with my head down."
    a "Your grades weren't always the best, but the past few weeks, they have been slipping drastically."
    a "At this rate, you're on course to fail this semester if you don't shape up."
    mc "Yeah. Okay."
    a "Now I know you don't want to hear this, but I know about your recent...social adjustment."
    "As I hear that my anger begins to show."
    "So my personal life is public knowledge now?"
    a "Before you get ahead of yourself, I don't think your other teachers know. And between us, I doubt any of them care."
    "He stands up to walk over to me and puts his hand on my shoulder"
    a "It's alright. These things happen. Yes. It will hurt. And you will feel like the lowest of the low. And every time you even think of her name your heart will-"
    mc "Is there a point to this!?"
    "Mr. Agawa smiles slyly"
    a "If I put the nail on the head, it's only from experience."
    a "Look, you have potential. I can see it in your work, when you turn it in that is."
    "I slowly look up and meet his eyes"
    a "The thing you need is direction and opportunity."
    a "While I can only give advice on the first, the latter is something I can provide."
    a "I was able to speak with your other teachers. They agreed to let you catch up on all of your incomplete assignments for 75 percent credit under 3 conditions:"
    a "1. You have to turn in everything by the festival. And that's everything. All or nothing."
    a "2. You have to keep up with your current work as well. One late assignment and it's all over."
    a "3. Since you have yet to fill out your exit survey for your post school roadmap, you will need to fill that out."
    "At least the last one should be easy. I'll just put college and call it a day"
    a "And since this is also late, we will want to see more than just university for general studies." 
    a "It will need to be an ACTUAL profession post college. This includes at least yearly goals and landmarks."
    mc "What the heck? That's not fair! You want me to plan out my life while buried in homework in 2 weeks?"
    a "Consider it a sleep tax for my class"
    a "Besides, you should already have SOMETHING in mind by now. Even if it's something simple. You should be able to make choices on your own if you're going to be an adult."
    "I sign and look down."
    "Mr. Agawa grabs both of my shoulders and looks straight at me."
    a "I wouldn't do this if I thought you were a lost cause. You just need a push to realize you are enough on your own. Got it?"
    mc "Yeah... got it."
    a "Good. Now head home and try and think over today. Oh, and a few assignments here and there won't hurt."
    "I grab the stack of papers and put them in my bag as I head out the classroom."
    "This is so unfair."
    scene bg school_hall_2
    "Great. Double the work AND a stupid roadmap crap or else I'm stuck in this hell hole for another year."
    "..."
    "I mean, at least there's an out. Maybe this can help take my mind off-"
    "I stop in my tracks as I hear a familiar voice."
    "Elsea..."
    "And she..."
    "Sounds happy..."
    "Crap!"
    "My autopilot brain brought me straight to the art club!"
    "I turn around to go to another exit when-"
    show natsuki turned ldown rdown pani om ce at t11
    qu "AHH!!"
    show natsuki cm ce
    "I bump into someone small, knocking the book out of their hand. And they fall on the floor."
    show natsuki turned angr cm oe
    mc "AH! Sorry, I didn't see you."
    "I immediately bend down and grab the book on the ground."
    "It's a pink covered manga book with cutesy girls in dramatic poses on the cover."
    show natsuki oe om
    qu "Geez, dude! Watch where you're go-"
    show natsuki turned lsur oe cm
    "As she looks up, I notice it was the same girl who was getting bullied yesterday."
    "My face goes pale with the realization while she gets red with anger and embarrassment"
    show natsuki turned vang om ce
    qu "Of course you didn't see me, you prick!"
    qu "Not like you care about anyone but yourself, right?"
    "She snatches her book out of my hand"
    show natsuki ce om
    qu "Don't touch! Your grubby hands are gonna ruin the quality!"
    mc "...I...I'm So-"
    show natsuki cross fs neut b2 e4
    qu "Save it!"
    "She turns around and stomps off."
    hide natsuki
    "Great."
    "Another eggshell to walk on."
    scene bg residential_day
    "Finally, this day is almost over"
    "Wait, no it's not. I've got a pile of homework to chop through."
    "*grurgg*" #[Add stomach growl sound bit]
    "I should probably eat something other than peanut butter tonight as well"
    "Hopefully I can at least make myself som-"
    play sound closet_open
    "*CREEK*" #[Add door creek sound bit]
    "What the hell?"
    "I stop in place to listen as I hear something near Sayori's house."
    "Chances are, her mom is gonna be on me now."
    "Wonderful."
    "I take a look, and I swear I see the blinds closing quickly."
    "I hurry into my house and lock the door after grabbing the spare from the doorsill."
    scene bg living_room_afternoon
    "I plop down on the couch, drained of motivation."
    "How could one person just leaving ruin my entire life this deeply?"
    "Now every adult in my life is on my ass."
    "And I have no one to talk to."
    "I pull my phone out realizing I've had it off the entire time."
    "24 missed calls."
    "41 texts"
    "The more of the texts I read the deeper my heart sinks."
    "I don't think I'll ever be free."
    "As I'm about to give up, I hear a knock on the door."
    "I wait to see if anyone says anything."
    "After about a minute I go to the door and look through the peephole."
    scene bg front_door_night
    "No one's there."
    "Wait, is something on the floor?"
    "I creak open the door and look to see.."
    "A tupperware container?"
    "I pick it up and it's full of pot roast and mashed potatoes."
    "It smells delicious."
    scene bg kitchen
    "I finish off the entire container in about 10 minutes."
    "Either this was the greatest food ever made or I was significantly hungrier than I thought."
    "..."
    "It's been so long since I had Sayori's mom's cooking."
    "She didn't deserve how I treated her today."
    "Same for Sayori these past two years."
    "As I let my food settle, I begin to feel the void of loneliness again."
    mc "Let me try and make a dent in this homework."
    scene bg bedroom
    "I head upstairs and begin to work on my homework."
    "I'm able to get my current assignments done and start working on the backlog."
    "My phone notification goes off and I see one new message from Dad."
    d "Sayori's mom told us about Elsea. Sorry to hear about that kiddo. "
    d "I understand your wounds are still fresh and this is a big change, so I was able to talk to your mother to give a bit of leniency from what happened this morning, but that doesn't excuse you from responsibilities. "
    d "You're almost an adult. You won't be able to run away from your problems. Focus on your school right now so you don't ruin your future. "
    d "We're here if you need to talk. "
    d "Love you."
    "Ruin my future..."
    "I look at my exit survey assignment realizing I have to come to grips that my future won't have her in it."
    "Without her, do I even have a future?"
    "As I mull these thoughts over, the fatigue sets in."
    "I finish up the last problem set and get ready for bed."
    "At least tomorrow can't be worse."
    scene bg black

    return
