
label act1_day14:
    scene bg black
    "Festival Day"
    scene bg club_day2
    s "[player], where have you been? The performance is about to start!"
    mc "Sorry, I don't know what happened."
    n "Did you bring the cupcakes?"
    mc "Wait, I didn't bring them?"
    y "Do you have your poem?"
    mc "Wait..it's..somewhere..."
    m "You're going to ruin this for the club!"
    mc "I'm trying my best!"
    dokis "Don't let us down!"
    dokis "Don't let us down!"
    dokis "Don't let-"
    scene bg bedroom
    "My eyes shoot open. "
    "I grab my phone and check the time. "
    "5:57. "
    "No sense in trying to go back to sleep for 3 minutes. I roll out of bed and get ready."
    scene bg kitchen
    "I was able to get ready relatively quickly this morning. "
    "Can't tell if it's the anxiety of the event or the excitement of the festival, but I'm wired this morning. "
    "I pull out my phone to give her a call to make sure she's up."
    "*Riing riing* [Phone Ringing Calling Sound]"
    s "H-hello?"
    "Great. She sounds like she just woke up."
    mc "Hey Sayori. Just reminding you to help carry the cupcakes. If you can get up and over here, I'll have a surprise for you."
    s "Mmmm..cupcakes...uhhh...be there in a sec."
    "I hang up and continue making breakfast burritos for myself and Sayori hoping a full tummy keeps her mouth at bay."
    scene bg kitchen
    with dissolve
    "*DING DONG*" #[Doorbell Ring]"
    scene bg front_door_morning
    "The door rings as I'm finishing my burrito."
    "I open the door to find a slightly lethargic Sayori with her eyes half open."
    s "Sayori report for cupcake duty."
    mc "At ease, soldier. Before we move out, you better fuel up. Don't want any casualties on our mission."
    "I hold the burrito out towards her as she sniffs it."
    s "Mmmmm...burrito..."
    "She grabs it and begins gnawing at it like a feral animal."
    mc "I forgot how...cute you are when you eat those."
    s "hmfp...meanie..."
    mc "Yeah, talking with a full mouth ain't helping."
    s "Stop iiit! It's too early for this!"
    mc "Fine, I'll stop. Finish up so we can get a move on."
    scene bg kitchen
    with dissolve
    mc "Alright. I'll take these two and you take those two. "
    mc "Do NOT try to even sneak a peek! Don't forget. The penalty is DEATH."
    s "I mean, YOUR death..."
    mc "Sayori, I WILL haunt you."
    s "Fine..."
    scene bg school
    "As we arrive, we see the other students are already working on the booths in the courtyard area. "
    "From what I can tell, it looks like mainly the sports clubs hosting outside with a few classes setting up food booths. "
    "I look back at Sayori and can see she's already planning her path when we're done."
    s "[player]!! LOOK! Funnel cake..."
    mc "Don't get too distracted, we still got to finish our setup."
    s "Right!"
    scene bg club_day
    "We walk into the clubroom to see everyone else already there setting up decorations. "
    "Natsuki and Monika are placing table covers and battery operated candles on each of the desks while Yuri is adding some streamers on a blackboard near the front."
    n "Geez! Even when you're early you're late!"
    s "Sorry! I was so excited for today that I couldn't sleep! Then I uhh...didn't wanna wake up...heh heh."
    m "Don't let Natsuki get at you, Sayori. She only showed up 5 minutes ago."
    mc "And here I thought you were waiting for hours."
    n "I was just worried about the cupcakes! Speaking of which, bring them over here."
    "Natsuki guides us to a folding table draped with a cloth to place the cupcakes. She then opens each box inspecting the cupcakes."
    n "Not one missing or out of place. I guess you take your life seriously, [player]."
    mc "Glad to no longer be a joke in your eyes."
    n "Let's not get ahead of ourselves."
    "Natsuki grabs a stack of small paper plates and proceeds to place cupcakes on them while Sayori helps Monika place pamphlets on the tables. "
    "I look around to see what else is needed and see Yuri beginning to put up a banner."
    mc "Do you need help with that, Yuri?"
    y "Huh? Oh. It is fine. I should be able to-"
    "Yuri begins to struggle with taping the banner due to the weight of it. "
    "I grab the other end and walk over to spread it out allowing her to properly apply the tape. She then walks over to hand me the tap."
    y "T-thank you."
    mc "No problem."
    y "Also, I apologize on behalf of my mother. She can be quite...a character."
    mc "It's...fine. I should probably be used to it by now."
    y "Huh? What do you mean?"
    mc "N-nothing. It's alright. Is there anything else you need help with?"
    scene bg club_festival
    with wipeleft
    "As we are finishing the decorations, Monika calls us over."
    m "Okay, everyone! Well, today's the day. It's been a challenge , but you all have worked so hard to make this event come together. "
    m "The place looks great and I have absolute faith in your performances. We're scheduled to start in about half an hour, so for now, Sayori and I will be passing out handouts to promote the event more. "
    m "We will want to be as friendly as possible, so don't be afraid to answer any questions anyone may have or strike up a conversation with anyone who comes in. "
    m "Alright, are we all ready for this?"
    s "You can count on me!"
    y "I will do my best to be an exemplary representative of our club. As long as..."
    y "Uuuuuu...."
    n "As long as they're not a jerk, then we're good."
    m "Geez, you two...how about you [player]?"
    mc "Back up Yuri, Muzzle Natsuki. Got it."
    n "You'll do what to Natsuki?"
    m "Please be civil. I'm hoping I can trust you all without a chaperone."
    n "We're fine! Just go. Get some butts in seats."
    m "Alright, see you all soon."
    s "This is so exciting, I can't wait!"
    "They both leave the clubroom as the rest of us look over our poems. "
    "As I'm rereading mine, I must have been mouthing it out loud because Natsuki chimes in."
    n "You chose that one, huh?"
    mc "Y-yeah."
    n "Too bad. I like the one you performed for us before."
    mc "Well, too late now."
    n "Mind if I ask something about that one?"
    mc "Yeah. Sure"
    n "Who or what was your sunshine?"
    mc "Uhh...kinda, all of you. And...the club I guess."
    n "Aww, you sappy little suck up."
    "She elbows me slightly."
    "As the time goes by, students begin filling up the classroom. "
    "Some take a look at the decorations and others flock straight to the cupcakes. "
    "One student grabs a cupcake and proceeds to leave the room. This prompted Natsuki to cut her eyes on them."
    n "Greedy fricking jerk..."
    mc "It's okay. There's still plenty of people staying."
    "I lean in to whisper to her."
    mc "Plus, I recognize that guy from the baseball team. Pretty sure they had some sort of dunk tank." 
    mc "How good is your pitching arm?"
    "Natsuki smirks."
    n "Good enough to look bad."
    "We fist bump and continue to greet the people who came in. At least the ones that acknowledged our existence. "
    "I glance at Yuri and can't help but notice that may be a good thing as she seems frozen solid."
    " I guess the crowd is getting to her already. Wait...is she even breathing?"
    "...."
    "...."
    m "Okay, everyone!"
    y "*Exhale*."
    "Oh thank God!"
    m "As many of you know, My name is Monika and-"
    "The crowd roars with applause with a few guys whistling at her. She smiles at the applause while signaling them to wrap it up."
    m "And I am the president of the Literature Club! "
    "With me are my vice president Sayori, and our esteemed members: Yuri, Natsuki, and [player]. "
    "Here we engage in different forms of literary expression. "
    "To represent what we are all about, we will be performing poetry for you all. "
    "After our performance, we will be available to discuss our other activities and even take requests. "
    "Here, we have fostered a safe space of encouragement and belonging and we are glad to have so many guests, so feel free to stick around. "
    "So without further ado, I will present my poem."
    "There is a light applause before Monika begins. "
    "As always, her performance captures the attention of all in the room. "
    "The confidence and emotion presented leaves me in awe as I focus on every syllable punctuated perfectly. "
    "I'm broken out of my trance by the applause filling the room and Monika bowing."
    m "Thank you, thank you. Up next, please give a round of applause to Sayori."
    "A modest applause comes from the crowd as Sayori prepares herself."
    s "*Exhale* Showtime!"
    "As she gets to the front of the room, there's a bit of chatter, but it's silenced as she clears her throat."
    s "Hello! As Monika said, I am Sayori. I hope you enjoy my poem."
    "As she begins, I look amongst the crowd to gauge a reaction. "
    "Unfortunately, quite a few people are on their phones not really paying attention."
    "A few people in the back get up and leave. I glance at Sayori, hoping she doesn't take it too hard, but she begins to gain confidence in her performance. "
    "Her emotions are more pronounced, enhanced even more by her movements to the point where it's almost an interpretative dance. "
    "As she finishes, a few others are peeking through the room and coming in for the show."
    "As she finishes, she gives a courtesy and the crowd begins to applaud."
    "She sits back down with the rest of us as Monika goes up front."
    mc "Great job, Sayori!"
    s "Thanks! I just hope I was entertaining enough. I noticed a few weren't really paying attention. But I'm glad for the ones that did. And that's all that matters!"
    m "-and as a courtesy, please keep your phones down while we are performing. Now, next up to perform is our own Natsuki. Come on up!"
    n "Guhhh...let's get this over with..."
    "She struts up to the front and introduces herself bluntly."
    n "I'm Natsuki. This is my poem. Enjoy."
    "She begins to recite her poem with an extremely dry delivery that you can tell she doesn't want to be up there. "
    "I glance at Monika and Sayori and Monika has her face in her palm while Sayori..."
    "Wait. I know that look. She's plotting something. What could it-"
    "*BANG TAP BANG BANG BANG TAP*"
    "Sayori starts slowly beating the desk to Natsuki's poem. "
    "As Natsuki glances over, Sayori gives a wink and Natsuki nods. "
    "Her energy changes as she continues, emphasizing the bounce in her words. "
    "The crowd begins to get into it as well with a few people clapping in with the beat. "
    "She even gained a hype man throwing in ad-libs after every other line. "
    "By the time she finishes, everyone loudly applauds her performance. As she trots back to her seat, she gives Sayori a high five."
    m "Thank you Natsuki for such a lively performance. Up next, please welcome Yuri."
    "As the crowd applauds, Yuri is still sitting, staring forward completely frozen. "
    "Natsuki nudges her to get her attention and she slowly walks up. As she's passing me I whisper to her."
    mc "Psst. Remember. Don't look at the crowd, just read."
    "Yuri looks back at me and slowly nods her head. "
    "While up there she stands silent, causing it to spread throughout the room. "
    "The silence is followed by a ruffle of papers as she buries her face into her pages."
    "She then starts to read without any introduction. "
    "As she begins to read, she is almost shouting as if she's still aware of the crowd and its size. "
    "As she's reading, her voice begins to calm down as her paper slowly lowers. "
    "The further through her poem, the more comfortable she gets as her performance becomes more profound. "
    "She then closes her eyes, reciting it by memory. "
    "Her word choice is emphasized by her angelic voice to the point where she is no longer performing for us, but giving an audio description of her emotions so crystal clear that the entire room fully understands. "
    "As she finishes, she slowly opens her eyes and her nervous demeanor returns as the crowd looks on in silence and awe. "
    "The silence is broken by Monika's applause, which is soon followed by the entire room. "
    "From the sounds of the whistles, Yuri gained a few fans. "
    "She quickly bows and trots back to her seat, completely red in the face and breathing heavily."
    n "Woah, girl! Didn't know you had it in you!"
    y "Yes...it was quite...exhilarating...in a way.."
    m "Wow, we all felt that, didn't we? Now, last but not least, our final club member and performer, [player]!"
    "Okay. You got this"
    "I stand up and walk to the front, Monika whispers as she passes me."
    m "You've got this. I believe in you."
    "I nod as I reach the front."
    mc "Hello, everyone. My name is [player] and this is my-"
    qu "*cough* simp *cough*"
    "[player]:...m-my poem. Ah hem.."
    "As I start to perform, I decide to take the advice I gave to Yuri and focus on reading the page. As I'm going through-"
    qu "*cough* Pussy *cough* wuss*"
    "A small group begins laughing in the crowd. I look up at the group and can see the culprit. "
    "Kenji. "
    "As I'm about to say something, Monika swiftly comes to the front."
    m "Sorry to interrupt [player], but if there's someone in the crowd who wants to come up and perform, we should give them the chance."
    "The room is quiet as Kenji starts to slink down with a sly smile."
    mc "It's okay KENJI! If you want the stage, feel free!"
    "As people turn and look towards him, he begins to get flustered."
    k "W-what are you talkin- screw this lame crap."
    "He gets up in a hurry and walks out."
    m "Sorry for that interruption. Please, start over [player]."
    "I nod and begin again. It's a bit easier knowing that she and the others have my back. And the crowd seems so receptive now. As I look at them I can tell-"
    "...."
    "Her..."
    "She's here."
    "...Elsea"
    "I pause as I notice. Has...she been here the whole time?"
    "As I stand there frozen, I start to hear the murmurs. I apologize and begin to try and read again."
    "I focus on the words on the page. But I keep realizing the fact that she is hearing this. "
    "This was my heart and soul. I'm bearing it all out."
    "In front of her. She now knows my mind state. Does she...feel the same? Don't want to but..."
    "I glance up and can see her giggling while another girl is whispering to her. "
    "What? "
    "What's so funny? "
    "What are they saying?"
    " Did I mess up? "
    "No. "
    "No no no no."
    " I, what am I even saying. "
    "I stumble over the last few lines. "
    "I look back at my paper and start over from where I fell off, apologizing. "
    "I continue to read, but the sound of my heart beat is in my ears and the words on the page are jagged due to my shaking hands. "
    "While I focus on the words, the sound of footsteps steals my attention as I continue to stumble."
    "I look back where she was to find an empty seat as the back of her head catches my eye through the door as it closes. "
    "That's it. She didn't care. "
    "As I stand still and notice all the eyes on me and whispers all around.  "
    "I look towards the side and see Monika. She is clutching her hands near her chest as I read her lips mouthing you've got this. "
    "I take a deep breath, look back at my page and finish my last lines. "
    "As I return to my seat to lackluster applause, I can't help but feel like a failure. "
    "I sit down with my face in my hands trying to drown out the embarrassment."
    m "Thank you all for your attention. I hope this sparked an interest in literature amongst you. "
    m "If so, feel free to talk to me or Sayori about becoming members. Have a wonderful festival everyone!"
    "As I hear everyone walk out, I stay frozen and reclusive. "
    "I can hear the others trying to talk to me, but it's drowned out by the thought of Elsea. "
    "She was laughing. She just walked out. She...didn't care..."
    "I feel someone's hands on my shoulders, but before I can look up to see who it was, I push them away and rush out the door. "
    "The only thing I can hear is the muffled sounds of my name being called."
    scene bg roof_corner 
    "In my blind rush, I find myself on the roof. "
    "As I approach the fence, I fight the urge to scream my lungs out. "
    "Looking over the edge, I can see the festival going on. All those happy people. "
    "I swallow the urge and grunt as I bury my face in the chains of the fence."
    "I've already ruined my club's event with my stupid emotions. I don't need to ruin everyone else's."
    mc "You fucking screwup. Ruined everything. Why try? It's...no..."
    "As I begin to tear up, I hear the door open. I stay silent and continue to look forward. As the footsteps come closer, I'm expecting a teacher to intervene."
    m "[player]? It's...okay"
    "The fact that it's her seems to sting even more. The work she's put in, the faith she had in me, the encouragement."
    "And I just stood there and wasted it"
    mc "No...it's not. I'm sorry for being a failure."
    m "You are not a failure, you were-"
    mc "The only one that couldn't get through their poem. Yuri was scared stiff yet she gave it her all. Me? I crumble at the first sight of..."
    m "I...was hoping you wouldn't see her when performing. If I had known, I would have-"
    mc "It's not on you. It's me. "
    mc "It's always me. I have...so far to go."
    "I feel Monika's hand on my shoulder. I turn around and see that her eyes are almost as teary as mine. I try to force a smile towards her."
    mc "I am sooo sorry...I-I-"
    "She places her hand on my cheek to wipe my tears."
    m "You have nothing to apologize for. Your emotions are valid and more important than a silly little festival."
    "I break down and hug her. It catches her off guard, but she soon returns the gesture."
    mc "Thank you, Monika. Thank you for your kindness, your patience, your understanding...just..."
    "I begin to reflect on all of our interactions. At no point have I felt that she was doing anything out of pity, but of pure concern and care. "
    "I take a deep breath as I pull away and stare her into her eyes."
    mc "Thank you for being a genuine friend."
    m "It's...the least I could do...seeing what you've done. You've helped me in ways you couldn't imagine. "
    m "I just wish I could have done more to make this easier for you."
    mc "Being here with me is more than enough."
    "Monika begins to blush at that statement."
    mc "I...just wished I could have done better."
    m "It's okay, trust me. I'll admit, it was a bit shaky, but if anything, it played to the strength of your poem. "
    m "You showed your emotions through the words and the performance."
    mc "...Yeah..."
    m "Hey. It's one thing to write your emotions down and share it on paper. It's another thing to not only share them out loud, but in front of the person who caused those emotions to surface. "
    m "You are stronger than you give yourself credit for."
    mc "Sitting here crying over it doesn't make me feel strong."
    m "But you're still here. Still willing to talk, still willing to try. "
    m "Time heals all wounds. I'm glad to be a bandage for your recovery."
    "I look at Monika and our eyes are locked for what seems like an eternity. "
    "We are snapped back to reality after Monika's phone is ringing."
    "Monika steps back from me wiping her eyes. "
    "She looks at the caller id and then clears her throat and answers, but is immediately bombarded by a frantic Sayori"
    m "It's okay, Sayori. I found him. I'm with him right now. "
    m "Uh huh. Yes. Let Natsuki know she can stop looking and enjoy herself for a while. I'll be back shortly. "
    m "Yes. Yes, I'll ask."
    m "Sayori said she can walk you home if you need the company."
    mc "I...will be alright. I don't think being alone will do me any good right now. If it's okay with you all, I don't mind staying."
    "Monika smiles softly as she relays the message back to Sayori."
    m "He said he'll be okay. We'll be down soon."
    "She puts her phone back in her pocket and holds her hand out to me."
    m "You ready to go back? If you need some more time, I can wait inside for you."
    "My face starts to become a bit red as I grab her hand. It's a bit different this time though. It's less of a handshake and more of a..."
    mc "Uh...yeah! Let's head out. Don't wanna make them worry!"
    "I walk in front of Monika to get the door for her. As she curtsy and walks past me, my heart begins to flutter a bit. "
    "It feels deeper than the admiration I already had. Could it be..."
    scene bg club_day
    "As we return to the club room, we are greeted by a concerned Sayori and Yuri."
    s "Oh my gosh, are you alright?"
    mc "Yeah. Just...a bit heavier than I thought."
    y "I am sorry I was not able to return the favor of fortifying your nerves."
    mc "Unforeseen circumstances, Yuri. Not your fault at all."
    s "I should have shooed her away as soon as I saw her."
    y "What is that now?"
    mc "It...was my...ex"
    y "Oh. Uhh..."
    mc "It's okay Yuri. Don't stress about it. I'm just disappointed I ruined the festival for everyone."
    s "You didn't ruin anything! You went up there and did your best. That's all that matters."
    m "Sayori's right. This event was about us showing what this club is made of. And each and every one of you showed what we have to offer."
    n "I'll assume you still mean that now that I'm here."
    "Natsuki walks in and stands next to me."
    n "Sorry about Kenji, dude. I swear that little-"
    mc "He was nothing. It was uh..."
    s "It was his ex."
    mc "...Thank you, Sayori for that wind-like whisper."
    n "Woah, really? Geez, in that case, you rocked it for at least finishing."
    mc "Can...we talk about something else, please?"
    "The room is silent for a moment."
    n "So, anyone opt to join the club?"
    y "Unfortunately, n-no."
    s "Yeah. A couple people were passing by, but no one really tried to join. At least the cupcakes were a hit!"
    "Natsuki begins to eye the cupcakes counting them in her head."
    n "Well, looks like quite a few came by at least. Cupcakes are almost gone."
    y "Uuuuuu..."
    "I notice Sayori trying to look innocent while badly trying to whistle."
    n "Wait. Don't te- THAT WAS LIKE 15 CUPCAKES!!!"
    s "I was stress eating!!!"
    n "Monika. I vote Sayori goes to the festival now. Maybe we can have her ruin other stands by eating them out of business."
    s "Hey! I wouldn't be able to do that!"
    mc "Don't sell yourself short Sayori. I believe in you."
    s "I-!...Hrrmmmm.....Meanies."
    m "That's actually a good idea, Natsuki. Yuri, feel free to enjoy yourself as well."
    y "Umm...I am quite content to remain here for the duration of the festival. I can use the extra time to read."
    s "Nonsense. Your eyes need a break. If it's too much for you alone, you can hang out with me!"
    n "Heck, we three can all go and leave these two wanderers to hold down the fort. Not like we had anyone coming by anyway."
    "Natsuki face turns white as she realizes what she said. "
    "She looks towards the others and realizes that she slightly brought down the mood."
    n "I-I didn't mean it like that. It's just this school's too stupid to-"
    m "It's okay, Natsuki. Really. You three go ahead. Me and [player] will tidy up while we keep an eye out."
    s "Okay. We can be back in an hour to give you some help. Okay?"
    m "Sure. Have fun."
    "As they leave, Monika sits down at a desk and rests her cheek on her hand. I sit next to her, not knowing what to say at a moment like this."
    m "Heh, what a mess."
    mc "I'm...sorry. I hope my performance isn't what turned people away from joining."
    m "Huh? Believe me, your not to blame for anything."
    mc "Well then, what's going on? Is it something I can help with?"
    "Monika glances at me with an inquisitive face as if we are both talking about two separate things. "
    "She then points to the front of the class."
    m "I...was talking about the literal mess."
    mc "Ah. Well, since we're waiting for visitors anyway..."
    "I get up and start pickup up the cupcake wrappers and discarded handouts."
    "It kind of hurts seeing the work I put in being disregarded this way. I can't imagine how bad Monika feels. "
    "She put her heart into this and this is how it's received?"
    " She joins in with cleaning things up. I can hear a defeated sigh from her. "
    "As we finish up, we sit back down to an empty room. "
    "While there is quite the ruckus around us, nothing seems to be coming from our area. "
    "We see people pass and a few even wave, but no one comes in."
    "Monika lowers her head onto the table and groans."
    m "What am I doing?"
    mc "You...okay?"
    m "I just feel like..."
    "Monika glances over at me. Her worried face soon turns to a bit of a smile. She then pulls out her phone and starts dialing."
    m "Hey Sayori. When you guys get back, just take down the decorations and enjoy the rest of the festival. "
    m "Yeah. No one...I'm sure. Okay. See you around."
    m "Right. Okay, [player]. You're free to go."
    mc "So, no checking for any looky looks?"
    m "If they were interested, they would have been here by now. "
    m "There's still some handouts here. We can just leave them outside the door."
    mc "Are you sure? I kinda feel bad. I mean, all this work and no new members."
    m "*Sigh*...I know. But I don't want to see this as a failure. "
    m "I'm choosing to see this as an affirmation that you guys were right. "
    m "Our club is perfect the way it is now. I'd rather bask in making new memories to cherish forever over sulking about the club's member count."
    "With both of us here without anything else to do, I figure now's as good a time as any to try and hang out together."
    mc "So...you have any other duties from any other clubs?"
    m "Hmm? Oh. No. I'm actually quite surprised my phone isn't blowing up with last minute favor requests."
    mc "Well, if you want, we can...you know. Go...together?"
    "Monika's face gets red as she stands in slight shock before putting on a coy smile."
    m "My, [player], you wouldn't be asking me out on a-"
    "She stops in her tracks as she rethinks her usual teasing."
    m "...f-friendly outing?"
    mc "As long as you're okay with that label. Just so I can make sure to correct any..misconceptions."
    "Monika thinks about it for a moment before smiling back with a hand out for a handshake."
    m "Friendly outing it is."
    "I shake her hand and nod back. "
    "As we look at each other, we both get lost staring for a bit. "
    "While we would usually look away, it's less uncomfortable this ti-"
    y "I knew I should have brought it wi-"
    "Yuri walks in and sees us holding hands as we both stare back at her. "
    "She looks down at our hands and we follow suit. "
    "We immediately release each other's hands and both get redder."
    m "Oh! Yuri! Are you all back?"
    y "Uhh...nnoo. I just...came back for my bag. The others are still..."
    "Yuri swiftly walks over to grab her bag and walks towards the door."
    y "C-carry on!"
    "The door shuts in a rush and we can hear her footsteps speed off."
    mc "Do you think she will...you know. Because the other will definitely make a thing out of it."
    m "Well...that's a problem for Tuesday Monika. Right now, it's time to focus on Festival Monika!"
    mc "Right! Let's see what's out there!"
    "As we approach the festivities, we take in the sheer amount of stands available."
    mc "Wow! This place looks like a legit fair!"
    m "Yeah, everyone went all out this year."
    mc "So, what do you wanna do first?"
    m "Hmmm...that looks like it can be fun."
    "She points to a dunk tank with teachers sitting on the top. "
    "As we approach, I recognized one of the teachers as Mr. Awaga."
    a "Hey! [player]! Get in this line!"
    mc "Uh...you sure?? This won't affect my grade or anything, right?"
    a "Trying won't. Not trying on the other hand..."
    "He puts up his hands as if he's weighing the options."
    mc "*Sigh*. Three balls, please."
    "I look towards the guy and noticed he had a black eye. "
    "I pay for the balls and as soon as the guy hands them to me he runs behind me. Me and Monika look at him quizzically."
    a "Don't worry about him. Some pink hairs first year beaned him in the eye on accident."
    "Yes. Accidentally. "
    "I smile slightly from that as Monika sighs in slight disappointment. "
    "I make my first throw and it flies way over the target."
    a "You know, you can try to hit me. I won't mind."
    "Monika begins to giggle."
    mc "Alright. You asked for it!"
    "I throw my second ball and it hits the edge of the target, but not enough to trigger the seat."
    a "I'd give that throw a solid C-!"
    m "Is that an improvement or an insult?"
    a "For [player]? That's quite-"
    "CLONCK!!" #[MEtal Banging Sound]"
    "My third throw was a bullseye, dunking Mr. Agawa."
    m "Ooh! Nice one!"
    "As he comes back up from the water, he wipes his face and gives a big grin."
    a "I see your lady friend gave quite the inspiration. Now if you can keep that up in class..."
    "I look towards Monika and she is just smiling at the notion."
    mc "You got it, sir. Stay dry."
    a "We'll see. Oh, and don't forget your roadmap tomorrow."
    "As we walk away from the dunk tank, Monika begins to pry."
    m "So, what was that about the roadmap?"
    mc "Oh. The post school goals we have. I've been kinda working on it lately."
    m "Huh. It's funny. I think I had mine filled out my freshman year."
    mc "Knowing you, I'm surprised it was that late."
    "Monika playfully pushes me."
    m "So, what is your goal?"
    mc "Honestly? I don't know. So because of that, I just chose being a writer."
    m "A writer, huh? And what brought this on?"
    mc "Yeah, yeah. Another thing you've helped with."
    m "Glad to see the club is a good influence on you."
    mc "It...really is. I mean, honestly, I am just using it to fill the roadmap out with something I can feasibly do. But, thinking about it...ehh..."
    m "And that's okay. You can be uncertain. It's natural."
    mc "...Is there anything you're uncertain of?"
    "Monika stops walking. I look back at her thinking I crossed the line with that question only to find her staring at...Sayori?"
    s "Hey! Guys! You're here!"
    "Sayori runs towards us with her arms full of food."
    mc "Hey! Where's Natsuki and Yuri?"
    s "Natsuki broke away with some of her class friends after the uh...incident."
    m "Figures. And Yuri didn't meet back up with you two? "
    m "We ran into her while we were leaving."
    s "Hmm? I thought she stayed in the club room. I think the crowds were a bit much for her."
    mc "I can see that. She's probably nose deep in her latest novel. "
    mc "And I see you found the food stands. Trying one of everything?"
    s "For your information, I was taking some to Yuri while we finished taking down the decorations."
    m "I'm sure she'll appreciate the sentiment."
    mc "When you're done, let us know and we can wait for you."
    s "Naah. I don't wanna feel like a third wheel. I'll just..."
    "Sayori begins to run off to the school."
    s "Leave you two on your date! Byeeee~"
    "I look at Monika and she looks back at me. We both shake our heads."
    mc "Damn that Sayori..."
    m "It's okay. I already expected her to call this a date."
    mc "Huh? Oh. I meant her with the food. Now I'm kinda hungry."
    m "Oh, uhh heh. Yeah. Let's see what-"
    "*POP* [Balloon Pop Sound]"
    "We're caught off guard by a loud sound from an attraction we were passing by. "
    "It's a dart game where the goal is to pop the balloons. "
    "I see there isn't a line and it looks pretty straightforward."
    mc "You wanna try this while we're here?"
    m "If you're up for it."
    mc "I'm so up for it, I'm down."
    "Monika rolls her eyes as she chuckles."
    m "Only you..."
    st "Alright folks! 5 darts per try! 3 pops get a small prize, 4 pops for the mid, and 5 gets a choice of big win prizes! "
    st "But that's not all! We got 4 balloons left with the grand prize ticket hidden! Pop it and get the grand prize!"
    "I look over the prizes and they're just as you would expect. "
    "The small prizes are basically cheap candy and pencils. "
    "The mid are just keychains and packs of gum. "
    "And the 'big' prizes are yo-yos, fidget spinners, and food coupons for some of the events here. "
    "I mean, I wouldn't really expect anything more for a student ran game."
    "I take a look and see 4 stuffed bears about the size of my torso. I take it those are the grand prizes."
    mc "Hey buddy, two tries here."
    "I pay the attendant and give 5 of the darts to Monika."
    mc "You wanna go first?"
    m "After you."
    mc "Alright."
    "I throw my darts and pop 3 of the 5."
    st "Alright, small winner. hurry up and pick."
    "I grab one of the pencils since it seemed the most reasonable. "
    "As Monika steps up, she throws the darts as if she's done this before. Throw after throw pops a balloon. Her last dart reveals a piece of paper."
    st "We got ourselves a big winner here! Perfect throws with a grand prize finale!"
    "The perfect combination of skill and luck. I wouldn't have expected any less. "
    "They pull down one of the bears and hand it to Monika."
    st "Here you go, miss."
    "He looks over towards me with a condescending grin."
    st "Tough luck, buddy. Would have been a good date win."
    "Monika leans in to whisper in my ear."
    m "Well, I guess it's good this isn't a date then."
    "She giggles in the bear as the student lightly chuckles."
    "[player]:...I mean...I did buy the darts so...."
    st "Oh, don't forget your choice of regular prize as well."
    "Monika looks over the prizes. She grabs one of the food stand vouchers from the stack."
    m "We were on our way to get some food, so this will come in handy."
    st "Sure you don't wanna try again and beat your girl, buddy."
    "I look towards Monika, who is just trying her darndest to look as adorable as possible cuddling the plushie."
    mc "I'm alright."
    "We walk off towards the food stands with Monika grinning ear to ear in high spirits. "
    "Looking at the food voucher Monika got, it looks like it's only for sophomore run stands. "
    "As we check the choices, the abundance of meat based stands make the option choices quite slim."
    mc "Geez. Is someone's parents a butcher or something?"
    m "It's alright. I know vegetables aren't much of a big seller. Despite my personal tastes, you don't win crowds with salad."
    mc "Hey! What about this!"
    "Monika looks at where I was pointing and her face gets a bit flushed."
    mc "What, you never had an elephant ear?"
    m "Uhh...that seems a bit of an exotic taste..."
    mc "Don't worry. It's just a name. It's actually just fried dough with sugar on it. It's a festival staple. You've got to try it!"
    m "Well, if you're familiar with it, I'll give it a try."
    "Monika hands me her voucher as we stand in line. "
    "As some of the other customers walk past with their orders, Monika takes a sniff."
    m "Mmmm...That smells heavenly. But..."
    mc "But what?"
    m "If you don't mind, can we just split one? I don't think I can eat a whole one."
    mc "Oh. Yeah. No problem. These things are massively Sweet. Good to the taste, bad to your health. "
    mc "Sayori's actually the only one I can think of who has eaten a full one of these."
    m "Why am I not surprised."
    "As we reach the front, I trade the voucher for one elephant ear. "
    "I tear off a piece and start chewing and the flavor hits me right in the nostalgia."
    mc "Man, it's been ages since I've tasted this!"
    "I rip another piece off and hold it towards Monika's mouth. She takes a bite and begins to chew. "
    "As we pass some of the other students, we realize that they're whispering. "
    "We both stop in our tracks. Monika looks down at the piece of dough still hanging out of her mouth. "
    "She then slowly turns red as she looks towards me. I soon adopt the same shade as her."
    mc "I-I'm sorry! Your hands were full and uh.."
    m "It's-it's okay. I didn't think anything of it it's just-"
    mc "I was helping you."
    m "Yeah! Friendly helping hand!"
    mc "You don't wanna get your bear dirty!"
    m "Right! Right. Yeah..."
    mc "So...uh...is it okay to..."
    m "Ummhmm. Don't worry I would do the same for you."
    "..."
    m "-RI!! I would do the same for Yuri! You know, if I were you and she was me. Cus that's what friends do!"
    mc "Ha ha..right! Yeah. Totally."
    m "So..,uhh..,that's really good and I would like some more. If you don't mind."
    mc "Uhh, yeah. Of course."
    "We continue through the place as I occasionally feed her pieces of elephant ear. "
    "While she always has a slightly embarrassed look on her face as I hold it up to her mouth, it's quickly replaced with a joyful smile as she chews."
    qu "Hey! You Two!!"
    "We're cut off by a student dressed as a magical girl. She looks to be a first year student."
    st "Yes. You two look madly in love. Dare to test that love in our compatibility test?"
    "[player]/Monika: Uhhh....."
    st "Come on, buddy! Show her how committed you are! Prove your love to her!"
    mc "Sorry to disappoint, but we're not-"
    st "Got it. Friend zoned."
    "She looks Monika up and down while whistling."
    st "Heh heh...WAY out of your league."
    mc "H-hey!"
    st "Don't worry, it'll be quick. If you need the nail in the coffin, this can be it, sister."
    m "Now I don't- I mean I-ehhhh..."
    "She walks closer to us and begins to speak low to us."
    st "Alright, look. My class is giving a prize to the most results. You guys can bomb it for all I care, I just need to catch up."
    "Me and Monika look at each other before being dragged by her into the tent. Inside is a table with two tablets on opposite sides of the table. "
    "The student guides us to the tablets."
    st "Alright, you two. Here's how it'll go. I'll start the quiz in a moment. You two just answer quickly. "
    st "You gotta get in 10 answers, so just go with your gut."
    mc "Wait, what's going on?"
    st "First part is a quiz, now go!"
    "As she presses something on her tablet, the one in front of me starts flashing images and then a multiple choice option."
    mc "Wait, what? Gooey, ceremony, republic- hey!"
    "The choices go away in a flash and another image shows up quickly and then disappears, leaving completely different options. "
    "I look up to Monika and she is just as confused as I am."
    m "I think I- wait! Can I-"
    st "No take backs! All answers final!"
    "Realizing the insanity of the situation I shrug and start spamming the first option. "
    "It seems like Monika had the same idea and she follows suit. Soon the screen has a palm print on it"
    st "Alright. Now for the final check. Place your hands on the screen and look deep into each other's eyes."
    mc "Is this really necessary?!"
    st "The test doesn't lie. "
    st "Stare into that pool of emerald bliss while you can, you scrub! "
    st "And you...just keep your laughing to a minimum. I mean, he is funny looking, but-"
    mc "Are all the insults necessary?!"
    "Monika begins chuckling and I look over to her. "
    "Our eyes meet like they have dozens of other times. It's seems the closer we get, the more comfortable we are with doing thi-"
    st "The results are in! You two are...wait. Hold up. That can't be-"
    "She gasps while looking at the two of us before a cheeky smile crawls on her face."
    st "I don't know how you pulled it, my guy, but you struck gold. Results came back as â€˜Madly in love'!"
    "Both of our faces turn red as we look at each other."
    st "It says you two share an intimate understanding that syncs your souls into an unbreakable bond."
    "[player]/Monika: Well that's just redicu-"
    "...."
    "[player]/Monika: ..lous"
    st "Well that's a sync if I've ever seen one. "
    st "Welp, buddy! It's your lucky day. How bout you hit your wingman up with a nice tip."
    "She holds her hand out to me and I just stare at it. I give her a low five."
    mc "Here's a tip: don't quit your day job."
    st "I see you're not with him for the jokes."
    m "Oh, he has some good qualities. We all need our faults."
    mc "Wait, so my sense of humor is a fault?"
    m "Well..."
    "Monika begins walking out the tent without answering the question, leading me to follow her."
    st "Have fun, love birds!"
    m "Well, that was an experience."
    mc "Yeah. I highly doubt the accuracy of that. I mean, we're not even dating."
    m "I can understand the confusion. The more that I think about it, the more this is starting to look like a date."
    mc "Do...you want to consider this a date?"
    "I glance at Monika and she is looking down to the ground with a slight smile as her face gets red."
    m "While I'm not one to follow peer pressure, I-"
    qu "Monika! Thank god I ran into you!"
    "We both look up and see a frantic girl approaching."
    m "K-Kazumi? What's wrong?"
    "Kazumi: Quick, can you step in as our debate moderator? Ryukia had to drop out at the last minute."
    m "Uh..I don't know if I can-"
    "Kazumi; It's nothing fancy. We just need someone who knows the rules. Everyone else is busy with their class events or stands."
    "Monika looks towards me with a sad face. Kazumi looks towards me as well and gasps."
    "Kazumi: S-sorry. I didn't mean to interrupt your date."
    "Monika gets surprised and red."
    "This really does keep happening doesn't it? If I'm being honest, I don't really mind calling it a date. "
    "And by Monika's demeanor...I think she might actually prefer it."
    m "It's...not a-"
    mc "It's not a big deal. You can go ahead and help them out. I'll be fine."
    m "You...you sure? It's okay that we-"
    "I walk forward and surprise her with a hug while also taking hold of the bear."
    mc "Heh...I can 'bear'ly hug you like this."
    "Monika leans her head on my head."
    m "Hee hee...you dork."
    mc "I can put this fella back in the clubroom for when you're done. I'll let Sayori know what's up."
    m "Yeah. Okay. Thanks. I...really did have a nice time."
    mc "Me too. Looking forward to doing this again."
    "Kazumi: Alright, then. Come on! We're running short on time!"
    "Kazumi begins dragging Monika off. Monika waves to me and I use the bear's hand to wave back. "
    "As I stand there alone with my thoughts, the first thing that hits me is how much the bear now smells like Monika."
    "..."
    "I'm starting to think Sayori and Natsuki were right. Maybe Monika does have feelings for me. "
    "And I.."
    "..."
    "I think I feel the same."
    scene bg club_day
    "As I enter the clubroom, I see that the decorations are all down and the room almost empty. "
    "The only one here is Yuri, reading alone. She looks up at me and smiles."
    y "[player]! Glad to see that you are in better spirits."
    mc "Yeah. Me and Monika had fun. I take it festivals aren't your thing."
    y "Sadly, no. "
    y "While the attractions are appealing, and I do find some of the games enjoyable, it is a bit too...much socially."
    mc "I can see that. Crowds can be bothersome."
    y "Indeed. Oh, might I ask about your new friend there?"
    mc "Oh this? He's Monika's. I'm just dropping him off at the club for her."
    "I set him on the front desk and begin to walk away, but then I'm struck with an idea. "
    "I grab a book from the bookshelf and move the bear in the front room chair. "
    "I place the book in the bear's hands and position it to make it look like it's reading."
    y "Hee hee...adorable! It looks like we have gotten a new club member after all."
    mc "Heh, yeah. He'll make a perfect addition."
    scene bg bedroom
    "As I lay in bed, I reflect on the day I had. "
    "While my performance was...traumatic,I gotta say, the girls really helped. "
    "It's reassuring how much they've got my back. "
    "As I twirl the pencil I won at the festival, I can't help but feel inspired. "
    "I sit up and go over to my desk and pull out the information on my roadmap"
    mc "Alright. Writer it is."
    "After a couple hours, I now have a detailed goals list for the next 5 years. "
    "Even if this falls through, at least I have the knowledge of it. "
    "I wash up and quickly fall asleep feeling a huge weight off my shoulders."
    return